# Run a Comgr test with the build-tree library on CMake before 3.22.
if(NOT DEFINED COMGR_TEST_EXECUTABLE OR NOT DEFINED COMGR_TEST_LIBRARY_DIR)
  message(FATAL_ERROR "Missing Comgr test executable or library directory")
endif()

set(ENV{AMD_COMGR_CACHE} 0)
if(WIN32)
  if("$ENV{PATH}" STREQUAL "")
    set(ENV{PATH} "${COMGR_TEST_LIBRARY_DIR}")
  else()
    set(ENV{PATH} "${COMGR_TEST_LIBRARY_DIR};$ENV{PATH}")
  endif()
else()
  if("$ENV{LD_LIBRARY_PATH}" STREQUAL "")
    set(ENV{LD_LIBRARY_PATH} "${COMGR_TEST_LIBRARY_DIR}")
  else()
    set(ENV{LD_LIBRARY_PATH} "${COMGR_TEST_LIBRARY_DIR}:$ENV{LD_LIBRARY_PATH}")
  endif()
endif()

execute_process(COMMAND "${COMGR_TEST_EXECUTABLE}" RESULT_VARIABLE Result)
if(NOT "${Result}" STREQUAL "0")
  message(FATAL_ERROR "${COMGR_TEST_EXECUTABLE} failed: ${Result}")
endif()
