; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=amdgcn-- -mcpu=gfx1300 -passes=amdgpu-atomic-optimizer %s | FileCheck -check-prefix=IR %s

declare i32 @llvm.amdgcn.workitem.id.x()

define amdgpu_kernel void @atomicrmw_add_divergent(i32 addrspace(1)* %out, i32 addrspace(1)* %in) {
; IR-LABEL: define amdgpu_kernel void @atomicrmw_add_divergent(
; IR-SAME: ptr addrspace(1) [[OUT:%.*]], ptr addrspace(1) [[IN:%.*]]) #[[ATTR1:[0-9]+]] {
; IR-NEXT:  [[ENTRY:.*]]:
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[IN]], i32 [[TID]]
; IR-NEXT:    [[TMP0:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TID]], i32 [[TID]])
; IR-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.sum.i32(i32 5, i32 [[TMP0]], i1 false)
; IR-NEXT:    [[TMP2:%.*]] = add i32 5, [[TMP1]]
; IR-NEXT:    [[TMP3:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP4:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP0]], i1 true)
; IR-NEXT:    [[TMP5:%.*]] = sub i32 31, [[TMP4]]
; IR-NEXT:    [[TMP6:%.*]] = icmp eq i32 [[TMP3]], [[TMP5]]
; IR-NEXT:    br i1 [[TMP6]], label %[[BB7:.*]], label %[[BB9:.*]]
; IR:       [[BB7]]:
; IR-NEXT:    [[TMP8:%.*]] = atomicrmw add ptr addrspace(1) [[PTR]], i32 [[TMP2]] syncscope("agent") monotonic, align 4
; IR-NEXT:    br label %[[BB9]]
; IR:       [[BB9]]:
; IR-NEXT:    [[TMP10:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[TMP8]], %[[BB7]] ]
; IR-NEXT:    [[TMP11:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP10]], i32 [[TMP5]])
; IR-NEXT:    [[OLD:%.*]] = add i32 [[TMP11]], [[TMP1]]
; IR-NEXT:    store i32 [[OLD]], ptr addrspace(1) [[OUT]], align 4
; IR-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %ptr = getelementptr i32, i32 addrspace(1)* %in, i32 %tid
  %old = atomicrmw add i32 addrspace(1)* %ptr, i32 5 syncscope("agent") monotonic
  store i32 %old, i32 addrspace(1)* %out
  ret void
}

define amdgpu_kernel void @example_atomic_64bit_opaque(ptr addrspace(1) %in, ptr addrspace(1) %out) {
; IR-LABEL: define amdgpu_kernel void @example_atomic_64bit_opaque(
; IR-SAME: ptr addrspace(1) [[IN:%.*]], ptr addrspace(1) [[OUT:%.*]]) #[[ATTR1]] {
; IR-NEXT:  [[ENTRY:.*]]:
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[IDX:%.*]] = zext i32 [[TID]] to i64
; IR-NEXT:    [[PTR:%.*]] = getelementptr i64, ptr addrspace(1) [[IN]], i64 4
; IR-NEXT:    [[TMP0:%.*]] = call i32 @llvm.amdgcn.ballot.i32(i1 true)
; IR-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 [[TMP0]], i32 0)
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.ctpop.i32(i32 [[TMP0]])
; IR-NEXT:    [[TMP3:%.*]] = mul i32 5, [[TMP2]]
; IR-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[TMP1]], 0
; IR-NEXT:    br i1 [[TMP4]], label %[[BB5:.*]], label %[[BB7:.*]]
; IR:       [[BB5]]:
; IR-NEXT:    [[TMP6:%.*]] = atomicrmw add ptr addrspace(1) [[PTR]], i32 [[TMP3]] syncscope("agent") monotonic, align 4
; IR-NEXT:    br label %[[BB7]]
; IR:       [[BB7]]:
; IR-NEXT:    [[TMP8:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[TMP6]], %[[BB5]] ]
; IR-NEXT:    [[TMP9:%.*]] = call i32 @llvm.amdgcn.readfirstlane.i32(i32 [[TMP8]])
; IR-NEXT:    [[TMP10:%.*]] = mul i32 5, [[TMP1]]
; IR-NEXT:    [[TMP11:%.*]] = add i32 [[TMP9]], [[TMP10]]
; IR-NEXT:    store i32 [[TMP11]], ptr addrspace(1) [[OUT]], align 8
; IR-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %idx = zext i32 %tid to i64
  %ptr = getelementptr i64, ptr addrspace(1) %in, i64 4
  %old = atomicrmw add ptr addrspace(1) %ptr, i32 5 syncscope("agent") monotonic
  store i32 %old, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @example_atomic_64bit_opaque_2(ptr addrspace(1) %in, ptr addrspace(1) %out) {
; IR-LABEL: define amdgpu_kernel void @example_atomic_64bit_opaque_2(
; IR-SAME: ptr addrspace(1) [[IN:%.*]], ptr addrspace(1) [[OUT:%.*]]) #[[ATTR1]] {
; IR-NEXT:  [[ENTRY:.*]]:
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[IDX:%.*]] = zext i32 [[TID]] to i64
; IR-NEXT:    [[PTR:%.*]] = getelementptr i64, ptr addrspace(1) [[IN]], i64 [[IDX]]
; IR-NEXT:    [[TMP1:%.*]] = trunc i64 [[IDX]] to i32
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP1]], i32 [[TMP1]])
; IR-NEXT:    [[TMP7:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.sum.i32(i32 5, i32 [[TMP6]], i1 false)
; IR-NEXT:    [[TMP8:%.*]] = add i32 5, [[TMP7]]
; IR-NEXT:    [[TMP9:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP10:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP6]], i1 true)
; IR-NEXT:    [[TMP11:%.*]] = sub i32 31, [[TMP10]]
; IR-NEXT:    [[TMP12:%.*]] = icmp eq i32 [[TMP9]], [[TMP11]]
; IR-NEXT:    br i1 [[TMP12]], label %[[BB8:.*]], label %[[BB10:.*]]
; IR:       [[BB8]]:
; IR-NEXT:    [[TMP14:%.*]] = atomicrmw add ptr addrspace(1) [[PTR]], i32 [[TMP8]] syncscope("agent") monotonic, align 4
; IR-NEXT:    br label %[[BB10]]
; IR:       [[BB10]]:
; IR-NEXT:    [[TMP16:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[TMP14]], %[[BB8]] ]
; IR-NEXT:    [[TMP17:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP16]], i32 [[TMP11]])
; IR-NEXT:    [[OLD:%.*]] = add i32 [[TMP17]], [[TMP7]]
; IR-NEXT:    store i32 [[OLD]], ptr addrspace(1) [[OUT]], align 8
; IR-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %idx = zext i32 %tid to i64
  %ptr = getelementptr i64, ptr addrspace(1) %in, i64 %idx
  %old = atomicrmw add ptr addrspace(1) %ptr, i32 5 syncscope("agent") monotonic
  store i32 %old, ptr addrspace(1) %out, align 8
  ret void
}
