; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=amdgcn-- -mcpu=gfx1300 -passes=amdgpu-atomic-optimizer %s | FileCheck -check-prefix=IR %s

@lds_mem = internal addrspace(3) global [1024 x i32] poison, align 4
@histogram_bins = internal addrspace(3) global [64 x i32] poison, align 4

define amdgpu_kernel void @test_atomicrmw_add_divergent_base_divergent_offset(ptr addrspace(1) %base_ptrs, ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @test_atomicrmw_add_divergent_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[BASE_PTRS:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0:[0-9]+]] {
; IR-NEXT:  [[ENTRY:.*]]:
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[BASE_PTR_ADDR:%.*]] = getelementptr i32, ptr addrspace(1) [[BASE_PTRS]], i32 [[TID]]
; IR-NEXT:    [[BASE_PTR_I32:%.*]] = load i32, ptr addrspace(1) [[BASE_PTR_ADDR]], align 4
; IR-NEXT:    [[BASE_PTR:%.*]] = inttoptr i32 [[BASE_PTR_I32]] to ptr addrspace(3)
; IR-NEXT:    [[PTR_OFFSET:%.*]] = getelementptr i8, ptr addrspace(3) [[BASE_PTR]], i32 4
; IR-NEXT:    [[PTR_DIVERGENT:%.*]] = getelementptr i32, ptr addrspace(3) [[PTR_OFFSET]], i32 [[TID]]
; IR-NEXT:    [[VALUE:%.*]] = add i32 [[TID]], 42
; IR-NEXT:    [[TMP0:%.*]] = ptrtoint ptr addrspace(3) [[PTR_DIVERGENT]] to i32
; IR-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP0]], i32 [[TMP0]])
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.sum.i32(i32 [[VALUE]], i32 [[TMP1]], i1 false)
; IR-NEXT:    [[TMP3:%.*]] = add i32 [[VALUE]], [[TMP2]]
; IR-NEXT:    [[TMP4:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP1]], i1 true)
; IR-NEXT:    [[TMP6:%.*]] = sub i32 31, [[TMP5]]
; IR-NEXT:    [[TMP7:%.*]] = icmp eq i32 [[TMP4]], [[TMP6]]
; IR-NEXT:    br i1 [[TMP7]], label %[[BB8:.*]], label %[[BB10:.*]]
; IR:       [[BB8]]:
; IR-NEXT:    [[TMP9:%.*]] = atomicrmw add ptr addrspace(3) [[PTR_DIVERGENT]], i32 [[TMP3]] seq_cst, align 4
; IR-NEXT:    br label %[[BB10]]
; IR:       [[BB10]]:
; IR-NEXT:    [[TMP11:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[TMP9]], %[[BB8]] ]
; IR-NEXT:    [[TMP12:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP11]], i32 [[TMP6]])
; IR-NEXT:    [[TMP13:%.*]] = add i32 [[TMP12]], [[TMP2]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP13]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %base_ptr_addr = getelementptr i32, ptr addrspace(1) %base_ptrs, i32 %tid
  %base_ptr_i32 = load i32, ptr addrspace(1) %base_ptr_addr
  %base_ptr = inttoptr i32 %base_ptr_i32 to ptr addrspace(3)
  %ptr_offset = getelementptr i8, ptr addrspace(3) %base_ptr, i32 4
  %ptr_divergent = getelementptr i32, ptr addrspace(3) %ptr_offset, i32 %tid
  %value = add i32 %tid, 42
  %old = atomicrmw add ptr addrspace(3) %ptr_divergent, i32 %value seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %old, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @test_atomicrmw_sub_divergent_base_divergent_offset(ptr addrspace(1) %base_ptrs, ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @test_atomicrmw_sub_divergent_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[BASE_PTRS:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:  [[ENTRY:.*]]:
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[BASE_PTR_ADDR:%.*]] = getelementptr i32, ptr addrspace(1) [[BASE_PTRS]], i32 [[TID]]
; IR-NEXT:    [[BASE_PTR_I32:%.*]] = load i32, ptr addrspace(1) [[BASE_PTR_ADDR]], align 4
; IR-NEXT:    [[BASE_PTR:%.*]] = inttoptr i32 [[BASE_PTR_I32]] to ptr addrspace(3)
; IR-NEXT:    [[PTR_OFFSET:%.*]] = getelementptr i8, ptr addrspace(3) [[BASE_PTR]], i32 4
; IR-NEXT:    [[PTR_DIVERGENT:%.*]] = getelementptr i32, ptr addrspace(3) [[PTR_OFFSET]], i32 [[TID]]
; IR-NEXT:    [[VALUE:%.*]] = add i32 [[TID]], 42
; IR-NEXT:    [[TMP0:%.*]] = ptrtoint ptr addrspace(3) [[PTR_DIVERGENT]] to i32
; IR-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP0]], i32 [[TMP0]])
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.sum.i32(i32 [[VALUE]], i32 [[TMP1]], i1 false)
; IR-NEXT:    [[TMP3:%.*]] = add i32 [[VALUE]], [[TMP2]]
; IR-NEXT:    [[TMP4:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP1]], i1 true)
; IR-NEXT:    [[TMP6:%.*]] = sub i32 31, [[TMP5]]
; IR-NEXT:    [[TMP7:%.*]] = icmp eq i32 [[TMP4]], [[TMP6]]
; IR-NEXT:    br i1 [[TMP7]], label %[[BB8:.*]], label %[[BB10:.*]]
; IR:       [[BB8]]:
; IR-NEXT:    [[TMP9:%.*]] = atomicrmw sub ptr addrspace(3) [[PTR_DIVERGENT]], i32 [[TMP3]] seq_cst, align 4
; IR-NEXT:    br label %[[BB10]]
; IR:       [[BB10]]:
; IR-NEXT:    [[TMP11:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[TMP9]], %[[BB8]] ]
; IR-NEXT:    [[TMP12:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP11]], i32 [[TMP6]])
; IR-NEXT:    [[TMP13:%.*]] = sub i32 [[TMP12]], [[TMP2]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP13]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %base_ptr_addr = getelementptr i32, ptr addrspace(1) %base_ptrs, i32 %tid
  %base_ptr_i32 = load i32, ptr addrspace(1) %base_ptr_addr
  %base_ptr = inttoptr i32 %base_ptr_i32 to ptr addrspace(3)
  %ptr_offset = getelementptr i8, ptr addrspace(3) %base_ptr, i32 4
  %ptr_divergent = getelementptr i32, ptr addrspace(3) %ptr_offset, i32 %tid
  %value = add i32 %tid, 42
  %old = atomicrmw sub ptr addrspace(3) %ptr_divergent, i32 %value seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %old, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @test_atomicrmw_and_divergent_base_divergent_offset(ptr addrspace(1) %base_ptrs, ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @test_atomicrmw_and_divergent_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[BASE_PTRS:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:  [[ENTRY:.*]]:
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[BASE_PTR_ADDR:%.*]] = getelementptr i32, ptr addrspace(1) [[BASE_PTRS]], i32 [[TID]]
; IR-NEXT:    [[BASE_PTR_I32:%.*]] = load i32, ptr addrspace(1) [[BASE_PTR_ADDR]], align 4
; IR-NEXT:    [[BASE_PTR:%.*]] = inttoptr i32 [[BASE_PTR_I32]] to ptr addrspace(3)
; IR-NEXT:    [[PTR_OFFSET:%.*]] = getelementptr i8, ptr addrspace(3) [[BASE_PTR]], i32 4
; IR-NEXT:    [[PTR_DIVERGENT:%.*]] = getelementptr i32, ptr addrspace(3) [[PTR_OFFSET]], i32 [[TID]]
; IR-NEXT:    [[VALUE:%.*]] = add i32 [[TID]], 42
; IR-NEXT:    [[TMP0:%.*]] = ptrtoint ptr addrspace(3) [[PTR_DIVERGENT]] to i32
; IR-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP0]], i32 [[TMP0]])
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.and.b32(i32 [[VALUE]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = and i32 [[VALUE]], [[TMP2]]
; IR-NEXT:    [[TMP4:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP1]], i1 true)
; IR-NEXT:    [[TMP6:%.*]] = sub i32 31, [[TMP5]]
; IR-NEXT:    [[TMP7:%.*]] = icmp eq i32 [[TMP4]], [[TMP6]]
; IR-NEXT:    br i1 [[TMP7]], label %[[BB8:.*]], label %[[BB10:.*]]
; IR:       [[BB8]]:
; IR-NEXT:    [[TMP9:%.*]] = atomicrmw and ptr addrspace(3) [[PTR_DIVERGENT]], i32 [[TMP3]] seq_cst, align 4
; IR-NEXT:    br label %[[BB10]]
; IR:       [[BB10]]:
; IR-NEXT:    [[TMP11:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[TMP9]], %[[BB8]] ]
; IR-NEXT:    [[TMP12:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP11]], i32 [[TMP6]])
; IR-NEXT:    [[TMP13:%.*]] = and i32 [[TMP12]], [[TMP2]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP13]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %base_ptr_addr = getelementptr i32, ptr addrspace(1) %base_ptrs, i32 %tid
  %base_ptr_i32 = load i32, ptr addrspace(1) %base_ptr_addr
  %base_ptr = inttoptr i32 %base_ptr_i32 to ptr addrspace(3)
  %ptr_offset = getelementptr i8, ptr addrspace(3) %base_ptr, i32 4
  %ptr_divergent = getelementptr i32, ptr addrspace(3) %ptr_offset, i32 %tid
  %value = add i32 %tid, 42
  %old = atomicrmw and ptr addrspace(3) %ptr_divergent, i32 %value seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %old, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @test_atomicrmw_or_divergent_base_divergent_offset(ptr addrspace(1) %base_ptrs, ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @test_atomicrmw_or_divergent_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[BASE_PTRS:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:  [[ENTRY:.*]]:
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[BASE_PTR_ADDR:%.*]] = getelementptr i32, ptr addrspace(1) [[BASE_PTRS]], i32 [[TID]]
; IR-NEXT:    [[BASE_PTR_I32:%.*]] = load i32, ptr addrspace(1) [[BASE_PTR_ADDR]], align 4
; IR-NEXT:    [[BASE_PTR:%.*]] = inttoptr i32 [[BASE_PTR_I32]] to ptr addrspace(3)
; IR-NEXT:    [[PTR_OFFSET:%.*]] = getelementptr i8, ptr addrspace(3) [[BASE_PTR]], i32 4
; IR-NEXT:    [[PTR_DIVERGENT:%.*]] = getelementptr i32, ptr addrspace(3) [[PTR_OFFSET]], i32 [[TID]]
; IR-NEXT:    [[VALUE:%.*]] = add i32 [[TID]], 42
; IR-NEXT:    [[TMP0:%.*]] = ptrtoint ptr addrspace(3) [[PTR_DIVERGENT]] to i32
; IR-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP0]], i32 [[TMP0]])
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.or.b32(i32 [[VALUE]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = or i32 [[VALUE]], [[TMP2]]
; IR-NEXT:    [[TMP4:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP1]], i1 true)
; IR-NEXT:    [[TMP6:%.*]] = sub i32 31, [[TMP5]]
; IR-NEXT:    [[TMP7:%.*]] = icmp eq i32 [[TMP4]], [[TMP6]]
; IR-NEXT:    br i1 [[TMP7]], label %[[BB8:.*]], label %[[BB10:.*]]
; IR:       [[BB8]]:
; IR-NEXT:    [[TMP9:%.*]] = atomicrmw or ptr addrspace(3) [[PTR_DIVERGENT]], i32 [[TMP3]] seq_cst, align 4
; IR-NEXT:    br label %[[BB10]]
; IR:       [[BB10]]:
; IR-NEXT:    [[TMP11:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[TMP9]], %[[BB8]] ]
; IR-NEXT:    [[TMP12:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP11]], i32 [[TMP6]])
; IR-NEXT:    [[TMP13:%.*]] = or i32 [[TMP12]], [[TMP2]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP13]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %base_ptr_addr = getelementptr i32, ptr addrspace(1) %base_ptrs, i32 %tid
  %base_ptr_i32 = load i32, ptr addrspace(1) %base_ptr_addr
  %base_ptr = inttoptr i32 %base_ptr_i32 to ptr addrspace(3)
  %ptr_offset = getelementptr i8, ptr addrspace(3) %base_ptr, i32 4
  %ptr_divergent = getelementptr i32, ptr addrspace(3) %ptr_offset, i32 %tid
  %value = add i32 %tid, 42
  %old = atomicrmw or ptr addrspace(3) %ptr_divergent, i32 %value seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %old, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @test_atomicrmw_xor_divergent_base_divergent_offset(ptr addrspace(1) %base_ptrs, ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @test_atomicrmw_xor_divergent_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[BASE_PTRS:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:  [[ENTRY:.*]]:
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[BASE_PTR_ADDR:%.*]] = getelementptr i32, ptr addrspace(1) [[BASE_PTRS]], i32 [[TID]]
; IR-NEXT:    [[BASE_PTR_I32:%.*]] = load i32, ptr addrspace(1) [[BASE_PTR_ADDR]], align 4
; IR-NEXT:    [[BASE_PTR:%.*]] = inttoptr i32 [[BASE_PTR_I32]] to ptr addrspace(3)
; IR-NEXT:    [[PTR_OFFSET:%.*]] = getelementptr i8, ptr addrspace(3) [[BASE_PTR]], i32 4
; IR-NEXT:    [[PTR_DIVERGENT:%.*]] = getelementptr i32, ptr addrspace(3) [[PTR_OFFSET]], i32 [[TID]]
; IR-NEXT:    [[VALUE:%.*]] = add i32 [[TID]], 42
; IR-NEXT:    [[TMP0:%.*]] = ptrtoint ptr addrspace(3) [[PTR_DIVERGENT]] to i32
; IR-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP0]], i32 [[TMP0]])
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.xor.b32(i32 [[VALUE]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = xor i32 [[VALUE]], [[TMP2]]
; IR-NEXT:    [[TMP4:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP1]], i1 true)
; IR-NEXT:    [[TMP6:%.*]] = sub i32 31, [[TMP5]]
; IR-NEXT:    [[TMP7:%.*]] = icmp eq i32 [[TMP4]], [[TMP6]]
; IR-NEXT:    br i1 [[TMP7]], label %[[BB8:.*]], label %[[BB10:.*]]
; IR:       [[BB8]]:
; IR-NEXT:    [[TMP9:%.*]] = atomicrmw xor ptr addrspace(3) [[PTR_DIVERGENT]], i32 [[TMP3]] seq_cst, align 4
; IR-NEXT:    br label %[[BB10]]
; IR:       [[BB10]]:
; IR-NEXT:    [[TMP11:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[TMP9]], %[[BB8]] ]
; IR-NEXT:    [[TMP12:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP11]], i32 [[TMP6]])
; IR-NEXT:    [[TMP13:%.*]] = xor i32 [[TMP12]], [[TMP2]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP13]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %base_ptr_addr = getelementptr i32, ptr addrspace(1) %base_ptrs, i32 %tid
  %base_ptr_i32 = load i32, ptr addrspace(1) %base_ptr_addr
  %base_ptr = inttoptr i32 %base_ptr_i32 to ptr addrspace(3)
  %ptr_offset = getelementptr i8, ptr addrspace(3) %base_ptr, i32 4
  %ptr_divergent = getelementptr i32, ptr addrspace(3) %ptr_offset, i32 %tid
  %value = add i32 %tid, 42
  %old = atomicrmw xor ptr addrspace(3) %ptr_divergent, i32 %value seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %old, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @test_atomicrmw_min_divergent_base_divergent_offset(ptr addrspace(1) %base_ptrs, ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @test_atomicrmw_min_divergent_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[BASE_PTRS:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:  [[ENTRY:.*]]:
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[BASE_PTR_ADDR:%.*]] = getelementptr i32, ptr addrspace(1) [[BASE_PTRS]], i32 [[TID]]
; IR-NEXT:    [[BASE_PTR_I32:%.*]] = load i32, ptr addrspace(1) [[BASE_PTR_ADDR]], align 4
; IR-NEXT:    [[BASE_PTR:%.*]] = inttoptr i32 [[BASE_PTR_I32]] to ptr addrspace(3)
; IR-NEXT:    [[PTR_OFFSET:%.*]] = getelementptr i8, ptr addrspace(3) [[BASE_PTR]], i32 4
; IR-NEXT:    [[PTR_DIVERGENT:%.*]] = getelementptr i32, ptr addrspace(3) [[PTR_OFFSET]], i32 [[TID]]
; IR-NEXT:    [[VALUE:%.*]] = add i32 [[TID]], 42
; IR-NEXT:    [[TMP0:%.*]] = ptrtoint ptr addrspace(3) [[PTR_DIVERGENT]] to i32
; IR-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP0]], i32 [[TMP0]])
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.min.i32(i32 [[VALUE]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = icmp slt i32 [[VALUE]], [[TMP2]]
; IR-NEXT:    [[TMP4:%.*]] = select i1 [[TMP3]], i32 [[VALUE]], i32 [[TMP2]]
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP1]], i1 true)
; IR-NEXT:    [[TMP7:%.*]] = sub i32 31, [[TMP6]]
; IR-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[TMP5]], [[TMP7]]
; IR-NEXT:    br i1 [[TMP8]], label %[[BB9:.*]], label %[[BB11:.*]]
; IR:       [[BB9]]:
; IR-NEXT:    [[TMP10:%.*]] = atomicrmw min ptr addrspace(3) [[PTR_DIVERGENT]], i32 [[TMP4]] seq_cst, align 4
; IR-NEXT:    br label %[[BB11]]
; IR:       [[BB11]]:
; IR-NEXT:    [[TMP12:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[TMP10]], %[[BB9]] ]
; IR-NEXT:    [[TMP13:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP12]], i32 [[TMP7]])
; IR-NEXT:    [[TMP14:%.*]] = icmp slt i32 [[TMP13]], [[TMP2]]
; IR-NEXT:    [[TMP15:%.*]] = select i1 [[TMP14]], i32 [[TMP13]], i32 [[TMP2]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP15]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %base_ptr_addr = getelementptr i32, ptr addrspace(1) %base_ptrs, i32 %tid
  %base_ptr_i32 = load i32, ptr addrspace(1) %base_ptr_addr
  %base_ptr = inttoptr i32 %base_ptr_i32 to ptr addrspace(3)
  %ptr_offset = getelementptr i8, ptr addrspace(3) %base_ptr, i32 4
  %ptr_divergent = getelementptr i32, ptr addrspace(3) %ptr_offset, i32 %tid
  %value = add i32 %tid, 42
  %old = atomicrmw min ptr addrspace(3) %ptr_divergent, i32 %value seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %old, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @test_atomicrmw_max_divergent_base_divergent_offset(ptr addrspace(1) %base_ptrs, ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @test_atomicrmw_max_divergent_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[BASE_PTRS:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:  [[ENTRY:.*]]:
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[BASE_PTR_ADDR:%.*]] = getelementptr i32, ptr addrspace(1) [[BASE_PTRS]], i32 [[TID]]
; IR-NEXT:    [[BASE_PTR_I32:%.*]] = load i32, ptr addrspace(1) [[BASE_PTR_ADDR]], align 4
; IR-NEXT:    [[BASE_PTR:%.*]] = inttoptr i32 [[BASE_PTR_I32]] to ptr addrspace(3)
; IR-NEXT:    [[PTR_OFFSET:%.*]] = getelementptr i8, ptr addrspace(3) [[BASE_PTR]], i32 4
; IR-NEXT:    [[PTR_DIVERGENT:%.*]] = getelementptr i32, ptr addrspace(3) [[PTR_OFFSET]], i32 [[TID]]
; IR-NEXT:    [[VALUE:%.*]] = add i32 [[TID]], 42
; IR-NEXT:    [[TMP0:%.*]] = ptrtoint ptr addrspace(3) [[PTR_DIVERGENT]] to i32
; IR-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP0]], i32 [[TMP0]])
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.max.i32(i32 [[VALUE]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = icmp sgt i32 [[VALUE]], [[TMP2]]
; IR-NEXT:    [[TMP4:%.*]] = select i1 [[TMP3]], i32 [[VALUE]], i32 [[TMP2]]
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP1]], i1 true)
; IR-NEXT:    [[TMP7:%.*]] = sub i32 31, [[TMP6]]
; IR-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[TMP5]], [[TMP7]]
; IR-NEXT:    br i1 [[TMP8]], label %[[BB9:.*]], label %[[BB11:.*]]
; IR:       [[BB9]]:
; IR-NEXT:    [[TMP10:%.*]] = atomicrmw max ptr addrspace(3) [[PTR_DIVERGENT]], i32 [[TMP4]] seq_cst, align 4
; IR-NEXT:    br label %[[BB11]]
; IR:       [[BB11]]:
; IR-NEXT:    [[TMP12:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[TMP10]], %[[BB9]] ]
; IR-NEXT:    [[TMP13:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP12]], i32 [[TMP7]])
; IR-NEXT:    [[TMP14:%.*]] = icmp sgt i32 [[TMP13]], [[TMP2]]
; IR-NEXT:    [[TMP15:%.*]] = select i1 [[TMP14]], i32 [[TMP13]], i32 [[TMP2]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP15]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %base_ptr_addr = getelementptr i32, ptr addrspace(1) %base_ptrs, i32 %tid
  %base_ptr_i32 = load i32, ptr addrspace(1) %base_ptr_addr
  %base_ptr = inttoptr i32 %base_ptr_i32 to ptr addrspace(3)
  %ptr_offset = getelementptr i8, ptr addrspace(3) %base_ptr, i32 4
  %ptr_divergent = getelementptr i32, ptr addrspace(3) %ptr_offset, i32 %tid
  %value = add i32 %tid, 42
  %old = atomicrmw max ptr addrspace(3) %ptr_divergent, i32 %value seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %old, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @test_atomicrmw_umin_divergent_base_divergent_offset(ptr addrspace(1) %base_ptrs, ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @test_atomicrmw_umin_divergent_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[BASE_PTRS:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:  [[ENTRY:.*]]:
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[BASE_PTR_ADDR:%.*]] = getelementptr i32, ptr addrspace(1) [[BASE_PTRS]], i32 [[TID]]
; IR-NEXT:    [[BASE_PTR_I32:%.*]] = load i32, ptr addrspace(1) [[BASE_PTR_ADDR]], align 4
; IR-NEXT:    [[BASE_PTR:%.*]] = inttoptr i32 [[BASE_PTR_I32]] to ptr addrspace(3)
; IR-NEXT:    [[PTR_OFFSET:%.*]] = getelementptr i8, ptr addrspace(3) [[BASE_PTR]], i32 4
; IR-NEXT:    [[PTR_DIVERGENT:%.*]] = getelementptr i32, ptr addrspace(3) [[PTR_OFFSET]], i32 [[TID]]
; IR-NEXT:    [[VALUE:%.*]] = add i32 [[TID]], 42
; IR-NEXT:    [[TMP0:%.*]] = ptrtoint ptr addrspace(3) [[PTR_DIVERGENT]] to i32
; IR-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP0]], i32 [[TMP0]])
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.min.u32(i32 [[VALUE]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = icmp ult i32 [[VALUE]], [[TMP2]]
; IR-NEXT:    [[TMP4:%.*]] = select i1 [[TMP3]], i32 [[VALUE]], i32 [[TMP2]]
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP1]], i1 true)
; IR-NEXT:    [[TMP7:%.*]] = sub i32 31, [[TMP6]]
; IR-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[TMP5]], [[TMP7]]
; IR-NEXT:    br i1 [[TMP8]], label %[[BB9:.*]], label %[[BB11:.*]]
; IR:       [[BB9]]:
; IR-NEXT:    [[TMP10:%.*]] = atomicrmw umin ptr addrspace(3) [[PTR_DIVERGENT]], i32 [[TMP4]] seq_cst, align 4
; IR-NEXT:    br label %[[BB11]]
; IR:       [[BB11]]:
; IR-NEXT:    [[TMP12:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[TMP10]], %[[BB9]] ]
; IR-NEXT:    [[TMP13:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP12]], i32 [[TMP7]])
; IR-NEXT:    [[TMP14:%.*]] = icmp ult i32 [[TMP13]], [[TMP2]]
; IR-NEXT:    [[TMP15:%.*]] = select i1 [[TMP14]], i32 [[TMP13]], i32 [[TMP2]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP15]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %base_ptr_addr = getelementptr i32, ptr addrspace(1) %base_ptrs, i32 %tid
  %base_ptr_i32 = load i32, ptr addrspace(1) %base_ptr_addr
  %base_ptr = inttoptr i32 %base_ptr_i32 to ptr addrspace(3)
  %ptr_offset = getelementptr i8, ptr addrspace(3) %base_ptr, i32 4
  %ptr_divergent = getelementptr i32, ptr addrspace(3) %ptr_offset, i32 %tid
  %value = add i32 %tid, 42
  %old = atomicrmw umin ptr addrspace(3) %ptr_divergent, i32 %value seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %old, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @test_atomicrmw_umax_divergent_base_divergent_offset(ptr addrspace(1) %base_ptrs, ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @test_atomicrmw_umax_divergent_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[BASE_PTRS:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:  [[ENTRY:.*]]:
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[BASE_PTR_ADDR:%.*]] = getelementptr i32, ptr addrspace(1) [[BASE_PTRS]], i32 [[TID]]
; IR-NEXT:    [[BASE_PTR_I32:%.*]] = load i32, ptr addrspace(1) [[BASE_PTR_ADDR]], align 4
; IR-NEXT:    [[BASE_PTR:%.*]] = inttoptr i32 [[BASE_PTR_I32]] to ptr addrspace(3)
; IR-NEXT:    [[PTR_OFFSET:%.*]] = getelementptr i8, ptr addrspace(3) [[BASE_PTR]], i32 4
; IR-NEXT:    [[PTR_DIVERGENT:%.*]] = getelementptr i32, ptr addrspace(3) [[PTR_OFFSET]], i32 [[TID]]
; IR-NEXT:    [[VALUE:%.*]] = add i32 [[TID]], 42
; IR-NEXT:    [[TMP0:%.*]] = ptrtoint ptr addrspace(3) [[PTR_DIVERGENT]] to i32
; IR-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP0]], i32 [[TMP0]])
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.max.u32(i32 [[VALUE]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = icmp ugt i32 [[VALUE]], [[TMP2]]
; IR-NEXT:    [[TMP4:%.*]] = select i1 [[TMP3]], i32 [[VALUE]], i32 [[TMP2]]
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP1]], i1 true)
; IR-NEXT:    [[TMP7:%.*]] = sub i32 31, [[TMP6]]
; IR-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[TMP5]], [[TMP7]]
; IR-NEXT:    br i1 [[TMP8]], label %[[BB9:.*]], label %[[BB11:.*]]
; IR:       [[BB9]]:
; IR-NEXT:    [[TMP10:%.*]] = atomicrmw umax ptr addrspace(3) [[PTR_DIVERGENT]], i32 [[TMP4]] seq_cst, align 4
; IR-NEXT:    br label %[[BB11]]
; IR:       [[BB11]]:
; IR-NEXT:    [[TMP12:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[TMP10]], %[[BB9]] ]
; IR-NEXT:    [[TMP13:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP12]], i32 [[TMP7]])
; IR-NEXT:    [[TMP14:%.*]] = icmp ugt i32 [[TMP13]], [[TMP2]]
; IR-NEXT:    [[TMP15:%.*]] = select i1 [[TMP14]], i32 [[TMP13]], i32 [[TMP2]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP15]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %base_ptr_addr = getelementptr i32, ptr addrspace(1) %base_ptrs, i32 %tid
  %base_ptr_i32 = load i32, ptr addrspace(1) %base_ptr_addr
  %base_ptr = inttoptr i32 %base_ptr_i32 to ptr addrspace(3)
  %ptr_offset = getelementptr i8, ptr addrspace(3) %base_ptr, i32 4
  %ptr_divergent = getelementptr i32, ptr addrspace(3) %ptr_offset, i32 %tid
  %value = add i32 %tid, 42
  %old = atomicrmw umax ptr addrspace(3) %ptr_divergent, i32 %value seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %old, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @atomicrmw_add_uniform_base_divergent_offset(ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @atomicrmw_add_uniform_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[PTR:%.*]] = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 [[TID]]
; IR-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(3) [[PTR]] to i32
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP1]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.sum.i32(i32 1, i32 [[TMP2]], i1 false)
; IR-NEXT:    [[TMP4:%.*]] = add i32 1, [[TMP3]]
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP2]], i1 true)
; IR-NEXT:    [[TMP7:%.*]] = sub i32 31, [[TMP6]]
; IR-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[TMP5]], [[TMP7]]
; IR-NEXT:    br i1 [[TMP8]], label %[[BB9:.*]], label %[[BB11:.*]]
; IR:       [[BB9]]:
; IR-NEXT:    [[TMP10:%.*]] = atomicrmw add ptr addrspace(3) [[PTR]], i32 [[TMP4]] seq_cst, align 4
; IR-NEXT:    br label %[[BB11]]
; IR:       [[BB11]]:
; IR-NEXT:    [[TMP12:%.*]] = phi i32 [ poison, [[TMP0:%.*]] ], [ [[TMP10]], %[[BB9]] ]
; IR-NEXT:    [[TMP13:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP12]], i32 [[TMP7]])
; IR-NEXT:    [[TMP14:%.*]] = add i32 [[TMP13]], [[TMP3]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP14]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %ptr = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 %tid
  %val = atomicrmw add ptr addrspace(3) %ptr, i32 1 seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %val, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @atomicrmw_sub_uniform_base_divergent_offset(ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @atomicrmw_sub_uniform_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[PTR:%.*]] = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 [[TID]]
; IR-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(3) [[PTR]] to i32
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP1]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.sum.i32(i32 1, i32 [[TMP2]], i1 false)
; IR-NEXT:    [[TMP4:%.*]] = add i32 1, [[TMP3]]
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP2]], i1 true)
; IR-NEXT:    [[TMP7:%.*]] = sub i32 31, [[TMP6]]
; IR-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[TMP5]], [[TMP7]]
; IR-NEXT:    br i1 [[TMP8]], label %[[BB9:.*]], label %[[BB11:.*]]
; IR:       [[BB9]]:
; IR-NEXT:    [[TMP10:%.*]] = atomicrmw sub ptr addrspace(3) [[PTR]], i32 [[TMP4]] seq_cst, align 4
; IR-NEXT:    br label %[[BB11]]
; IR:       [[BB11]]:
; IR-NEXT:    [[TMP12:%.*]] = phi i32 [ poison, [[TMP0:%.*]] ], [ [[TMP10]], %[[BB9]] ]
; IR-NEXT:    [[TMP13:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP12]], i32 [[TMP7]])
; IR-NEXT:    [[TMP14:%.*]] = sub i32 [[TMP13]], [[TMP3]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP14]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %ptr = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 %tid
  %val = atomicrmw sub ptr addrspace(3) %ptr, i32 1 seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %val, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @atomicrmw_and_uniform_base_divergent_offset(ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @atomicrmw_and_uniform_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[PTR:%.*]] = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 [[TID]]
; IR-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(3) [[PTR]] to i32
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP1]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.and.b32(i32 -1, i32 [[TMP2]])
; IR-NEXT:    [[TMP4:%.*]] = and i32 -1, [[TMP3]]
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP2]], i1 true)
; IR-NEXT:    [[TMP7:%.*]] = sub i32 31, [[TMP6]]
; IR-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[TMP5]], [[TMP7]]
; IR-NEXT:    br i1 [[TMP8]], label %[[BB9:.*]], label %[[BB11:.*]]
; IR:       [[BB9]]:
; IR-NEXT:    [[TMP10:%.*]] = atomicrmw and ptr addrspace(3) [[PTR]], i32 [[TMP4]] seq_cst, align 4
; IR-NEXT:    br label %[[BB11]]
; IR:       [[BB11]]:
; IR-NEXT:    [[TMP12:%.*]] = phi i32 [ poison, [[TMP0:%.*]] ], [ [[TMP10]], %[[BB9]] ]
; IR-NEXT:    [[TMP13:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP12]], i32 [[TMP7]])
; IR-NEXT:    [[TMP14:%.*]] = and i32 [[TMP13]], [[TMP3]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP14]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %ptr = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 %tid
  %val = atomicrmw and ptr addrspace(3) %ptr, i32 -1 seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %val, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @atomicrmw_or_uniform_base_divergent_offset(ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @atomicrmw_or_uniform_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[PTR:%.*]] = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 [[TID]]
; IR-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(3) [[PTR]] to i32
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP1]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.or.b32(i32 1, i32 [[TMP2]])
; IR-NEXT:    [[TMP4:%.*]] = or i32 1, [[TMP3]]
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP2]], i1 true)
; IR-NEXT:    [[TMP7:%.*]] = sub i32 31, [[TMP6]]
; IR-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[TMP5]], [[TMP7]]
; IR-NEXT:    br i1 [[TMP8]], label %[[BB9:.*]], label %[[BB11:.*]]
; IR:       [[BB9]]:
; IR-NEXT:    [[TMP10:%.*]] = atomicrmw or ptr addrspace(3) [[PTR]], i32 [[TMP4]] seq_cst, align 4
; IR-NEXT:    br label %[[BB11]]
; IR:       [[BB11]]:
; IR-NEXT:    [[TMP12:%.*]] = phi i32 [ poison, [[TMP0:%.*]] ], [ [[TMP10]], %[[BB9]] ]
; IR-NEXT:    [[TMP13:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP12]], i32 [[TMP7]])
; IR-NEXT:    [[TMP14:%.*]] = or i32 [[TMP13]], [[TMP3]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP14]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %ptr = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 %tid
  %val = atomicrmw or ptr addrspace(3) %ptr, i32 1 seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %val, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @atomicrmw_xor_uniform_base_divergent_offset(ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @atomicrmw_xor_uniform_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[PTR:%.*]] = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 [[TID]]
; IR-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(3) [[PTR]] to i32
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP1]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.xor.b32(i32 1, i32 [[TMP2]])
; IR-NEXT:    [[TMP4:%.*]] = xor i32 1, [[TMP3]]
; IR-NEXT:    [[TMP5:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP2]], i1 true)
; IR-NEXT:    [[TMP7:%.*]] = sub i32 31, [[TMP6]]
; IR-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[TMP5]], [[TMP7]]
; IR-NEXT:    br i1 [[TMP8]], label %[[BB9:.*]], label %[[BB11:.*]]
; IR:       [[BB9]]:
; IR-NEXT:    [[TMP10:%.*]] = atomicrmw xor ptr addrspace(3) [[PTR]], i32 [[TMP4]] seq_cst, align 4
; IR-NEXT:    br label %[[BB11]]
; IR:       [[BB11]]:
; IR-NEXT:    [[TMP12:%.*]] = phi i32 [ poison, [[TMP0:%.*]] ], [ [[TMP10]], %[[BB9]] ]
; IR-NEXT:    [[TMP13:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP12]], i32 [[TMP7]])
; IR-NEXT:    [[TMP14:%.*]] = xor i32 [[TMP13]], [[TMP3]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP14]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %ptr = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 %tid
  %val = atomicrmw xor ptr addrspace(3) %ptr, i32 1 seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %val, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @atomicrmw_min_uniform_base_divergent_offset(ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @atomicrmw_min_uniform_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[PTR:%.*]] = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 [[TID]]
; IR-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(3) [[PTR]] to i32
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP1]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.min.i32(i32 100, i32 [[TMP2]])
; IR-NEXT:    [[TMP4:%.*]] = icmp slt i32 100, [[TMP3]]
; IR-NEXT:    [[TMP5:%.*]] = select i1 [[TMP4]], i32 100, i32 [[TMP3]]
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP7:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP2]], i1 true)
; IR-NEXT:    [[TMP8:%.*]] = sub i32 31, [[TMP7]]
; IR-NEXT:    [[TMP9:%.*]] = icmp eq i32 [[TMP6]], [[TMP8]]
; IR-NEXT:    br i1 [[TMP9]], label %[[BB10:.*]], label %[[BB12:.*]]
; IR:       [[BB10]]:
; IR-NEXT:    [[TMP11:%.*]] = atomicrmw min ptr addrspace(3) [[PTR]], i32 [[TMP5]] seq_cst, align 4
; IR-NEXT:    br label %[[BB12]]
; IR:       [[BB12]]:
; IR-NEXT:    [[TMP13:%.*]] = phi i32 [ poison, [[TMP0:%.*]] ], [ [[TMP11]], %[[BB10]] ]
; IR-NEXT:    [[TMP14:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP13]], i32 [[TMP8]])
; IR-NEXT:    [[TMP15:%.*]] = icmp slt i32 [[TMP14]], [[TMP3]]
; IR-NEXT:    [[TMP16:%.*]] = select i1 [[TMP15]], i32 [[TMP14]], i32 [[TMP3]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP16]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %ptr = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 %tid
  %val = atomicrmw min ptr addrspace(3) %ptr, i32 100 seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %val, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @atomicrmw_max_uniform_base_divergent_offset(ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @atomicrmw_max_uniform_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[PTR:%.*]] = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 [[TID]]
; IR-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(3) [[PTR]] to i32
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP1]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.max.i32(i32 100, i32 [[TMP2]])
; IR-NEXT:    [[TMP4:%.*]] = icmp sgt i32 100, [[TMP3]]
; IR-NEXT:    [[TMP5:%.*]] = select i1 [[TMP4]], i32 100, i32 [[TMP3]]
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP7:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP2]], i1 true)
; IR-NEXT:    [[TMP8:%.*]] = sub i32 31, [[TMP7]]
; IR-NEXT:    [[TMP9:%.*]] = icmp eq i32 [[TMP6]], [[TMP8]]
; IR-NEXT:    br i1 [[TMP9]], label %[[BB10:.*]], label %[[BB12:.*]]
; IR:       [[BB10]]:
; IR-NEXT:    [[TMP11:%.*]] = atomicrmw max ptr addrspace(3) [[PTR]], i32 [[TMP5]] seq_cst, align 4
; IR-NEXT:    br label %[[BB12]]
; IR:       [[BB12]]:
; IR-NEXT:    [[TMP13:%.*]] = phi i32 [ poison, [[TMP0:%.*]] ], [ [[TMP11]], %[[BB10]] ]
; IR-NEXT:    [[TMP14:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP13]], i32 [[TMP8]])
; IR-NEXT:    [[TMP15:%.*]] = icmp sgt i32 [[TMP14]], [[TMP3]]
; IR-NEXT:    [[TMP16:%.*]] = select i1 [[TMP15]], i32 [[TMP14]], i32 [[TMP3]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP16]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %ptr = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 %tid
  %val = atomicrmw max ptr addrspace(3) %ptr, i32 100 seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %val, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @atomicrmw_umin_uniform_base_divergent_offset(ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @atomicrmw_umin_uniform_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[PTR:%.*]] = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 [[TID]]
; IR-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(3) [[PTR]] to i32
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP1]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.min.u32(i32 100, i32 [[TMP2]])
; IR-NEXT:    [[TMP4:%.*]] = icmp ult i32 100, [[TMP3]]
; IR-NEXT:    [[TMP5:%.*]] = select i1 [[TMP4]], i32 100, i32 [[TMP3]]
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP7:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP2]], i1 true)
; IR-NEXT:    [[TMP8:%.*]] = sub i32 31, [[TMP7]]
; IR-NEXT:    [[TMP9:%.*]] = icmp eq i32 [[TMP6]], [[TMP8]]
; IR-NEXT:    br i1 [[TMP9]], label %[[BB10:.*]], label %[[BB12:.*]]
; IR:       [[BB10]]:
; IR-NEXT:    [[TMP11:%.*]] = atomicrmw umin ptr addrspace(3) [[PTR]], i32 [[TMP5]] seq_cst, align 4
; IR-NEXT:    br label %[[BB12]]
; IR:       [[BB12]]:
; IR-NEXT:    [[TMP13:%.*]] = phi i32 [ poison, [[TMP0:%.*]] ], [ [[TMP11]], %[[BB10]] ]
; IR-NEXT:    [[TMP14:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP13]], i32 [[TMP8]])
; IR-NEXT:    [[TMP15:%.*]] = icmp ult i32 [[TMP14]], [[TMP3]]
; IR-NEXT:    [[TMP16:%.*]] = select i1 [[TMP15]], i32 [[TMP14]], i32 [[TMP3]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP16]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %ptr = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 %tid
  %val = atomicrmw umin ptr addrspace(3) %ptr, i32 100 seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %val, ptr addrspace(1) %output_ptr, align 4
  ret void
}

define amdgpu_kernel void @atomicrmw_umax_uniform_base_divergent_offset(ptr addrspace(1) %output) {
; IR-LABEL: define amdgpu_kernel void @atomicrmw_umax_uniform_base_divergent_offset(
; IR-SAME: ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; IR-NEXT:    [[TID:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; IR-NEXT:    [[PTR:%.*]] = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 [[TID]]
; IR-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(3) [[PTR]] to i32
; IR-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TMP1]], i32 [[TMP1]])
; IR-NEXT:    [[TMP3:%.*]] = call i32 @llvm.amdgcn.exclusive.scan.max.u32(i32 100, i32 [[TMP2]])
; IR-NEXT:    [[TMP4:%.*]] = icmp ugt i32 100, [[TMP3]]
; IR-NEXT:    [[TMP5:%.*]] = select i1 [[TMP4]], i32 100, i32 [[TMP3]]
; IR-NEXT:    [[TMP6:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; IR-NEXT:    [[TMP7:%.*]] = call i32 @llvm.ctlz.i32(i32 [[TMP2]], i1 true)
; IR-NEXT:    [[TMP8:%.*]] = sub i32 31, [[TMP7]]
; IR-NEXT:    [[TMP9:%.*]] = icmp eq i32 [[TMP6]], [[TMP8]]
; IR-NEXT:    br i1 [[TMP9]], label %[[BB10:.*]], label %[[BB12:.*]]
; IR:       [[BB10]]:
; IR-NEXT:    [[TMP11:%.*]] = atomicrmw umax ptr addrspace(3) [[PTR]], i32 [[TMP5]] seq_cst, align 4
; IR-NEXT:    br label %[[BB12]]
; IR:       [[BB12]]:
; IR-NEXT:    [[TMP13:%.*]] = phi i32 [ poison, [[TMP0:%.*]] ], [ [[TMP11]], %[[BB10]] ]
; IR-NEXT:    [[TMP14:%.*]] = call i32 @llvm.amdgcn.bpermute.b32(i32 [[TMP13]], i32 [[TMP8]])
; IR-NEXT:    [[TMP15:%.*]] = icmp ugt i32 [[TMP14]], [[TMP3]]
; IR-NEXT:    [[TMP16:%.*]] = select i1 [[TMP15]], i32 [[TMP14]], i32 [[TMP3]]
; IR-NEXT:    [[OUTPUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUTPUT]], i32 [[TID]]
; IR-NEXT:    store i32 [[TMP16]], ptr addrspace(1) [[OUTPUT_PTR]], align 4
; IR-NEXT:    ret void
;
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %ptr = getelementptr inbounds [64 x i32], ptr addrspace(3) @histogram_bins, i64 0, i32 %tid
  %val = atomicrmw umax ptr addrspace(3) %ptr, i32 100 seq_cst, align 4
  %output_ptr = getelementptr i32, ptr addrspace(1) %output, i32 %tid
  store i32 %val, ptr addrspace(1) %output_ptr, align 4
  ret void
}
