; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a %s -o - | FileCheck %s

define void @scalar(double %num, ptr addrspace(1) %p) {
; CHECK-LABEL: scalar:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_cvt_f32_f64_e32 v0, v[0:1]
; CHECK-NEXT:    global_store_short_d16_hi v[2:3], v0, off
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  %conv = fptrunc double %num to bfloat
  store bfloat %conv, ptr addrspace(1) %p, align 8
  ret void
}

define void @v2(<2 x double> %num, ptr addrspace(1) %p) {
; CHECK-LABEL: v2:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_cvt_f32_f64_e32 v0, v[0:1]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v1, v[2:3]
; CHECK-NEXT:    s_mov_b32 s4, 0x7060302
; CHECK-NEXT:    v_perm_b32 v0, v1, v0, s4
; CHECK-NEXT:    global_store_dword v[4:5], v0, off
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  %conv = fptrunc <2 x double> %num to <2 x bfloat>
  store <2 x bfloat> %conv, ptr addrspace(1) %p, align 8
  ret void
}

define void @v3(<3 x double> %num, ptr addrspace(1) %p) {
; CHECK-LABEL: v3:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_cvt_f32_f64_e32 v0, v[0:1]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v1, v[2:3]
; CHECK-NEXT:    s_mov_b32 s4, 0x7060302
; CHECK-NEXT:    v_perm_b32 v0, v1, v0, s4
; CHECK-NEXT:    v_cvt_f32_f64_e32 v1, v[4:5]
; CHECK-NEXT:    global_store_short_d16_hi v[6:7], v1, off offset:4
; CHECK-NEXT:    global_store_dword v[6:7], v0, off
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  %conv = fptrunc <3 x double> %num to <3 x bfloat>
  store <3 x bfloat> %conv, ptr addrspace(1) %p, align 8
  ret void
}

define void @v4(<4 x double> %num, ptr addrspace(1) %p) {
; CHECK-LABEL: v4:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_cvt_f32_f64_e32 v4, v[4:5]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v5, v[6:7]
; CHECK-NEXT:    s_mov_b32 s4, 0x7060302
; CHECK-NEXT:    v_cvt_f32_f64_e32 v0, v[0:1]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v1, v[2:3]
; CHECK-NEXT:    v_perm_b32 v5, v5, v4, s4
; CHECK-NEXT:    v_perm_b32 v4, v1, v0, s4
; CHECK-NEXT:    global_store_dwordx2 v[8:9], v[4:5], off
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  %conv = fptrunc <4 x double> %num to <4 x bfloat>
  store <4 x bfloat> %conv, ptr addrspace(1) %p, align 8
  ret void
}

define void @v8(<8 x double> %num, ptr addrspace(1) %p) {
; CHECK-LABEL: v8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_cvt_f32_f64_e32 v12, v[12:13]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v13, v[14:15]
; CHECK-NEXT:    s_mov_b32 s4, 0x7060302
; CHECK-NEXT:    v_cvt_f32_f64_e32 v8, v[8:9]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v9, v[10:11]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v4, v[4:5]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v5, v[6:7]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v0, v[0:1]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v1, v[2:3]
; CHECK-NEXT:    v_perm_b32 v13, v13, v12, s4
; CHECK-NEXT:    v_perm_b32 v12, v9, v8, s4
; CHECK-NEXT:    v_perm_b32 v11, v5, v4, s4
; CHECK-NEXT:    v_perm_b32 v10, v1, v0, s4
; CHECK-NEXT:    global_store_dwordx4 v[16:17], v[10:13], off
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  %conv = fptrunc <8 x double> %num to <8 x bfloat>
  store <8 x bfloat> %conv, ptr addrspace(1) %p, align 8
  ret void
}

define void @v16(<16 x double> %num, ptr addrspace(1) %p) {
; CHECK-LABEL: v16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:8
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:4
; CHECK-NEXT:    s_mov_b32 s4, 0x7060302
; CHECK-NEXT:    v_cvt_f32_f64_e32 v8, v[8:9]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v9, v[10:11]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v12, v[12:13]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v13, v[14:15]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v4, v[4:5]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v5, v[6:7]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v0, v[0:1]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v6, v[2:3]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v7, v[28:29]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v10, v[24:25]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v11, v[26:27]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v14, v[20:21]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v15, v[22:23]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v16, v[16:17]
; CHECK-NEXT:    v_cvt_f32_f64_e32 v17, v[18:19]
; CHECK-NEXT:    v_perm_b32 v2, v9, v8, s4
; CHECK-NEXT:    v_perm_b32 v1, v5, v4, s4
; CHECK-NEXT:    v_perm_b32 v0, v6, v0, s4
; CHECK-NEXT:    v_perm_b32 v6, v11, v10, s4
; CHECK-NEXT:    v_perm_b32 v5, v15, v14, s4
; CHECK-NEXT:    v_perm_b32 v4, v17, v16, s4
; CHECK-NEXT:    v_perm_b32 v3, v13, v12, s4
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    v_cvt_f32_f64_e32 v8, v[30:31]
; CHECK-NEXT:    v_perm_b32 v7, v8, v7, s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_dwordx4 v[32:33], v[4:7], off offset:16
; CHECK-NEXT:    global_store_dwordx4 v[32:33], v[0:3], off
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  %conv = fptrunc <16 x double> %num to <16 x bfloat>
  store <16 x bfloat> %conv, ptr addrspace(1) %p, align 8
  ret void
}
