; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -passes=instcombine -S %s | FileCheck %s

@sem = internal addrspace(3) global target("amdgcn.semaphore", 1) poison
@sem2 = internal addrspace(3) global target("amdgcn.semaphore", 1) poison

define amdgpu_kernel void @vnbr_simple(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(10) %prefl) {
; CHECK-LABEL: define amdgpu_kernel void @vnbr_simple(
; CHECK-SAME: i32 [[I1:%.*]], ptr addrspace(10) [[PDST:%.*]], ptr addrspace(10) [[PREFL:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[MAIN_BODY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) @sem2, ptr addrspace(10) [[PREFL]], ptr addrspace(3) @sem, i32 0)
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.prev(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) @sem, ptr addrspace(10) [[PREFL]], ptr addrspace(3) @sem2, i32 0)
; CHECK-NEXT:    ret void
;
main_body:
  call void @llvm.amdgcn.spatial.cluster.send.next(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)),
  ptr addrspace(10) %prefl, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0);
  call void @llvm.amdgcn.spatial.cluster.send.prev(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)),
  ptr addrspace(10) %prefl, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0);
  call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sem2, ptr addrspace(3) @sem)
  call void @llvm.amdgcn.spatial.cluster.signal.prev(ptr addrspace(3) @sem, ptr addrspace(3) @sem2)
  ret void;
}

define amdgpu_kernel void @vnbr_show_combine_order(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(10) %prefl) {
; CHECK-LABEL: define amdgpu_kernel void @vnbr_show_combine_order(
; CHECK-SAME: i32 [[I1:%.*]], ptr addrspace(10) [[PDST:%.*]], ptr addrspace(10) [[PREFL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[MAIN_BODY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.signal.prev(ptr addrspace(3) @sem2, ptr addrspace(3) @sem)
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) @sem2, ptr addrspace(10) [[PREFL]], ptr addrspace(3) @sem, i32 0)
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sem, ptr addrspace(3) @sem2)
; CHECK-NEXT:    ret void
;
main_body:
  call void @llvm.amdgcn.spatial.cluster.send.next(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)),
  ptr addrspace(10) %prefl, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0);
  call void @llvm.amdgcn.spatial.cluster.signal.prev(ptr addrspace(3) @sem2, ptr addrspace(3) @sem)
  call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sem2, ptr addrspace(3) @sem)
  call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sem, ptr addrspace(3) @sem2)
  ret void;
}

define amdgpu_kernel void @vnbr_send_has_signal(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(10) %prefl) {
; CHECK-LABEL: define amdgpu_kernel void @vnbr_send_has_signal(
; CHECK-SAME: i32 [[I1:%.*]], ptr addrspace(10) [[PDST:%.*]], ptr addrspace(10) [[PREFL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[MAIN_BODY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) @sem2, ptr addrspace(10) [[PREFL]], ptr addrspace(3) @sem, i32 0)
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.prev(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) @sem, ptr addrspace(10) [[PREFL]], ptr addrspace(3) @sem2, i32 0)
; CHECK-NEXT:    ret void
;
main_body:
  call void @llvm.amdgcn.spatial.cluster.send.prev(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)),
  ptr addrspace(10) %prefl, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0);
  call void @llvm.amdgcn.spatial.cluster.send.next(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) @sem2, ptr addrspace(10) %prefl, ptr addrspace(3) @sem, i32 0);
  call void @llvm.amdgcn.spatial.cluster.signal.prev(ptr addrspace(3) @sem, ptr addrspace(3) @sem2)
  ret void;
}

define amdgpu_kernel void @vnbr_send_has_overlapping_signal(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(10) %prefl) {
; CHECK-LABEL: define amdgpu_kernel void @vnbr_send_has_overlapping_signal(
; CHECK-SAME: i32 [[I1:%.*]], ptr addrspace(10) [[PDST:%.*]], ptr addrspace(10) [[PREFL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[MAIN_BODY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) @sem2, ptr addrspace(10) [[PREFL]], ptr addrspace(3) @sem2, i32 0)
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.prev(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) @sem, ptr addrspace(10) [[PREFL]], ptr addrspace(3) @sem2, i32 0)
; CHECK-NEXT:    ret void
;
main_body:
  call void @llvm.amdgcn.spatial.cluster.send.prev(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)),
  ptr addrspace(10) %prefl, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0);
  call void @llvm.amdgcn.spatial.cluster.send.next(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) @sem2, ptr addrspace(10) %prefl, ptr addrspace(3) @sem2, i32 0);
  call void @llvm.amdgcn.spatial.cluster.signal.prev(ptr addrspace(3) @sem, ptr addrspace(3) @sem2)
  ret void;
}

define amdgpu_kernel void @vnbr_overlapping_signal(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(10) %prefl) {
; CHECK-LABEL: define amdgpu_kernel void @vnbr_overlapping_signal(
; CHECK-SAME: i32 [[I1:%.*]], ptr addrspace(10) [[PDST:%.*]], ptr addrspace(10) [[PREFL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[MAIN_BODY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) @sem, ptr addrspace(10) [[PREFL]], ptr addrspace(3) @sem, i32 0)
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.prev(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) @sem, ptr addrspace(10) [[PREFL]], ptr addrspace(3) @sem, i32 0)
; CHECK-NEXT:    ret void
;
main_body:
  call void @llvm.amdgcn.spatial.cluster.send.next(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)),
  ptr addrspace(10) %prefl, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0);
  call void @llvm.amdgcn.spatial.cluster.send.prev(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)),
  ptr addrspace(10) %prefl, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0);
  call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sem, ptr addrspace(3) @sem)
  call void @llvm.amdgcn.spatial.cluster.signal.prev(ptr addrspace(3) @sem, ptr addrspace(3) @sem)
  ret void;
}

define amdgpu_kernel void @vnbr_already_signalling(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(10) %prefl) {
; CHECK-LABEL: define amdgpu_kernel void @vnbr_already_signalling(
; CHECK-SAME: i32 [[I1:%.*]], ptr addrspace(10) [[PDST:%.*]], ptr addrspace(10) [[PREFL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[MAIN_BODY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) @sem2, ptr addrspace(10) [[PREFL]], ptr addrspace(3) @sem2, i32 0)
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sem2, ptr addrspace(3) @sem)
; CHECK-NEXT:    ret void
;
main_body:
  call void @llvm.amdgcn.spatial.cluster.send.next(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) @sem2, ptr addrspace(10) %prefl, ptr addrspace(3) @sem2, i32 0);
  call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sem2, ptr addrspace(3) @sem)
  ret void;
}

define amdgpu_kernel void @vnbr_same_direction_already_signalling(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(10) %prefl) {
; CHECK-LABEL: define amdgpu_kernel void @vnbr_same_direction_already_signalling(
; CHECK-SAME: i32 [[I1:%.*]], ptr addrspace(10) [[PDST:%.*]], ptr addrspace(10) [[PREFL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[MAIN_BODY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), ptr addrspace(10) [[PREFL]], ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0)
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) @sem2, ptr addrspace(10) [[PREFL]], ptr addrspace(3) @sem2, i32 0)
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sem, ptr addrspace(3) @sem2)
; CHECK-NEXT:    ret void
;
main_body:
  call void @llvm.amdgcn.spatial.cluster.send.next(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)),
  ptr addrspace(10) %prefl, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0);
  call void @llvm.amdgcn.spatial.cluster.send.next(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) @sem2, ptr addrspace(10) %prefl, ptr addrspace(3) @sem2, i32 0);
  call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sem, ptr addrspace(3) @sem2)
  ret void;
}

define amdgpu_kernel void @vnbr_with_side_effects(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(10) %prefl, ptr addrspace(1) %mem) {
; CHECK-LABEL: define amdgpu_kernel void @vnbr_with_side_effects(
; CHECK-SAME: i32 [[I1:%.*]], ptr addrspace(10) [[PDST:%.*]], ptr addrspace(10) [[PREFL:%.*]], ptr addrspace(1) [[MEM:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[MAIN_BODY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), ptr addrspace(10) [[PREFL]], ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0)
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sem2, ptr addrspace(3) @sem)
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.prev(i32 [[I1]], ptr addrspace(10) [[PDST]], ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), ptr addrspace(10) [[PREFL]], ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0)
; CHECK-NEXT:    [[VOLATILE_LOAD:%.*]] = load volatile i32, ptr addrspace(1) [[MEM]], align 4
; CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.signal.prev(ptr addrspace(3) @sem, ptr addrspace(3) @sem2)
; CHECK-NEXT:    ret void
;
main_body:
  call void @llvm.amdgcn.spatial.cluster.send.next(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)),
  ptr addrspace(10) %prefl, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0);
  call void @llvm.amdgcn.s.barrier()
  call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sem2, ptr addrspace(3) @sem)
  call void @llvm.amdgcn.spatial.cluster.send.prev(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)),
  ptr addrspace(10) %prefl, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0);
  %volatile_load = load volatile i32, ptr addrspace(1) %mem
  call void @llvm.amdgcn.spatial.cluster.signal.prev(ptr addrspace(3) @sem, ptr addrspace(3) @sem2)
  ret void;
}
