; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel=0 -mtriple=amdgcn -mcpu=gfx1370 -verify-machineinstrs -mattr=+wavefrontsize32 < %s | FileCheck -check-prefix=GFX1370-SDAG %s
; RUN: llc -global-isel=1 -global-isel-abort=2 -mtriple=amdgcn -mcpu=gfx1370 -verify-machineinstrs -mattr=+wavefrontsize32 < %s | FileCheck -check-prefix=GFX1370-GISEL %s

define amdgpu_kernel void @global_tiled_load_2x2_b128(ptr addrspace(1) %addr, ptr addrspace(1) %use) {
; GFX1370-SDAG-LABEL: global_tiled_load_2x2_b128:
; GFX1370-SDAG:       ; %bb.0: ; %entry
; GFX1370-SDAG-NEXT:    s_load_b128 s[0:3], s[4:5], 0x24
; GFX1370-SDAG-NEXT:    v_mov_b32_e32 v4, 0
; GFX1370-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1370-SDAG-NEXT:    global_tiled_load_2x2_b128 v[0:3], v4, s[0:1] offset:32 scope:SCOPE_SYS
; GFX1370-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX1370-SDAG-NEXT:    global_inv scope:SCOPE_SYS
; GFX1370-SDAG-NEXT:    global_store_b128 v4, v[0:3], s[2:3]
; GFX1370-SDAG-NEXT:    s_endpgm
;
; GFX1370-GISEL-LABEL: global_tiled_load_2x2_b128:
; GFX1370-GISEL:       ; %bb.0: ; %entry
; GFX1370-GISEL-NEXT:    s_load_b128 s[0:3], s[4:5], 0x24
; GFX1370-GISEL-NEXT:    v_mov_b32_e32 v4, 0
; GFX1370-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1370-GISEL-NEXT:    global_tiled_load_2x2_b128 v[0:3], v4, s[0:1] offset:32 scope:SCOPE_SYS
; GFX1370-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1370-GISEL-NEXT:    global_inv scope:SCOPE_SYS
; GFX1370-GISEL-NEXT:    global_store_b128 v4, v[0:3], s[2:3]
; GFX1370-GISEL-NEXT:    s_endpgm
 entry:
   %gep = getelementptr i64, ptr addrspace(1) %addr, i32 4
   %val = call <4 x i32> @llvm.amdgcn.global.tiled.load.2x2.b128(ptr addrspace(1) %gep)
   store <4 x i32> %val, ptr addrspace(1) %use
   ret void
}
