; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -mattr=+real-true16 %s -o - | FileCheck -check-prefixes=SDAG-REAL16,GFX1250-SDAG-REAL16 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1260 -mattr=+real-true16 %s -o - | FileCheck -check-prefixes=SDAG-REAL16,GFX1250-SDAG-REAL16 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -mattr=-real-true16 %s -o - | FileCheck -check-prefixes=SDAG-FAKE16,GFX1250-SDAG-FAKE16 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1260 -mattr=-real-true16 %s -o - | FileCheck -check-prefixes=SDAG-FAKE16,GFX1250-SDAG-FAKE16 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -mattr=+real-true16 %s -o - | FileCheck -check-prefixes=GISEL-REAL16 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1260 -mattr=+real-true16 %s -o - | FileCheck -check-prefixes=GISEL-REAL16 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -mattr=-real-true16 %s -o - | FileCheck -check-prefixes=GISEL-FAKE16 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1260 -mattr=-real-true16 %s -o - | FileCheck -check-prefixes=GISEL-FAKE16 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -mattr=+real-true16 %s -o - | FileCheck -check-prefixes=SDAG-REAL16,GFX13-SDAG-REAL16 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -mattr=-real-true16 %s -o - | FileCheck -check-prefixes=SDAG-FAKE16,GFX13-SDAG-FAKE16 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -mattr=+real-true16 %s -o - | FileCheck -check-prefixes=GISEL-REAL16 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -mattr=-real-true16 %s -o - | FileCheck -check-prefixes=GISEL-FAKE16 %s

declare i16 @llvm.amdgcn.sat.pk4.i4.i8(i32) #0
declare i16 @llvm.amdgcn.sat.pk4.u4.u8(i32) #0

define amdgpu_kernel void @sat_pk4_i4_i8_f32_v(i32 %src, ptr %out) #1 {
; GFX1250-SDAG-REAL16-LABEL: sat_pk4_i4_i8_f32_v:
; GFX1250-SDAG-REAL16:       ; %bb.0:
; GFX1250-SDAG-REAL16-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1250-SDAG-REAL16-NEXT:    s_clause 0x1
; GFX1250-SDAG-REAL16-NEXT:    s_load_b32 s2, s[4:5], 0x0
; GFX1250-SDAG-REAL16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX1250-SDAG-REAL16-NEXT:    v_mov_b32_e32 v1, 0
; GFX1250-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-REAL16-NEXT:    v_sat_pk4_i4_i8_e32 v0.l, s2
; GFX1250-SDAG-REAL16-NEXT:    flat_store_b16 v1, v0, s[0:1]
; GFX1250-SDAG-REAL16-NEXT:    s_endpgm
;
; GFX1250-SDAG-FAKE16-LABEL: sat_pk4_i4_i8_f32_v:
; GFX1250-SDAG-FAKE16:       ; %bb.0:
; GFX1250-SDAG-FAKE16-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1250-SDAG-FAKE16-NEXT:    s_clause 0x1
; GFX1250-SDAG-FAKE16-NEXT:    s_load_b32 s2, s[4:5], 0x0
; GFX1250-SDAG-FAKE16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX1250-SDAG-FAKE16-NEXT:    v_mov_b32_e32 v0, 0
; GFX1250-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-FAKE16-NEXT:    v_sat_pk4_i4_i8_e32 v1, s2
; GFX1250-SDAG-FAKE16-NEXT:    flat_store_b16 v0, v1, s[0:1]
; GFX1250-SDAG-FAKE16-NEXT:    s_endpgm
;
; GFX13-SDAG-REAL16-LABEL: sat_pk4_i4_i8_f32_v:
; GFX13-SDAG-REAL16:       ; %bb.0:
; GFX13-SDAG-REAL16-NEXT:    s_clause 0x1
; GFX13-SDAG-REAL16-NEXT:    s_load_b32 s2, s[4:5], 0x0
; GFX13-SDAG-REAL16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX13-SDAG-REAL16-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-REAL16-NEXT:    v_sat_pk4_i4_i8_e32 v0.l, s2
; GFX13-SDAG-REAL16-NEXT:    flat_store_b16 v1, v0, s[0:1]
; GFX13-SDAG-REAL16-NEXT:    s_endpgm
;
; GFX13-SDAG-FAKE16-LABEL: sat_pk4_i4_i8_f32_v:
; GFX13-SDAG-FAKE16:       ; %bb.0:
; GFX13-SDAG-FAKE16-NEXT:    s_clause 0x1
; GFX13-SDAG-FAKE16-NEXT:    s_load_b32 s2, s[4:5], 0x0
; GFX13-SDAG-FAKE16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX13-SDAG-FAKE16-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-FAKE16-NEXT:    v_sat_pk4_i4_i8_e32 v1, s2
; GFX13-SDAG-FAKE16-NEXT:    flat_store_b16 v0, v1, s[0:1]
; GFX13-SDAG-FAKE16-NEXT:    s_endpgm
  %cvt = call i16 @llvm.amdgcn.sat.pk4.i4.i8(i32 %src) #0
  store i16 %cvt, ptr %out, align 2
  ret void
}

define amdgpu_kernel void @sat_pk4_i4_i8_f32_s(i32 inreg %src, ptr %out) #1 {
; GFX1250-SDAG-REAL16-LABEL: sat_pk4_i4_i8_f32_s:
; GFX1250-SDAG-REAL16:       ; %bb.0:
; GFX1250-SDAG-REAL16-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1250-SDAG-REAL16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX1250-SDAG-REAL16-NEXT:    v_sat_pk4_i4_i8_e32 v0.l, s8
; GFX1250-SDAG-REAL16-NEXT:    v_mov_b32_e32 v1, 0
; GFX1250-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-REAL16-NEXT:    flat_store_b16 v1, v0, s[0:1]
; GFX1250-SDAG-REAL16-NEXT:    s_endpgm
;
; GFX1250-SDAG-FAKE16-LABEL: sat_pk4_i4_i8_f32_s:
; GFX1250-SDAG-FAKE16:       ; %bb.0:
; GFX1250-SDAG-FAKE16-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1250-SDAG-FAKE16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX1250-SDAG-FAKE16-NEXT:    v_mov_b32_e32 v0, 0
; GFX1250-SDAG-FAKE16-NEXT:    v_sat_pk4_i4_i8_e32 v1, s8
; GFX1250-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-FAKE16-NEXT:    flat_store_b16 v0, v1, s[0:1]
; GFX1250-SDAG-FAKE16-NEXT:    s_endpgm
;
; GFX13-SDAG-REAL16-LABEL: sat_pk4_i4_i8_f32_s:
; GFX13-SDAG-REAL16:       ; %bb.0:
; GFX13-SDAG-REAL16-NEXT:    s_clause 0x1
; GFX13-SDAG-REAL16-NEXT:    s_load_b32 s2, s[4:5], 0x0
; GFX13-SDAG-REAL16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX13-SDAG-REAL16-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-REAL16-NEXT:    v_sat_pk4_i4_i8_e32 v0.l, s2
; GFX13-SDAG-REAL16-NEXT:    flat_store_b16 v1, v0, s[0:1]
; GFX13-SDAG-REAL16-NEXT:    s_endpgm
;
; GFX13-SDAG-FAKE16-LABEL: sat_pk4_i4_i8_f32_s:
; GFX13-SDAG-FAKE16:       ; %bb.0:
; GFX13-SDAG-FAKE16-NEXT:    s_clause 0x1
; GFX13-SDAG-FAKE16-NEXT:    s_load_b32 s2, s[4:5], 0x0
; GFX13-SDAG-FAKE16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX13-SDAG-FAKE16-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-FAKE16-NEXT:    v_sat_pk4_i4_i8_e32 v1, s2
; GFX13-SDAG-FAKE16-NEXT:    flat_store_b16 v0, v1, s[0:1]
; GFX13-SDAG-FAKE16-NEXT:    s_endpgm
  %cvt = call i16 @llvm.amdgcn.sat.pk4.i4.i8(i32 %src) #0
  store i16 %cvt, ptr %out, align 2
  ret void
}

define amdgpu_kernel void @sat_pk4_i4_i8_f32_i(ptr %out) #1 {
; GFX1250-SDAG-REAL16-LABEL: sat_pk4_i4_i8_f32_i:
; GFX1250-SDAG-REAL16:       ; %bb.0:
; GFX1250-SDAG-REAL16-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1250-SDAG-REAL16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x0
; GFX1250-SDAG-REAL16-NEXT:    v_sat_pk4_i4_i8_e32 v0.l, 0x64
; GFX1250-SDAG-REAL16-NEXT:    v_mov_b32_e32 v1, 0
; GFX1250-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-REAL16-NEXT:    flat_store_b16 v1, v0, s[0:1]
; GFX1250-SDAG-REAL16-NEXT:    s_endpgm
;
; GFX1250-SDAG-FAKE16-LABEL: sat_pk4_i4_i8_f32_i:
; GFX1250-SDAG-FAKE16:       ; %bb.0:
; GFX1250-SDAG-FAKE16-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1250-SDAG-FAKE16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x0
; GFX1250-SDAG-FAKE16-NEXT:    v_mov_b32_e32 v0, 0
; GFX1250-SDAG-FAKE16-NEXT:    v_sat_pk4_i4_i8_e32 v1, 0x64
; GFX1250-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-FAKE16-NEXT:    flat_store_b16 v0, v1, s[0:1]
; GFX1250-SDAG-FAKE16-NEXT:    s_endpgm
;
; GFX13-SDAG-REAL16-LABEL: sat_pk4_i4_i8_f32_i:
; GFX13-SDAG-REAL16:       ; %bb.0:
; GFX13-SDAG-REAL16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x0
; GFX13-SDAG-REAL16-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-SDAG-REAL16-NEXT:    v_sat_pk4_i4_i8_e32 v0.l, 0x64
; GFX13-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-REAL16-NEXT:    flat_store_b16 v1, v0, s[0:1]
; GFX13-SDAG-REAL16-NEXT:    s_endpgm
;
; GFX13-SDAG-FAKE16-LABEL: sat_pk4_i4_i8_f32_i:
; GFX13-SDAG-FAKE16:       ; %bb.0:
; GFX13-SDAG-FAKE16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x0
; GFX13-SDAG-FAKE16-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-SDAG-FAKE16-NEXT:    v_sat_pk4_i4_i8_e32 v1, 0x64
; GFX13-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-FAKE16-NEXT:    flat_store_b16 v0, v1, s[0:1]
; GFX13-SDAG-FAKE16-NEXT:    s_endpgm
  %cvt = call i16 @llvm.amdgcn.sat.pk4.i4.i8(i32 100) #0
  store i16 %cvt, ptr %out, align 2
  ret void
}

define amdgpu_kernel void @sat_pk4_u4_u8_f32_v(i32 %src, ptr %out) #1 {
; GFX1250-SDAG-REAL16-LABEL: sat_pk4_u4_u8_f32_v:
; GFX1250-SDAG-REAL16:       ; %bb.0:
; GFX1250-SDAG-REAL16-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1250-SDAG-REAL16-NEXT:    s_clause 0x1
; GFX1250-SDAG-REAL16-NEXT:    s_load_b32 s2, s[4:5], 0x0
; GFX1250-SDAG-REAL16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX1250-SDAG-REAL16-NEXT:    v_mov_b32_e32 v1, 0
; GFX1250-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-REAL16-NEXT:    v_sat_pk4_u4_u8_e32 v0.l, s2
; GFX1250-SDAG-REAL16-NEXT:    flat_store_b16 v1, v0, s[0:1]
; GFX1250-SDAG-REAL16-NEXT:    s_endpgm
;
; GFX1250-SDAG-FAKE16-LABEL: sat_pk4_u4_u8_f32_v:
; GFX1250-SDAG-FAKE16:       ; %bb.0:
; GFX1250-SDAG-FAKE16-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1250-SDAG-FAKE16-NEXT:    s_clause 0x1
; GFX1250-SDAG-FAKE16-NEXT:    s_load_b32 s2, s[4:5], 0x0
; GFX1250-SDAG-FAKE16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX1250-SDAG-FAKE16-NEXT:    v_mov_b32_e32 v0, 0
; GFX1250-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-FAKE16-NEXT:    v_sat_pk4_u4_u8_e32 v1, s2
; GFX1250-SDAG-FAKE16-NEXT:    flat_store_b16 v0, v1, s[0:1]
; GFX1250-SDAG-FAKE16-NEXT:    s_endpgm
;
; GFX13-SDAG-REAL16-LABEL: sat_pk4_u4_u8_f32_v:
; GFX13-SDAG-REAL16:       ; %bb.0:
; GFX13-SDAG-REAL16-NEXT:    s_clause 0x1
; GFX13-SDAG-REAL16-NEXT:    s_load_b32 s2, s[4:5], 0x0
; GFX13-SDAG-REAL16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX13-SDAG-REAL16-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-REAL16-NEXT:    v_sat_pk4_u4_u8_e32 v0.l, s2
; GFX13-SDAG-REAL16-NEXT:    flat_store_b16 v1, v0, s[0:1]
; GFX13-SDAG-REAL16-NEXT:    s_endpgm
;
; GFX13-SDAG-FAKE16-LABEL: sat_pk4_u4_u8_f32_v:
; GFX13-SDAG-FAKE16:       ; %bb.0:
; GFX13-SDAG-FAKE16-NEXT:    s_clause 0x1
; GFX13-SDAG-FAKE16-NEXT:    s_load_b32 s2, s[4:5], 0x0
; GFX13-SDAG-FAKE16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX13-SDAG-FAKE16-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-FAKE16-NEXT:    v_sat_pk4_u4_u8_e32 v1, s2
; GFX13-SDAG-FAKE16-NEXT:    flat_store_b16 v0, v1, s[0:1]
; GFX13-SDAG-FAKE16-NEXT:    s_endpgm
  %cvt = call i16 @llvm.amdgcn.sat.pk4.u4.u8(i32 %src) #0
  store i16 %cvt, ptr %out, align 2
  ret void
}

define amdgpu_kernel void @sat_pk4_u4_u8_f32_s(i32 inreg %src, ptr %out) #1 {
; GFX1250-SDAG-REAL16-LABEL: sat_pk4_u4_u8_f32_s:
; GFX1250-SDAG-REAL16:       ; %bb.0:
; GFX1250-SDAG-REAL16-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1250-SDAG-REAL16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX1250-SDAG-REAL16-NEXT:    v_sat_pk4_u4_u8_e32 v0.l, s8
; GFX1250-SDAG-REAL16-NEXT:    v_mov_b32_e32 v1, 0
; GFX1250-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-REAL16-NEXT:    flat_store_b16 v1, v0, s[0:1]
; GFX1250-SDAG-REAL16-NEXT:    s_endpgm
;
; GFX1250-SDAG-FAKE16-LABEL: sat_pk4_u4_u8_f32_s:
; GFX1250-SDAG-FAKE16:       ; %bb.0:
; GFX1250-SDAG-FAKE16-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1250-SDAG-FAKE16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX1250-SDAG-FAKE16-NEXT:    v_mov_b32_e32 v0, 0
; GFX1250-SDAG-FAKE16-NEXT:    v_sat_pk4_u4_u8_e32 v1, s8
; GFX1250-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-FAKE16-NEXT:    flat_store_b16 v0, v1, s[0:1]
; GFX1250-SDAG-FAKE16-NEXT:    s_endpgm
;
; GFX13-SDAG-REAL16-LABEL: sat_pk4_u4_u8_f32_s:
; GFX13-SDAG-REAL16:       ; %bb.0:
; GFX13-SDAG-REAL16-NEXT:    s_clause 0x1
; GFX13-SDAG-REAL16-NEXT:    s_load_b32 s2, s[4:5], 0x0
; GFX13-SDAG-REAL16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX13-SDAG-REAL16-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-REAL16-NEXT:    v_sat_pk4_u4_u8_e32 v0.l, s2
; GFX13-SDAG-REAL16-NEXT:    flat_store_b16 v1, v0, s[0:1]
; GFX13-SDAG-REAL16-NEXT:    s_endpgm
;
; GFX13-SDAG-FAKE16-LABEL: sat_pk4_u4_u8_f32_s:
; GFX13-SDAG-FAKE16:       ; %bb.0:
; GFX13-SDAG-FAKE16-NEXT:    s_clause 0x1
; GFX13-SDAG-FAKE16-NEXT:    s_load_b32 s2, s[4:5], 0x0
; GFX13-SDAG-FAKE16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x8
; GFX13-SDAG-FAKE16-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-FAKE16-NEXT:    v_sat_pk4_u4_u8_e32 v1, s2
; GFX13-SDAG-FAKE16-NEXT:    flat_store_b16 v0, v1, s[0:1]
; GFX13-SDAG-FAKE16-NEXT:    s_endpgm
  %cvt = call i16 @llvm.amdgcn.sat.pk4.u4.u8(i32 %src) #0
  store i16 %cvt, ptr %out, align 2
  ret void
}

define amdgpu_kernel void @sat_pk4_u4_u8_f32_i(ptr %out) #1 {
; GFX1250-SDAG-REAL16-LABEL: sat_pk4_u4_u8_f32_i:
; GFX1250-SDAG-REAL16:       ; %bb.0:
; GFX1250-SDAG-REAL16-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1250-SDAG-REAL16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x0
; GFX1250-SDAG-REAL16-NEXT:    v_sat_pk4_u4_u8_e32 v0.l, 0x64
; GFX1250-SDAG-REAL16-NEXT:    v_mov_b32_e32 v1, 0
; GFX1250-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-REAL16-NEXT:    flat_store_b16 v1, v0, s[0:1]
; GFX1250-SDAG-REAL16-NEXT:    s_endpgm
;
; GFX1250-SDAG-FAKE16-LABEL: sat_pk4_u4_u8_f32_i:
; GFX1250-SDAG-FAKE16:       ; %bb.0:
; GFX1250-SDAG-FAKE16-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1250-SDAG-FAKE16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x0
; GFX1250-SDAG-FAKE16-NEXT:    v_mov_b32_e32 v0, 0
; GFX1250-SDAG-FAKE16-NEXT:    v_sat_pk4_u4_u8_e32 v1, 0x64
; GFX1250-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-FAKE16-NEXT:    flat_store_b16 v0, v1, s[0:1]
; GFX1250-SDAG-FAKE16-NEXT:    s_endpgm
;
; GFX13-SDAG-REAL16-LABEL: sat_pk4_u4_u8_f32_i:
; GFX13-SDAG-REAL16:       ; %bb.0:
; GFX13-SDAG-REAL16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x0
; GFX13-SDAG-REAL16-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-SDAG-REAL16-NEXT:    v_sat_pk4_u4_u8_e32 v0.l, 0x64
; GFX13-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-REAL16-NEXT:    flat_store_b16 v1, v0, s[0:1]
; GFX13-SDAG-REAL16-NEXT:    s_endpgm
;
; GFX13-SDAG-FAKE16-LABEL: sat_pk4_u4_u8_f32_i:
; GFX13-SDAG-FAKE16:       ; %bb.0:
; GFX13-SDAG-FAKE16-NEXT:    s_load_b64 s[0:1], s[4:5], 0x0
; GFX13-SDAG-FAKE16-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-SDAG-FAKE16-NEXT:    v_sat_pk4_u4_u8_e32 v1, 0x64
; GFX13-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-FAKE16-NEXT:    flat_store_b16 v0, v1, s[0:1]
; GFX13-SDAG-FAKE16-NEXT:    s_endpgm
  %cvt = call i16 @llvm.amdgcn.sat.pk4.u4.u8(i32 100) #0
  store i16 %cvt, ptr %out, align 2
  ret void
}

attributes #0 = { nounwind memory(none) }
attributes #1 = { nounwind }
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; GISEL-FAKE16: {{.*}}
; GISEL-REAL16: {{.*}}
; SDAG-FAKE16: {{.*}}
; SDAG-REAL16: {{.*}}
