; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -mattr=+real-true16 %s -o - | FileCheck -check-prefixes=SDAG-REAL16 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1260 -mattr=+real-true16 %s -o - | FileCheck -check-prefixes=SDAG-REAL16 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -mattr=-real-true16 %s -o - | FileCheck -check-prefixes=SDAG-FAKE16 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1260 -mattr=-real-true16 %s -o - | FileCheck -check-prefixes=SDAG-FAKE16 %s
; xUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -mattr=+real-true16 %s -o - | FileCheck -check-prefixes=GISEL-REAL16,GFX1250-GISEL-REAL16 %s
; xUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -mattr=-real-true16 %s -o - | FileCheck -check-prefixes=GISEL-FAKE16,GFX1250-GISEL-FAKE16 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -mattr=+real-true16 %s -o - | FileCheck -check-prefixes=SDAG-REAL16 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -mattr=-real-true16 %s -o - | FileCheck -check-prefixes=SDAG-FAKE16 %s
; xUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -mattr=+real-true16 %s -o - | FileCheck -check-prefixes=GISEL-REAL16,GFX13-GISEL-REAL16 %s
; xUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -mattr=-real-true16 %s -o - | FileCheck -check-prefixes=GISEL-FAKE16,GFX13-GISEL-FAKE16 %s

; FIXME: GlobalISel does not work with bf16

declare float @llvm.amdgcn.tanh.f32(float) #0
declare half @llvm.amdgcn.tanh.f16(half) #0
declare bfloat @llvm.amdgcn.tanh.bf16(bfloat) #0

define amdgpu_kernel void @tanh_f32(ptr addrspace(1) %out, float %src) #1 {
  %tanh = call float @llvm.amdgcn.tanh.f32(float %src) #0
  store float %tanh, ptr addrspace(1) %out, align 4
  ret void
}

; TODO: Really these should be constant folded
define amdgpu_kernel void @tanh_f32_constant_4.0(ptr addrspace(1) %out) #1 {
  %tanh = call float @llvm.amdgcn.tanh.f32(float 4.0) #0
  store float %tanh, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @tanh_f32_constant_100.0(ptr addrspace(1) %out) #1 {
  %tanh = call float @llvm.amdgcn.tanh.f32(float 100.0) #0
  store float %tanh, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @tanh_undef_f32(ptr addrspace(1) %out) #1 {
  %tanh = call float @llvm.amdgcn.tanh.f32(float undef)
  store float %tanh, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @tanh_f16(ptr addrspace(1) %out, half %src) #1 {
  %tanh = call half @llvm.amdgcn.tanh.f16(half %src) #0
  store half %tanh, ptr addrspace(1) %out, align 2
  ret void
}

define amdgpu_kernel void @tanh_f16_constant_4.0(ptr addrspace(1) %out) #1 {
  %tanh = call half @llvm.amdgcn.tanh.f16(half 4.0) #0
  store half %tanh, ptr addrspace(1) %out, align 2
  ret void
}

define amdgpu_kernel void @tanh_f16_constant_100.0(ptr addrspace(1) %out) #1 {
  %tanh = call half @llvm.amdgcn.tanh.f16(half 100.0) #0
  store half %tanh, ptr addrspace(1) %out, align 2
  ret void
}

define amdgpu_kernel void @tanh_undef_f16(ptr addrspace(1) %out) #1 {
  %tanh = call half @llvm.amdgcn.tanh.f16(half undef)
  store half %tanh, ptr addrspace(1) %out, align 2
  ret void
}

define amdgpu_kernel void @tanh_bf16(ptr addrspace(1) %out, bfloat %src) #1 {
  %tanh = call bfloat @llvm.amdgcn.tanh.bf16(bfloat %src) #0
  store bfloat %tanh, ptr addrspace(1) %out, align 2
  ret void
}

define amdgpu_kernel void @tanh_bf16_constant_4(ptr addrspace(1) %out) #1 {
  %tanh = call bfloat @llvm.amdgcn.tanh.bf16(bfloat 4.0) #0
  store bfloat %tanh, ptr addrspace(1) %out, align 2
  ret void
}

define amdgpu_kernel void @tanh_bf16_constant_100(ptr addrspace(1) %out) #1 {
  %tanh = call bfloat @llvm.amdgcn.tanh.bf16(bfloat 100.0) #0
  store bfloat %tanh, ptr addrspace(1) %out, align 2
  ret void
}

define amdgpu_kernel void @tanh_undef_bf16(ptr addrspace(1) %out) #1 {
  %tanh = call bfloat @llvm.amdgcn.tanh.bf16(bfloat undef)
  store bfloat %tanh, ptr addrspace(1) %out, align 2
  ret void
}

attributes #0 = { nounwind readnone }
attributes #1 = { nounwind }
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; SDAG-FAKE16: {{.*}}
; SDAG-REAL16: {{.*}}
