; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn -mcpu=gfx1260 -global-isel=0 < %s | FileCheck -check-prefixes=GFX1260,GFX1260-SDAG %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1260 -global-isel=1 < %s | FileCheck -check-prefixes=GFX1260,GFX1260-GISEL %s

define amdgpu_ps void @test_wmma_tr_16x16_b16(<8 x i16> %inp, ptr addrspace (1) %out) {
; GFX1260-LABEL: test_wmma_tr_16x16_b16:
; GFX1260:       ; %bb.0:
; GFX1260-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1260-NEXT:    v_wmma_tr_16x16_b16 v[6:9], v[0:3]
; GFX1260-NEXT:    global_store_b128 v[4:5], v[6:9], off
; GFX1260-NEXT:    s_endpgm
  %res = call <8 x i16> @llvm.amdgcn.wmma.tr.16x16.b16(<8 x i16> %inp)
  store <8 x i16> %res, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @test_wmma_tr_32x32_b16(<32 x i16> %inp, ptr addrspace (1) %out) {
; GFX1260-SDAG-LABEL: test_wmma_tr_32x32_b16:
; GFX1260-SDAG:       ; %bb.0:
; GFX1260-SDAG-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1260-SDAG-NEXT:    v_wmma_tr_32x32_b16 v[18:33], v[0:15]
; GFX1260-SDAG-NEXT:    s_clause 0x3
; GFX1260-SDAG-NEXT:    global_store_b128 v[16:17], v[30:33], off offset:48
; GFX1260-SDAG-NEXT:    global_store_b128 v[16:17], v[26:29], off offset:32
; GFX1260-SDAG-NEXT:    global_store_b128 v[16:17], v[22:25], off offset:16
; GFX1260-SDAG-NEXT:    global_store_b128 v[16:17], v[18:21], off
; GFX1260-SDAG-NEXT:    s_endpgm
;
; GFX1260-GISEL-LABEL: test_wmma_tr_32x32_b16:
; GFX1260-GISEL:       ; %bb.0:
; GFX1260-GISEL-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1
; GFX1260-GISEL-NEXT:    v_wmma_tr_32x32_b16 v[18:33], v[0:15]
; GFX1260-GISEL-NEXT:    s_clause 0x3
; GFX1260-GISEL-NEXT:    global_store_b128 v[16:17], v[18:21], off
; GFX1260-GISEL-NEXT:    global_store_b128 v[16:17], v[22:25], off offset:16
; GFX1260-GISEL-NEXT:    global_store_b128 v[16:17], v[26:29], off offset:32
; GFX1260-GISEL-NEXT:    global_store_b128 v[16:17], v[30:33], off offset:48
; GFX1260-GISEL-NEXT:    s_endpgm
  %res = call <32 x i16> @llvm.amdgcn.wmma.tr.32x32.b16(<32 x i16> %inp)
  store <32 x i16> %res, ptr addrspace(1) %out
  ret void
}

