; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-- -mcpu=gfx1310 -amdgpu-promote-private=true -verify-machineinstrs -o - %s | FileCheck -check-prefix=CHECK %s

define i32 @private_load_store(i32 inreg %idx) alwaysinline #0 {
; CHECK-LABEL: private_load_store:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_wait_loadcnt_dscnt 0x0
; CHECK-NEXT:    s_wait_expcnt 0x0
; CHECK-NEXT:    s_wait_samplecnt 0x0
; CHECK-NEXT:    s_wait_rtscnt 0x0
; CHECK-NEXT:    s_wait_kmcnt 0x0
; CHECK-NEXT:    s_getreg_b32 s1, hwreg(HW_REG_WAVE_GPR_MSB_IDX0, 0, 10)
; CHECK-NEXT:    v_mov_b32_e32 v33, 0
; CHECK-NEXT:    s_lshl_b32 s1, s1, 2
; CHECK-NEXT:    v_mov_b32_e32 v34, 1
; CHECK-NEXT:    s_lshr_b32 s2, s1, 2
; CHECK-NEXT:    s_lshl2_add_u32 s0, s0, s1
; CHECK-NEXT:    ; VGPR lifetime start: v[0:32]
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, s2
; CHECK-NEXT:    s_lshr_b32 s0, s0, 2
; CHECK-NEXT:    s_set_vgpr_frames 64 ; vsrc0_idx=0 vsrc1_idx=0 vsrc2_idx=0 vdst_idx=1 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    v_mov_b32_e32 g1[5], v33
; CHECK-NEXT:    v_mov_b32_e32 g1[6], v34
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, s0
; CHECK-NEXT:    s_set_vgpr_frames 1 ; vsrc0_idx=1 vsrc1_idx=0 vsrc2_idx=0 vdst_idx=0 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    v_mov_b32_e32 v33, g1[0]
; CHECK-NEXT:    ; VGPR lifetime end: v[0:32]
; CHECK-NEXT:    s_set_vgpr_frames 0 ; vsrc0_idx=0 vsrc1_idx=0 vsrc2_idx=0 vdst_idx=0 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; CHECK-NEXT:    v_mov_b32_e32 v0, v33
; CHECK-NEXT:    s_set_pc_i64 s[30:31]
entry:
  %p = alloca [33 x float], align 4, addrspace(5)
  %p.5 = getelementptr i32, ptr addrspace(5) %p, i32 5
  %p.6 = getelementptr i32, ptr addrspace(5) %p, i32 6
  store i32 0, ptr addrspace(5) %p.5
  store i32 1, ptr addrspace(5) %p.6

  %p.i = getelementptr i32, ptr addrspace(5) %p, i32 %idx
  %x = load i32, ptr addrspace(5) %p.i
  ret i32 %x
}

attributes #0 = { "amdgpu-flat-work-group-size"="32,32" }
