; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -amdgpu-promote-private=true -private-object-reg-chunk-size=4 -verify-machineinstrs -o - %s | FileCheck --check-prefixes=CHECK,KERNEL %s

define amdgpu_kernel void @foo(ptr addrspace(5) %out, i32 %x) #0 {
; CHECK-LABEL: foo:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_load_b64 s[0:1], s[4:5], 0x0
; CHECK-NEXT:    ; VGPR lifetime start: v[0:32]
; CHECK-NEXT:    s_set_gpr_idx_u32 idx2, 0
; CHECK-NEXT:    s_set_vgpr_frames 0x84 ; vsrc0_idx=0 vsrc1_idx=1 vsrc2_idx=0 vdst_idx=2 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    v_mov_b32_e32 g2[1], 0x40a00000
; CHECK-NEXT:    s_wait_kmcnt 0x0
; CHECK-NEXT:    s_lshl_b32 s2, s1, 2
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; CHECK-NEXT:    s_lshr_b32 s2, s2, 2
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, s2
; CHECK-NEXT:    ; VGPR lifetime start: v[33:65]
; CHECK-NEXT:    scratch_store_b32 off, g1[0], s0 offset:20
; CHECK-NEXT:    v_mov_b32_e32 g2[34], 0x40e00000
; CHECK-NEXT:    scratch_store_b32 off, g1[33], s0 offset:28
; CHECK-NEXT:    ; VGPR lifetime end: v[0:32]
; CHECK-NEXT:    ; VGPR lifetime end: v[33:65]
; CHECK-NEXT:    s_endpgm
entry:
  %p = alloca [33 x float], align 4, addrspace(5)
  %p.1 = getelementptr [33 x float], ptr addrspace(5) %p, i32 0, i32 1
  store float 5.0, ptr addrspace(5) %p.1, align 4
  %p.2 = getelementptr float, ptr addrspace(5) %p, i32 %x
  %vp = load float, ptr addrspace(5) %p.2, align 4

  %q = alloca [33 x float], align 4, addrspace(5)
  %q.1 = getelementptr [33 x float], ptr addrspace(5) %q, i32 0, i32 1
  store float 7.0, ptr addrspace(5) %q.1, align 4
  %q.2 = getelementptr float, ptr addrspace(5) %q, i32 %x
  %vq = load float, ptr addrspace(5) %q.2, align 4

  %out.5 = getelementptr i32, ptr addrspace(5) %out, i32 5
  store float %vp, ptr addrspace(5) %out.5

  %out.7 = getelementptr i32, ptr addrspace(5) %out, i32 7
  store float %vq, ptr addrspace(5) %out.7

  ret void
}

attributes #0 = { "amdgpu-flat-work-group-size"="32,32" }

; KERNEL:    .enable_wavegroup: false
; KERNEL-NEXT:    .group_segment_fixed_size: 0
; KERNEL-NEXT:    .kernarg_segment_align: 8
; KERNEL-NEXT:    .kernarg_segment_size: 264
; KERNEL-NEXT:    .laneshared_segment_fixed_size: 0
; KERNEL-NEXT:    .max_flat_workgroup_size: 32
; KERNEL-NEXT:    .name:           foo
; KERNEL-NEXT:    .private_segment_fixed_size: 268
; KERNEL-NEXT:    .sgpr_count:     6
; KERNEL-NEXT:    .sgpr_spill_count: 0
; KERNEL-NEXT:    .spatial_cluster: false
; KERNEL-NEXT:    .symbol:         foo.kd
; KERNEL-NEXT:    .uses_dynamic_stack: false
; KERNEL-NEXT:    .vgpr_count:     66
; KERNEL-NEXT:    .vgpr_spill_count: 0
; KERNEL-NEXT:    .wavefront_size: 32
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; KERNEL: {{.*}}
