; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-- -mcpu=gfx1310 -amdgpu-promote-private=true -amdgpu-promote-sub-dword=true -mattr=-real-true16 -stop-after=finalize-isel -verify-machineinstrs -o - %s | FileCheck -check-prefix=VIDX %s
; RUN: llc -mtriple=amdgcn-- -mcpu=gfx1310 -amdgpu-promote-private=true -amdgpu-promote-sub-dword=true -mattr=-real-true16 -stop-after=bundle-indexed-load-store -verify-machineinstrs -o - %s | FileCheck -check-prefix=BUNDLE %s
; RUN: llc -mtriple=amdgcn-- -mcpu=gfx1310 -amdgpu-promote-private=true -amdgpu-promote-sub-dword=true -mattr=-real-true16 -stop-after=amdgpu-idx-reg-alloc -verify-machineinstrs -o - %s | FileCheck -check-prefix=SETIDX %s
; RUN: llc -mtriple=amdgcn-- -mcpu=gfx1310 -amdgpu-promote-private=true -amdgpu-promote-sub-dword=true -mattr=+real-true16 -stop-after=finalize-isel -verify-machineinstrs -o - %s | FileCheck -check-prefix=REAL16-VIDX %s
; RUN: llc -mtriple=amdgcn-- -mcpu=gfx1310 -amdgpu-promote-private=true -amdgpu-promote-sub-dword=true -mattr=+real-true16 -stop-after=bundle-indexed-load-store -verify-machineinstrs -o - %s | FileCheck -check-prefix=REAL16-BUNDLE %s
; RUN: llc -mtriple=amdgcn-- -mcpu=gfx1310 -amdgpu-promote-private=true -amdgpu-promote-sub-dword=true -mattr=+real-true16 -stop-after=amdgpu-idx-reg-alloc -verify-machineinstrs -o - %s | FileCheck -check-prefix=REAL16-SETIDX %s

define amdgpu_kernel void @subdword() #0 {
  ; VIDX-LABEL: name: subdword
  ; VIDX: bb.0.entry:
  ; VIDX-NEXT:   VGPR_LIFETIME_START :: (dereferenceable store (s1056) into %ir.q, align 1, addrspace 5)
  ; VIDX-NEXT:   VGPR_LIFETIME_START :: (dereferenceable store (s1056) into %ir.p, align 1, addrspace 5)
  ; VIDX-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 2
  ; VIDX-NEXT:   [[S_ADD_I32_:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 [[S_MOV_B32_]], 0, implicit-def dead $scc
  ; VIDX-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_]], 3, implicit-def dead $scc
  ; VIDX-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_]], 3, implicit-def dead $scc
  ; VIDX-NEXT:   [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_MOV_B32_]], 2, implicit-def dead $scc
  ; VIDX-NEXT:   [[V_LOAD_IDX_BITS:%[0-9]+]]:vgpr_32 = V_LOAD_IDX_BITS [[S_LSHR_B32_]], 0, 16, [[S_LSHL_B32_]], 0, implicit $exec :: (load (s16) from %ir.p.1, align 4, addrspace 5)
  ; VIDX-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 4
  ; VIDX-NEXT:   [[S_ADD_I32_1:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 [[S_MOV_B32_1]], 0, implicit-def dead $scc
  ; VIDX-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_1]], 3, implicit-def dead $scc
  ; VIDX-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_1]], 3, implicit-def dead $scc
  ; VIDX-NEXT:   [[S_LSHR_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_MOV_B32_1]], 2, implicit-def dead $scc
  ; VIDX-NEXT:   V_STORE_IDX_BITS [[V_LOAD_IDX_BITS]], [[S_LSHR_B32_1]], 0, 16, [[S_LSHL_B32_1]], implicit $exec :: (store (s16) into %ir.p.2, align 4, addrspace 5)
  ; VIDX-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 134
  ; VIDX-NEXT:   [[S_ADD_I32_2:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 [[S_MOV_B32_2]], 0, implicit-def dead $scc
  ; VIDX-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_2]], 3, implicit-def dead $scc
  ; VIDX-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_2]], 3, implicit-def dead $scc
  ; VIDX-NEXT:   [[S_LSHR_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_MOV_B32_2]], 2, implicit-def dead $scc
  ; VIDX-NEXT:   [[V_LOAD_IDX_BITS1:%[0-9]+]]:vgpr_32 = V_LOAD_IDX_BITS [[S_LSHR_B32_2]], 0, 16, [[S_LSHL_B32_2]], 0, implicit $exec :: (load (s16) from %ir.q.1, align 4, addrspace 5)
  ; VIDX-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 136
  ; VIDX-NEXT:   [[S_ADD_I32_3:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 [[S_MOV_B32_3]], 0, implicit-def dead $scc
  ; VIDX-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_3]], 3, implicit-def dead $scc
  ; VIDX-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_3]], 3, implicit-def dead $scc
  ; VIDX-NEXT:   [[S_LSHR_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_MOV_B32_3]], 2, implicit-def dead $scc
  ; VIDX-NEXT:   V_STORE_IDX_BITS [[V_LOAD_IDX_BITS1]], [[S_LSHR_B32_3]], 0, 16, [[S_LSHL_B32_3]], implicit $exec :: (store (s16) into %ir.q.2, align 4, addrspace 5)
  ; VIDX-NEXT:   S_ENDPGM 0
  ;
  ; BUNDLE-LABEL: name: subdword
  ; BUNDLE: bb.0.entry:
  ; BUNDLE-NEXT:   VGPR_LIFETIME_START :: (dereferenceable store (s1056) into %ir.q, align 1, addrspace 5)
  ; BUNDLE-NEXT:   VGPR_LIFETIME_START :: (dereferenceable store (s1056) into %ir.p, align 1, addrspace 5)
  ; BUNDLE-NEXT:   [[S_ADD_I32_:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 2, 0, implicit-def dead $scc
  ; BUNDLE-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_]], 3, implicit-def dead $scc
  ; BUNDLE-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_]], 3, implicit-def dead $scc
  ; BUNDLE-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 0
  ; BUNDLE-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %6, implicit [[S_MOV_B32_]], implicit $exec, implicit [[S_LSHL_B32_]] :: (load (s16) from %ir.p.1, align 4, addrspace 5) {
  ; BUNDLE-NEXT:     $stg_srca = V_LOAD_IDX_B32 [[S_MOV_B32_]], 0, implicit $exec :: (load (s16) from %ir.p.1, align 4, addrspace 5)
  ; BUNDLE-NEXT:     [[V_BFE_U32_e64_:%[0-9]+]]:vgpr_32 = V_BFE_U32_e64 internal $stg_srca, [[S_LSHL_B32_]], 16, implicit $exec
  ; BUNDLE-NEXT:   }
  ; BUNDLE-NEXT:   [[S_ADD_I32_1:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 4, 0, implicit-def dead $scc
  ; BUNDLE-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_1]], 3, implicit-def dead $scc
  ; BUNDLE-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_1]], 3, implicit-def dead $scc
  ; BUNDLE-NEXT:   [[V_BFM_B32_e64_:%[0-9]+]]:vgpr_32 = V_BFM_B32_e64 16, [[S_LSHL_B32_1]], implicit $exec
  ; BUNDLE-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_MOV_B32_]], implicit $exec, implicit [[V_BFM_B32_e64_]], implicit [[V_BFE_U32_e64_]] :: (load (s16) from %ir.p.2, align 4, addrspace 5), (store (s16) into %ir.p.2, align 4, addrspace 5) {
  ; BUNDLE-NEXT:     $stg_srca = V_LOAD_IDX_B32 [[S_MOV_B32_]], 1, implicit $exec :: (load (s16) from %ir.p.2, align 4, addrspace 5)
  ; BUNDLE-NEXT:     $stg_dsta = V_BFI_B32_e64 [[V_BFM_B32_e64_]], [[V_BFE_U32_e64_]], internal $stg_srca, implicit $exec
  ; BUNDLE-NEXT:     V_STORE_IDX_B32 internal $stg_dsta, [[S_MOV_B32_]], 1, implicit $exec :: (store (s16) into %ir.p.2, align 4, addrspace 5)
  ; BUNDLE-NEXT:   }
  ; BUNDLE-NEXT:   [[S_ADD_I32_2:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 134, 0, implicit-def dead $scc
  ; BUNDLE-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_2]], 3, implicit-def dead $scc
  ; BUNDLE-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_2]], 3, implicit-def dead $scc
  ; BUNDLE-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %9, implicit [[S_MOV_B32_]], implicit $exec, implicit [[S_LSHL_B32_2]] :: (load (s16) from %ir.q.1, align 4, addrspace 5) {
  ; BUNDLE-NEXT:     $stg_srca = V_LOAD_IDX_B32 [[S_MOV_B32_]], 33, implicit $exec :: (load (s16) from %ir.q.1, align 4, addrspace 5)
  ; BUNDLE-NEXT:     [[V_BFE_U32_e64_1:%[0-9]+]]:vgpr_32 = V_BFE_U32_e64 internal $stg_srca, [[S_LSHL_B32_2]], 16, implicit $exec
  ; BUNDLE-NEXT:   }
  ; BUNDLE-NEXT:   [[S_ADD_I32_3:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 136, 0, implicit-def dead $scc
  ; BUNDLE-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_3]], 3, implicit-def dead $scc
  ; BUNDLE-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_3]], 3, implicit-def dead $scc
  ; BUNDLE-NEXT:   [[V_BFM_B32_e64_1:%[0-9]+]]:vgpr_32 = V_BFM_B32_e64 16, [[S_LSHL_B32_3]], implicit $exec
  ; BUNDLE-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit killed [[S_MOV_B32_]], implicit $exec, implicit [[V_BFM_B32_e64_1]], implicit [[V_BFE_U32_e64_1]] :: (load (s16) from %ir.q.2, align 4, addrspace 5), (store (s16) into %ir.q.2, align 4, addrspace 5) {
  ; BUNDLE-NEXT:     $stg_srca = V_LOAD_IDX_B32 [[S_MOV_B32_]], 34, implicit $exec :: (load (s16) from %ir.q.2, align 4, addrspace 5)
  ; BUNDLE-NEXT:     $stg_dsta = V_BFI_B32_e64 [[V_BFM_B32_e64_1]], [[V_BFE_U32_e64_1]], internal $stg_srca, implicit $exec
  ; BUNDLE-NEXT:     V_STORE_IDX_B32 internal $stg_dsta, killed [[S_MOV_B32_]], 34, implicit $exec :: (store (s16) into %ir.q.2, align 4, addrspace 5)
  ; BUNDLE-NEXT:   }
  ; BUNDLE-NEXT:   S_ENDPGM 0
  ;
  ; SETIDX-LABEL: name: subdword
  ; SETIDX: bb.0.entry:
  ; SETIDX-NEXT:   VGPR_LIFETIME_START :: (dereferenceable store (s1056) into %ir.q, align 1, addrspace 5)
  ; SETIDX-NEXT:   VGPR_LIFETIME_START :: (dereferenceable store (s1056) into %ir.p, align 1, addrspace 5)
  ; SETIDX-NEXT:   [[S_ADD_I32_:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 2, 0, implicit-def dead $scc
  ; SETIDX-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_]], 3, implicit-def dead $scc
  ; SETIDX-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_]], 3, implicit-def dead $scc
  ; SETIDX-NEXT:   $idx1 = S_SET_GPR_IDX_U32 0
  ; SETIDX-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %6, implicit $idx1, implicit $exec, implicit [[S_LSHL_B32_]] :: (load (s16) from %ir.p.1, align 4, addrspace 5) {
  ; SETIDX-NEXT:     $stg_srca = V_LOAD_IDX_B32 $idx1, 0, implicit $exec :: (load (s16) from %ir.p.1, align 4, addrspace 5)
  ; SETIDX-NEXT:     [[V_BFE_U32_e64_:%[0-9]+]]:vgpr_32 = V_BFE_U32_e64 internal $stg_srca, [[S_LSHL_B32_]], 16, implicit $exec
  ; SETIDX-NEXT:   }
  ; SETIDX-NEXT:   [[S_ADD_I32_1:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 4, 0, implicit-def dead $scc
  ; SETIDX-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_1]], 3, implicit-def dead $scc
  ; SETIDX-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_1]], 3, implicit-def dead $scc
  ; SETIDX-NEXT:   [[V_BFM_B32_e64_:%[0-9]+]]:vgpr_32 = V_BFM_B32_e64 16, [[S_LSHL_B32_1]], implicit $exec
  ; SETIDX-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx1, implicit $exec, implicit [[V_BFM_B32_e64_]], implicit [[V_BFE_U32_e64_]] :: (load (s16) from %ir.p.2, align 4, addrspace 5), (store (s16) into %ir.p.2, align 4, addrspace 5) {
  ; SETIDX-NEXT:     $stg_srca = V_LOAD_IDX_B32 $idx1, 1, implicit $exec :: (load (s16) from %ir.p.2, align 4, addrspace 5)
  ; SETIDX-NEXT:     $stg_dsta = V_BFI_B32_e64 [[V_BFM_B32_e64_]], [[V_BFE_U32_e64_]], internal $stg_srca, implicit $exec
  ; SETIDX-NEXT:     V_STORE_IDX_B32 internal $stg_dsta, $idx1, 1, implicit $exec :: (store (s16) into %ir.p.2, align 4, addrspace 5)
  ; SETIDX-NEXT:   }
  ; SETIDX-NEXT:   [[S_ADD_I32_2:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 134, 0, implicit-def dead $scc
  ; SETIDX-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_2]], 3, implicit-def dead $scc
  ; SETIDX-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_2]], 3, implicit-def dead $scc
  ; SETIDX-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %9, implicit $idx1, implicit $exec, implicit [[S_LSHL_B32_2]] :: (load (s16) from %ir.q.1, align 4, addrspace 5) {
  ; SETIDX-NEXT:     $stg_srca = V_LOAD_IDX_B32 $idx1, 33, implicit $exec :: (load (s16) from %ir.q.1, align 4, addrspace 5)
  ; SETIDX-NEXT:     [[V_BFE_U32_e64_1:%[0-9]+]]:vgpr_32 = V_BFE_U32_e64 internal $stg_srca, [[S_LSHL_B32_2]], 16, implicit $exec
  ; SETIDX-NEXT:   }
  ; SETIDX-NEXT:   [[S_ADD_I32_3:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 136, 0, implicit-def dead $scc
  ; SETIDX-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_3]], 3, implicit-def dead $scc
  ; SETIDX-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_3]], 3, implicit-def dead $scc
  ; SETIDX-NEXT:   [[V_BFM_B32_e64_1:%[0-9]+]]:vgpr_32 = V_BFM_B32_e64 16, [[S_LSHL_B32_3]], implicit $exec
  ; SETIDX-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit killed $idx1, implicit $exec, implicit [[V_BFM_B32_e64_1]], implicit [[V_BFE_U32_e64_1]] :: (load (s16) from %ir.q.2, align 4, addrspace 5), (store (s16) into %ir.q.2, align 4, addrspace 5) {
  ; SETIDX-NEXT:     $stg_srca = V_LOAD_IDX_B32 $idx1, 34, implicit $exec :: (load (s16) from %ir.q.2, align 4, addrspace 5)
  ; SETIDX-NEXT:     $stg_dsta = V_BFI_B32_e64 [[V_BFM_B32_e64_1]], [[V_BFE_U32_e64_1]], internal $stg_srca, implicit $exec
  ; SETIDX-NEXT:     V_STORE_IDX_B32 internal $stg_dsta, killed $idx1, 34, implicit $exec :: (store (s16) into %ir.q.2, align 4, addrspace 5)
  ; SETIDX-NEXT:   }
  ; SETIDX-NEXT:   S_ENDPGM 0
  ;
  ; REAL16-VIDX-LABEL: name: subdword
  ; REAL16-VIDX: bb.0.entry:
  ; REAL16-VIDX-NEXT:   VGPR_LIFETIME_START :: (dereferenceable store (s1056) into %ir.q, align 1, addrspace 5)
  ; REAL16-VIDX-NEXT:   VGPR_LIFETIME_START :: (dereferenceable store (s1056) into %ir.p, align 1, addrspace 5)
  ; REAL16-VIDX-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 2
  ; REAL16-VIDX-NEXT:   [[S_ADD_I32_:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 [[S_MOV_B32_]], 0, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_]], 3, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_]], 3, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_MOV_B32_]], 2, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[V_LOAD_IDX_BITS_D16_:%[0-9]+]]:vgpr_16 = V_LOAD_IDX_BITS_D16 [[S_LSHR_B32_]], 0, 16, [[S_LSHL_B32_]], 0, implicit $exec :: (load (s16) from %ir.p.1, align 4, addrspace 5)
  ; REAL16-VIDX-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 4
  ; REAL16-VIDX-NEXT:   [[S_ADD_I32_1:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 [[S_MOV_B32_1]], 0, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_1]], 3, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_1]], 3, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[S_LSHR_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_MOV_B32_1]], 2, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   V_STORE_IDX_BITS_D16 [[V_LOAD_IDX_BITS_D16_]], [[S_LSHR_B32_1]], 0, 16, [[S_LSHL_B32_1]], implicit $exec :: (store (s16) into %ir.p.2, align 4, addrspace 5)
  ; REAL16-VIDX-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 134
  ; REAL16-VIDX-NEXT:   [[S_ADD_I32_2:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 [[S_MOV_B32_2]], 0, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_2]], 3, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_2]], 3, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[S_LSHR_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_MOV_B32_2]], 2, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[V_LOAD_IDX_BITS_D16_1:%[0-9]+]]:vgpr_16 = V_LOAD_IDX_BITS_D16 [[S_LSHR_B32_2]], 0, 16, [[S_LSHL_B32_2]], 0, implicit $exec :: (load (s16) from %ir.q.1, align 4, addrspace 5)
  ; REAL16-VIDX-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 136
  ; REAL16-VIDX-NEXT:   [[S_ADD_I32_3:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 [[S_MOV_B32_3]], 0, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_3]], 3, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_3]], 3, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   [[S_LSHR_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_MOV_B32_3]], 2, implicit-def dead $scc
  ; REAL16-VIDX-NEXT:   V_STORE_IDX_BITS_D16 [[V_LOAD_IDX_BITS_D16_1]], [[S_LSHR_B32_3]], 0, 16, [[S_LSHL_B32_3]], implicit $exec :: (store (s16) into %ir.q.2, align 4, addrspace 5)
  ; REAL16-VIDX-NEXT:   S_ENDPGM 0
  ;
  ; REAL16-BUNDLE-LABEL: name: subdword
  ; REAL16-BUNDLE: bb.0.entry:
  ; REAL16-BUNDLE-NEXT:   VGPR_LIFETIME_START :: (dereferenceable store (s1056) into %ir.q, align 1, addrspace 5)
  ; REAL16-BUNDLE-NEXT:   VGPR_LIFETIME_START :: (dereferenceable store (s1056) into %ir.p, align 1, addrspace 5)
  ; REAL16-BUNDLE-NEXT:   [[S_ADD_I32_:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 2, 0, implicit-def dead $scc
  ; REAL16-BUNDLE-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_]], 3, implicit-def dead $scc
  ; REAL16-BUNDLE-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_]], 3, implicit-def dead $scc
  ; REAL16-BUNDLE-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 0
  ; REAL16-BUNDLE-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %28, implicit [[S_MOV_B32_]], implicit $exec, implicit [[S_LSHL_B32_]] :: (load (s16) from %ir.p.1, align 4, addrspace 5) {
  ; REAL16-BUNDLE-NEXT:     $stg_srca = V_LOAD_IDX_B32 [[S_MOV_B32_]], 0, implicit $exec :: (load (s16) from %ir.p.1, align 4, addrspace 5)
  ; REAL16-BUNDLE-NEXT:     [[V_BFE_U32_e64_:%[0-9]+]]:vgpr_32 = V_BFE_U32_e64 internal $stg_srca, [[S_LSHL_B32_]], 16, implicit $exec
  ; REAL16-BUNDLE-NEXT:   }
  ; REAL16-BUNDLE-NEXT:   [[COPY:%[0-9]+]]:vgpr_16 = COPY [[V_BFE_U32_e64_]].lo16
  ; REAL16-BUNDLE-NEXT:   [[S_ADD_I32_1:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 4, 0, implicit-def dead $scc
  ; REAL16-BUNDLE-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_1]], 3, implicit-def dead $scc
  ; REAL16-BUNDLE-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_1]], 3, implicit-def dead $scc
  ; REAL16-BUNDLE-NEXT:   [[V_BFM_B32_e64_:%[0-9]+]]:vgpr_32 = V_BFM_B32_e64 16, [[S_LSHL_B32_1]], implicit $exec
  ; REAL16-BUNDLE-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[COPY]], %subreg.lo16, undef %32:vgpr_16, %subreg.hi16
  ; REAL16-BUNDLE-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_MOV_B32_]], implicit $exec, implicit [[V_BFM_B32_e64_]], implicit [[REG_SEQUENCE]] :: (load (s16) from %ir.p.2, align 4, addrspace 5), (store (s16) into %ir.p.2, align 4, addrspace 5) {
  ; REAL16-BUNDLE-NEXT:     $stg_srca = V_LOAD_IDX_B32 [[S_MOV_B32_]], 1, implicit $exec :: (load (s16) from %ir.p.2, align 4, addrspace 5)
  ; REAL16-BUNDLE-NEXT:     $stg_dsta = V_BFI_B32_e64 [[V_BFM_B32_e64_]], [[REG_SEQUENCE]], internal $stg_srca, implicit $exec
  ; REAL16-BUNDLE-NEXT:     V_STORE_IDX_B32 internal $stg_dsta, [[S_MOV_B32_]], 1, implicit $exec :: (store (s16) into %ir.p.2, align 4, addrspace 5)
  ; REAL16-BUNDLE-NEXT:   }
  ; REAL16-BUNDLE-NEXT:   [[S_ADD_I32_2:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 134, 0, implicit-def dead $scc
  ; REAL16-BUNDLE-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_2]], 3, implicit-def dead $scc
  ; REAL16-BUNDLE-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_2]], 3, implicit-def dead $scc
  ; REAL16-BUNDLE-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %35, implicit [[S_MOV_B32_]], implicit $exec, implicit [[S_LSHL_B32_2]] :: (load (s16) from %ir.q.1, align 4, addrspace 5) {
  ; REAL16-BUNDLE-NEXT:     $stg_srca = V_LOAD_IDX_B32 [[S_MOV_B32_]], 33, implicit $exec :: (load (s16) from %ir.q.1, align 4, addrspace 5)
  ; REAL16-BUNDLE-NEXT:     [[V_BFE_U32_e64_1:%[0-9]+]]:vgpr_32 = V_BFE_U32_e64 internal $stg_srca, [[S_LSHL_B32_2]], 16, implicit $exec
  ; REAL16-BUNDLE-NEXT:   }
  ; REAL16-BUNDLE-NEXT:   [[COPY1:%[0-9]+]]:vgpr_16 = COPY [[V_BFE_U32_e64_1]].lo16
  ; REAL16-BUNDLE-NEXT:   [[S_ADD_I32_3:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 136, 0, implicit-def dead $scc
  ; REAL16-BUNDLE-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_3]], 3, implicit-def dead $scc
  ; REAL16-BUNDLE-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_3]], 3, implicit-def dead $scc
  ; REAL16-BUNDLE-NEXT:   [[V_BFM_B32_e64_1:%[0-9]+]]:vgpr_32 = V_BFM_B32_e64 16, [[S_LSHL_B32_3]], implicit $exec
  ; REAL16-BUNDLE-NEXT:   [[REG_SEQUENCE1:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[COPY1]], %subreg.lo16, undef %39:vgpr_16, %subreg.hi16
  ; REAL16-BUNDLE-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit killed [[S_MOV_B32_]], implicit $exec, implicit [[V_BFM_B32_e64_1]], implicit [[REG_SEQUENCE1]] :: (load (s16) from %ir.q.2, align 4, addrspace 5), (store (s16) into %ir.q.2, align 4, addrspace 5) {
  ; REAL16-BUNDLE-NEXT:     $stg_srca = V_LOAD_IDX_B32 [[S_MOV_B32_]], 34, implicit $exec :: (load (s16) from %ir.q.2, align 4, addrspace 5)
  ; REAL16-BUNDLE-NEXT:     $stg_dsta = V_BFI_B32_e64 [[V_BFM_B32_e64_1]], [[REG_SEQUENCE1]], internal $stg_srca, implicit $exec
  ; REAL16-BUNDLE-NEXT:     V_STORE_IDX_B32 internal $stg_dsta, killed [[S_MOV_B32_]], 34, implicit $exec :: (store (s16) into %ir.q.2, align 4, addrspace 5)
  ; REAL16-BUNDLE-NEXT:   }
  ; REAL16-BUNDLE-NEXT:   S_ENDPGM 0
  ;
  ; REAL16-SETIDX-LABEL: name: subdword
  ; REAL16-SETIDX: bb.0.entry:
  ; REAL16-SETIDX-NEXT:   VGPR_LIFETIME_START :: (dereferenceable store (s1056) into %ir.q, align 1, addrspace 5)
  ; REAL16-SETIDX-NEXT:   VGPR_LIFETIME_START :: (dereferenceable store (s1056) into %ir.p, align 1, addrspace 5)
  ; REAL16-SETIDX-NEXT:   [[S_ADD_I32_:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 2, 0, implicit-def dead $scc
  ; REAL16-SETIDX-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_]], 3, implicit-def dead $scc
  ; REAL16-SETIDX-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_]], 3, implicit-def dead $scc
  ; REAL16-SETIDX-NEXT:   $idx1 = S_SET_GPR_IDX_U32 0
  ; REAL16-SETIDX-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %28, implicit $idx1, implicit $exec, implicit [[S_LSHL_B32_]] :: (load (s16) from %ir.p.1, align 4, addrspace 5) {
  ; REAL16-SETIDX-NEXT:     $stg_srca = V_LOAD_IDX_B32 $idx1, 0, implicit $exec :: (load (s16) from %ir.p.1, align 4, addrspace 5)
  ; REAL16-SETIDX-NEXT:     [[V_BFE_U32_e64_:%[0-9]+]]:vgpr_32 = V_BFE_U32_e64 internal $stg_srca, [[S_LSHL_B32_]], 16, implicit $exec
  ; REAL16-SETIDX-NEXT:   }
  ; REAL16-SETIDX-NEXT:   [[COPY:%[0-9]+]]:vgpr_16 = COPY [[V_BFE_U32_e64_]].lo16
  ; REAL16-SETIDX-NEXT:   [[S_ADD_I32_1:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 4, 0, implicit-def dead $scc
  ; REAL16-SETIDX-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_1]], 3, implicit-def dead $scc
  ; REAL16-SETIDX-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_1]], 3, implicit-def dead $scc
  ; REAL16-SETIDX-NEXT:   [[V_BFM_B32_e64_:%[0-9]+]]:vgpr_32 = V_BFM_B32_e64 16, [[S_LSHL_B32_1]], implicit $exec
  ; REAL16-SETIDX-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[COPY]], %subreg.lo16, undef %32:vgpr_16, %subreg.hi16
  ; REAL16-SETIDX-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx1, implicit $exec, implicit [[V_BFM_B32_e64_]], implicit [[REG_SEQUENCE]] :: (load (s16) from %ir.p.2, align 4, addrspace 5), (store (s16) into %ir.p.2, align 4, addrspace 5) {
  ; REAL16-SETIDX-NEXT:     $stg_srca = V_LOAD_IDX_B32 $idx1, 1, implicit $exec :: (load (s16) from %ir.p.2, align 4, addrspace 5)
  ; REAL16-SETIDX-NEXT:     $stg_dsta = V_BFI_B32_e64 [[V_BFM_B32_e64_]], [[REG_SEQUENCE]], internal $stg_srca, implicit $exec
  ; REAL16-SETIDX-NEXT:     V_STORE_IDX_B32 internal $stg_dsta, $idx1, 1, implicit $exec :: (store (s16) into %ir.p.2, align 4, addrspace 5)
  ; REAL16-SETIDX-NEXT:   }
  ; REAL16-SETIDX-NEXT:   [[S_ADD_I32_2:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 134, 0, implicit-def dead $scc
  ; REAL16-SETIDX-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_2]], 3, implicit-def dead $scc
  ; REAL16-SETIDX-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_2]], 3, implicit-def dead $scc
  ; REAL16-SETIDX-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %35, implicit $idx1, implicit $exec, implicit [[S_LSHL_B32_2]] :: (load (s16) from %ir.q.1, align 4, addrspace 5) {
  ; REAL16-SETIDX-NEXT:     $stg_srca = V_LOAD_IDX_B32 $idx1, 33, implicit $exec :: (load (s16) from %ir.q.1, align 4, addrspace 5)
  ; REAL16-SETIDX-NEXT:     [[V_BFE_U32_e64_1:%[0-9]+]]:vgpr_32 = V_BFE_U32_e64 internal $stg_srca, [[S_LSHL_B32_2]], 16, implicit $exec
  ; REAL16-SETIDX-NEXT:   }
  ; REAL16-SETIDX-NEXT:   [[COPY1:%[0-9]+]]:vgpr_16 = COPY [[V_BFE_U32_e64_1]].lo16
  ; REAL16-SETIDX-NEXT:   [[S_ADD_I32_3:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 136, 0, implicit-def dead $scc
  ; REAL16-SETIDX-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32_xm0_xexec = S_AND_B32 [[S_ADD_I32_3]], 3, implicit-def dead $scc
  ; REAL16-SETIDX-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xm0_xexec = S_LSHL_B32 [[S_AND_B32_3]], 3, implicit-def dead $scc
  ; REAL16-SETIDX-NEXT:   [[V_BFM_B32_e64_1:%[0-9]+]]:vgpr_32 = V_BFM_B32_e64 16, [[S_LSHL_B32_3]], implicit $exec
  ; REAL16-SETIDX-NEXT:   [[REG_SEQUENCE1:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[COPY1]], %subreg.lo16, undef %39:vgpr_16, %subreg.hi16
  ; REAL16-SETIDX-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit killed $idx1, implicit $exec, implicit [[V_BFM_B32_e64_1]], implicit [[REG_SEQUENCE1]] :: (load (s16) from %ir.q.2, align 4, addrspace 5), (store (s16) into %ir.q.2, align 4, addrspace 5) {
  ; REAL16-SETIDX-NEXT:     $stg_srca = V_LOAD_IDX_B32 $idx1, 34, implicit $exec :: (load (s16) from %ir.q.2, align 4, addrspace 5)
  ; REAL16-SETIDX-NEXT:     $stg_dsta = V_BFI_B32_e64 [[V_BFM_B32_e64_1]], [[REG_SEQUENCE1]], internal $stg_srca, implicit $exec
  ; REAL16-SETIDX-NEXT:     V_STORE_IDX_B32 internal $stg_dsta, killed $idx1, 34, implicit $exec :: (store (s16) into %ir.q.2, align 4, addrspace 5)
  ; REAL16-SETIDX-NEXT:   }
  ; REAL16-SETIDX-NEXT:   S_ENDPGM 0
entry:
  %p = alloca [66 x half], align 4, addrspace(5)
  %q = alloca [66 x half], align 4, addrspace(5)

  %p.1 = getelementptr half, ptr addrspace(5) %p, i64 1
  %v = load half, ptr addrspace(5) %p.1, align 4

  %p.2 = getelementptr half, ptr addrspace(5) %p, i64 2
  store half %v, ptr addrspace(5) %p.2, align 4

  %q.1 = getelementptr half, ptr addrspace(5) %q, i64 1
  %w = load half, ptr addrspace(5) %q.1, align 4

  %q.2 = getelementptr half, ptr addrspace(5) %q, i64 2
  store half %w, ptr addrspace(5) %q.2, align 4

  ret void
}

attributes #0 = { "amdgpu-flat-work-group-size"="32,32" }
