; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -verify-machineinstrs -passes=amdgpu-lower-module-lds -S -o - %s | FileCheck --check-prefixes=CHECK,GV %s

target datalayout = "A5"

@weights = hidden local_unnamed_addr addrspace(3) global <9 x i32> undef, align 64
@col_center = hidden local_unnamed_addr addrspace(3) global <3 x i32> undef, align 16
@col_left = hidden local_unnamed_addr addrspace(3) global <3 x i32> undef, align 16
@col_right = hidden local_unnamed_addr addrspace(3) global <3 x i32> undef, align 16
@out = hidden local_unnamed_addr addrspace(3) global <8 x i16> undef, align 16

; The LDS GVs above get packed into two structs, one module-level and one kernel-level, which are accessible from the specializations.

@sem1 = internal addrspace(3) global target("amdgcn.semaphore", 1) poison
@sem2 = internal addrspace(3) global target("amdgcn.semaphore", 2) poison

; Function Attrs: convergent nounwind
declare !callback !38 void @llvm.amdgcn.wavegroup.rank.p0(i32 immarg, ptr) #2

define private amdgpu_kernel void @input(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) #1 {
; CHECK-LABEL: define private amdgpu_kernel void @input(
; CHECK-SAME: ptr addrspace(1) [[INBUF:%.*]], ptr addrspace(1) [[WBUF:%.*]], ptr addrspace(1) [[OUTBUF:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VEC30:%.*]] = load <3 x i32>, ptr addrspace(1) [[INBUF]], align 16
; CHECK-NEXT:    [[LD_P1:%.*]] = getelementptr <3 x i32>, ptr addrspace(1) [[INBUF]], i64 16
; CHECK-NEXT:    [[VEC31:%.*]] = load <3 x i32>, ptr addrspace(1) [[LD_P1]], align 16
; CHECK-NEXT:    [[LD_P2:%.*]] = getelementptr <3 x i32>, ptr addrspace(1) [[INBUF]], i64 32
; CHECK-NEXT:    [[VEC32:%.*]] = load <3 x i32>, ptr addrspace(1) [[LD_P2]], align 16
; CHECK-NEXT:    [[WEI30:%.*]] = load <3 x i32>, ptr addrspace(1) [[WBUF]], align 64
; CHECK-NEXT:    [[W_P1:%.*]] = getelementptr <3 x i32>, ptr addrspace(1) [[WBUF]], i64 16
; CHECK-NEXT:    [[WEI31:%.*]] = load <3 x i32>, ptr addrspace(1) [[W_P1]], align 16
; CHECK-NEXT:    [[W_P2:%.*]] = getelementptr <3 x i32>, ptr addrspace(1) [[WBUF]], i64 32
; CHECK-NEXT:    [[WEI32:%.*]] = load <3 x i32>, ptr addrspace(1) [[W_P2]], align 16
; CHECK-NEXT:    store <3 x i32> [[VEC30]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, align 16
; CHECK-NEXT:    store <3 x i32> [[VEC31]], ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T:%.*]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 1), align 16
; CHECK-NEXT:    store <3 x i32> [[VEC32]], ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 2), align 16
; CHECK-NEXT:    store <3 x i32> [[WEI30]], ptr addrspace(3) @llvm.amdgcn.module.lds, align 64, !alias.scope [[META4:![0-9]+]], !noalias [[META7:![0-9]+]]
; CHECK-NEXT:    [[WEI_P1:%.*]] = getelementptr <3 x i32>, ptr addrspace(3) @llvm.amdgcn.module.lds, i64 12
; CHECK-NEXT:    store <3 x i32> [[WEI31]], ptr addrspace(3) [[WEI_P1]], align 64, !alias.scope [[META4]], !noalias [[META7]]
; CHECK-NEXT:    [[WEI_P2:%.*]] = getelementptr <3 x i32>, ptr addrspace(3) @llvm.amdgcn.module.lds, i64 24
; CHECK-NEXT:    store <3 x i32> [[WEI32]], ptr addrspace(3) [[WEI_P2]], align 64, !alias.scope [[META4]], !noalias [[META7]]
; CHECK-NEXT:    call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_MODULE_LDS_T:%.*]], ptr addrspace(3) @llvm.amdgcn.module.lds, i32 0, i32 1)), !alias.scope [[META13:![0-9]+]], !noalias [[META14:![0-9]+]]
; CHECK-NEXT:    ret void
;
entry:
  %vec30 = load <3 x i32>, ptr addrspace(1) %inbuf, align 16
  %ld.p1 = getelementptr <3 x i32>, ptr addrspace(1) %inbuf, i64 16
  %vec31 = load <3 x i32>, ptr addrspace(1) %ld.p1, align 16
  %ld.p2 = getelementptr <3 x i32>, ptr addrspace(1) %inbuf, i64 32
  %vec32 = load <3 x i32>, ptr addrspace(1) %ld.p2, align 16

  %wei30 = load <3 x i32>, ptr addrspace(1) %wbuf, align 64
  %w.p1 = getelementptr <3 x i32>, ptr addrspace(1) %wbuf, i64 16
  %wei31 = load <3 x i32>, ptr addrspace(1) %w.p1, align 16
  %w.p2 = getelementptr <3 x i32>, ptr addrspace(1) %wbuf, i64 32
  %wei32 = load <3 x i32>, ptr addrspace(1) %w.p2, align 16

  store <3 x i32> %vec30, ptr addrspace(3) @col_center, align 16
  store <3 x i32> %vec31, ptr addrspace(3) @col_left, align 16
  store <3 x i32> %vec32, ptr addrspace(3) @col_right, align 16

  store <3 x i32> %wei30, ptr addrspace(3) @weights, align 64
  %wei.p1 = getelementptr <3 x i32>, ptr addrspace(3) @weights, i64 12
  store <3 x i32> %wei31, ptr addrspace(3) %wei.p1, align 64
  %wei.p2 = getelementptr <3 x i32>, ptr addrspace(3) @weights, i64 24
  store <3 x i32> %wei32, ptr addrspace(3) %wei.p2, align 64

  call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) @sem1)
  ret void
}

define private amdgpu_kernel void @compute(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) #1 {
; CHECK-LABEL: define private amdgpu_kernel void @compute(
; CHECK-SAME: ptr addrspace(1) [[INBUF:%.*]], ptr addrspace(1) [[WBUF:%.*]], ptr addrspace(1) [[OUTBUF:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_MODULE_LDS_T:%.*]], ptr addrspace(3) @llvm.amdgcn.module.lds, i32 0, i32 1)), !alias.scope [[META13]], !noalias [[META14]]
; CHECK-NEXT:    [[VEC30:%.*]] = load <3 x i32>, ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, align 16
; CHECK-NEXT:    [[VEC31:%.*]] = load <3 x i32>, ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T:%.*]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 1), align 16
; CHECK-NEXT:    [[VEC32:%.*]] = load <3 x i32>, ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 2), align 16
; CHECK-NEXT:    [[WEI:%.*]] = load <9 x i32>, ptr addrspace(3) @llvm.amdgcn.module.lds, align 64, !alias.scope [[META4]], !noalias [[META7]]
; CHECK-NEXT:    [[TMP0:%.*]] = tail call contract <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> zeroinitializer, <9 x i32> [[WEI]], <3 x i32> [[VEC30]], <3 x i32> [[VEC31]], <3 x i32> [[VEC32]], i32 42, i1 true)
; CHECK-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 3), align 16, !tbaa [[TBAA17:![0-9]+]]
; CHECK-NEXT:    call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 4))
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sem1)
  %vec30 = load <3 x i32>, ptr addrspace(3) @col_center, align 16
  %vec31 = load <3 x i32>, ptr addrspace(3) @col_left, align 16
  %vec32 = load <3 x i32>, ptr addrspace(3) @col_right, align 16
  %wei = load <9 x i32>, ptr addrspace(3) @weights, align 64
  %0 = tail call contract <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> zeroinitializer, <9 x i32> %wei, <3 x i32> %vec30, <3 x i32> %vec31, <3 x i32> %vec32, i32 42, i1 true)
  store <8 x half> %0, ptr addrspace(3) @out, align 16, !tbaa !4
  call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) @sem2)
  ret void
}

define private amdgpu_kernel void @output(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) #1 {
; CHECK-LABEL: define private amdgpu_kernel void @output(
; CHECK-SAME: ptr addrspace(1) [[INBUF:%.*]], ptr addrspace(1) [[WBUF:%.*]], ptr addrspace(1) [[OUTBUF:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T:%.*]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 4))
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x half>, ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 3), align 16
; CHECK-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUTBUF]], align 16
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sem2)
  %0 = load <8 x half>, ptr addrspace(3) @out, align 16
  store <8 x half> %0, ptr addrspace(1) %outbuf, align 16
  ret void
}

; Function Attrs: convergent mustprogress nofree norecurse nosync nounwind memory(readwrite, argmem: none, inaccessiblemem: none)
define amdgpu_kernel void @main(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) !reqd_work_group_size !{i32 32, i32 12, i32 1} {
; CHECK-LABEL: define amdgpu_kernel void @main(
; CHECK-SAME: ptr addrspace(1) [[INBUF:%.*]], ptr addrspace(1) [[WBUF:%.*]], ptr addrspace(1) [[OUTBUF:%.*]]) #[[ATTR2:[0-9]+]] !reqd_work_group_size [[META20:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.donothing() [ "ExplicitUse"(ptr addrspace(3) @llvm.amdgcn.kernel.main.lds) ], !alias.scope [[META21:![0-9]+]], !noalias [[META24:![0-9]+]]
; CHECK-NEXT:    call void @llvm.donothing() [ "ExplicitUse"(ptr addrspace(3) @llvm.amdgcn.module.lds) ], !alias.scope [[META4]], !noalias [[META13]]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr @input)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 1, ptr @compute)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 2, ptr @output)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.amdgcn.wavegroup.rank(i32 0, ptr @input)
  call void @llvm.amdgcn.wavegroup.rank(i32 1, ptr @compute)
  call void @llvm.amdgcn.wavegroup.rank(i32 2, ptr @output)
  ret void
}


; Rank specialization example below tests the case where there is another kernel in the module that uses the same addrspace(3) GVs, in which case those
; GVs get lowered using the module-scope strategy in the amdgpu-lower-module-lds pass.
define private amdgpu_kernel void @input_kern2(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) #1 {
; CHECK-LABEL: define private amdgpu_kernel void @input_kern2(
; CHECK-SAME: ptr addrspace(1) [[INBUF:%.*]], ptr addrspace(1) [[WBUF:%.*]], ptr addrspace(1) [[OUTBUF:%.*]]) #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[IN:%.*]] = load <3 x i32>, ptr addrspace(1) [[INBUF]], align 16
; CHECK-NEXT:    [[W:%.*]] = load <3 x i32>, ptr addrspace(1) [[WBUF]], align 64
; CHECK-NEXT:    [[VEC:%.*]] = add <3 x i32> [[W]], [[IN]]
; CHECK-NEXT:    store <3 x i32> [[VEC]], ptr addrspace(3) @llvm.amdgcn.module.lds, align 64, !alias.scope [[META4]], !noalias [[META7]]
; CHECK-NEXT:    call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_MODULE_LDS_T:%.*]], ptr addrspace(3) @llvm.amdgcn.module.lds, i32 0, i32 1)), !alias.scope [[META13]], !noalias [[META14]]
; CHECK-NEXT:    ret void
;
entry:
  %in = load <3 x i32>, ptr addrspace(1) %inbuf, align 16
  %w = load <3 x i32>, ptr addrspace(1) %wbuf, align 64
  %vec = add <3 x i32> %w, %in

  store <3 x i32> %vec, ptr addrspace(3) @weights, align 64

  call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) @sem1)
  ret void
}

define amdgpu_kernel void @kern2(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) !reqd_work_group_size !{i32 32, i32 12, i32 1} {
; CHECK-LABEL: define amdgpu_kernel void @kern2(
; CHECK-SAME: ptr addrspace(1) [[INBUF:%.*]], ptr addrspace(1) [[WBUF:%.*]], ptr addrspace(1) [[OUTBUF:%.*]]) #[[ATTR4:[0-9]+]] !reqd_work_group_size [[META20]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.donothing() [ "ExplicitUse"(ptr addrspace(3) @llvm.amdgcn.module.lds) ]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr @input_kern2)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr @input_kern2)
  ret void
}

attributes #1 = { "amdgpu-wavegroup-rank-function" }
attributes #2 = { convergent nounwind }

; Check that LDS propogates to rank specializations and that it matches the kernel entry functions.
; LDS Size 128 for main's rank specializations:
; ... and for main:
; LDS Size 128 for kern2's rank specializations:
; ... and for input_kern2:

!4 = !{!5, !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}
!38 = !{!39}
!39 = !{i64 1, i1 false}

;.
; CHECK: [[META4]] = !{[[META5:![0-9]+]]}
; CHECK: [[META5]] = distinct !{[[META5]], [[META6:![0-9]+]]}
; CHECK: [[META6]] = distinct !{[[META6]]}
; CHECK: [[META7]] = !{[[META8:![0-9]+]], [[META10:![0-9]+]], [[META12:![0-9]+]]}
; CHECK: [[META8]] = distinct !{[[META8]], [[META9:![0-9]+]]}
; CHECK: [[META9]] = distinct !{[[META9]]}
; CHECK: [[META10]] = distinct !{[[META10]], [[META11:![0-9]+]]}
; CHECK: [[META11]] = distinct !{[[META11]]}
; CHECK: [[META12]] = distinct !{[[META12]], [[META6]]}
; CHECK: [[META13]] = !{[[META12]]}
; CHECK: [[META14]] = !{[[META15:![0-9]+]], [[META16:![0-9]+]], [[META5]]}
; CHECK: [[META15]] = distinct !{[[META15]], [[META9]]}
; CHECK: [[META16]] = distinct !{[[META16]], [[META11]]}
; CHECK: [[TBAA17]] = !{[[META18:![0-9]+]], [[META18]], i64 0}
; CHECK: [[META18]] = !{!"omnipotent char", [[META19:![0-9]+]], i64 0}
; CHECK: [[META19]] = !{!"Simple C++ TBAA"}
; CHECK: [[META20]] = !{i32 32, i32 12, i32 1}
; CHECK: [[META21]] = !{[[META22:![0-9]+]]}
; CHECK: [[META22]] = distinct !{[[META22]], [[META23:![0-9]+]]}
; CHECK: [[META23]] = distinct !{[[META23]]}
; CHECK: [[META24]] = !{[[META25:![0-9]+]], [[META26:![0-9]+]], [[META27:![0-9]+]], [[META28:![0-9]+]]}
; CHECK: [[META25]] = distinct !{[[META25]], [[META23]]}
; CHECK: [[META26]] = distinct !{[[META26]], [[META23]]}
; CHECK: [[META27]] = distinct !{[[META27]], [[META23]]}
; CHECK: [[META28]] = distinct !{[[META28]], [[META23]]}
;.
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; GV: {{.*}}
