; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-attributes --check-globals all --version 5
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -verify-machineinstrs -passes=amdgpu-lower-exec-sync,amdgpu-lower-module-lds -S -o - %s \
; RUN:   | FileCheck --check-prefixes=CHECK %s

target datalayout = "A5"

; These LDS GVs get packed into two structs, one module-level and one kernel-level, which are accessible from the specializations.
@weights = hidden local_unnamed_addr addrspace(3) global <9 x i32> undef, align 64
@col_center = hidden local_unnamed_addr addrspace(3) global <3 x i32> undef, align 16
@col_left = hidden local_unnamed_addr addrspace(3) global <3 x i32> undef, align 16
@col_right = hidden local_unnamed_addr addrspace(3) global <3 x i32> undef, align 16
@out = hidden local_unnamed_addr addrspace(3) global <8 x i16> undef, align 16

; Semaphores are assigned absolute addresses during amdgpu-lower-exec-sync
@sem1 = internal addrspace(3) global target("amdgcn.semaphore", 1) poison
@sem2 = internal addrspace(3) global target("amdgcn.semaphore", 2) poison

; Function Attrs: convergent nounwind
declare !callback !38 void @llvm.amdgcn.wavegroup.rank.p0(i32 immarg, ptr) #2

;.
; CHECK: @sem1 = internal addrspace(3) global target("amdgcn.semaphore", 1) poison, !absolute_symbol [[META0:![0-9]+]]
; CHECK: @sem2 = internal addrspace(3) global target("amdgcn.semaphore", 2) poison, !absolute_symbol [[META1:![0-9]+]]
; CHECK: @llvm.amdgcn.module.lds = internal addrspace(3) global %llvm.amdgcn.module.lds.t poison, align 64, !absolute_symbol [[META2:![0-9]+]]
; CHECK: @llvm.compiler.used = appending global [1 x ptr] [ptr addrspacecast (ptr addrspace(3) @llvm.amdgcn.module.lds to ptr)], section "llvm.metadata"
; CHECK: @llvm.amdgcn.kernel.main.lds = internal addrspace(3) global %llvm.amdgcn.kernel.main.lds.t poison, align 16, !absolute_symbol [[META3:![0-9]+]]
;.
define private amdgpu_kernel void @input(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) #1 {
; CHECK-LABEL: define private amdgpu_kernel void @input(
; CHECK-SAME: ptr addrspace(1) [[INBUF:%.*]], ptr addrspace(1) [[WBUF:%.*]], ptr addrspace(1) [[OUTBUF:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VEC30:%.*]] = load <3 x i32>, ptr addrspace(1) [[INBUF]], align 16
; CHECK-NEXT:    [[LD_P1:%.*]] = getelementptr <3 x i32>, ptr addrspace(1) [[INBUF]], i64 16
; CHECK-NEXT:    [[VEC31:%.*]] = load <3 x i32>, ptr addrspace(1) [[LD_P1]], align 16
; CHECK-NEXT:    [[LD_P2:%.*]] = getelementptr <3 x i32>, ptr addrspace(1) [[INBUF]], i64 32
; CHECK-NEXT:    [[VEC32:%.*]] = load <3 x i32>, ptr addrspace(1) [[LD_P2]], align 16
; CHECK-NEXT:    [[WEI30:%.*]] = load <3 x i32>, ptr addrspace(1) [[WBUF]], align 64
; CHECK-NEXT:    [[W_P1:%.*]] = getelementptr <3 x i32>, ptr addrspace(1) [[WBUF]], i64 16
; CHECK-NEXT:    [[WEI31:%.*]] = load <3 x i32>, ptr addrspace(1) [[W_P1]], align 16
; CHECK-NEXT:    [[W_P2:%.*]] = getelementptr <3 x i32>, ptr addrspace(1) [[WBUF]], i64 32
; CHECK-NEXT:    [[WEI32:%.*]] = load <3 x i32>, ptr addrspace(1) [[W_P2]], align 16
; CHECK-NEXT:    store <3 x i32> [[VEC30]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, align 16
; CHECK-NEXT:    store <3 x i32> [[VEC31]], ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T:%.*]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 1), align 16
; CHECK-NEXT:    store <3 x i32> [[VEC32]], ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 2), align 16
; CHECK-NEXT:    store <3 x i32> [[WEI30]], ptr addrspace(3) @llvm.amdgcn.module.lds, align 64
; CHECK-NEXT:    [[WEI_P1:%.*]] = getelementptr <3 x i32>, ptr addrspace(3) @llvm.amdgcn.module.lds, i64 12
; CHECK-NEXT:    store <3 x i32> [[WEI31]], ptr addrspace(3) [[WEI_P1]], align 64
; CHECK-NEXT:    [[WEI_P2:%.*]] = getelementptr <3 x i32>, ptr addrspace(3) @llvm.amdgcn.module.lds, i64 24
; CHECK-NEXT:    store <3 x i32> [[WEI32]], ptr addrspace(3) [[WEI_P2]], align 64
; CHECK-NEXT:    call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) @sem1, i32 poison)
; CHECK-NEXT:    ret void
;
entry:
  %vec30 = load <3 x i32>, ptr addrspace(1) %inbuf, align 16
  %ld.p1 = getelementptr <3 x i32>, ptr addrspace(1) %inbuf, i64 16
  %vec31 = load <3 x i32>, ptr addrspace(1) %ld.p1, align 16
  %ld.p2 = getelementptr <3 x i32>, ptr addrspace(1) %inbuf, i64 32
  %vec32 = load <3 x i32>, ptr addrspace(1) %ld.p2, align 16

  %wei30 = load <3 x i32>, ptr addrspace(1) %wbuf, align 64
  %w.p1 = getelementptr <3 x i32>, ptr addrspace(1) %wbuf, i64 16
  %wei31 = load <3 x i32>, ptr addrspace(1) %w.p1, align 16
  %w.p2 = getelementptr <3 x i32>, ptr addrspace(1) %wbuf, i64 32
  %wei32 = load <3 x i32>, ptr addrspace(1) %w.p2, align 16

  store <3 x i32> %vec30, ptr addrspace(3) @col_center, align 16
  store <3 x i32> %vec31, ptr addrspace(3) @col_left, align 16
  store <3 x i32> %vec32, ptr addrspace(3) @col_right, align 16

  store <3 x i32> %wei30, ptr addrspace(3) @weights, align 64
  %wei.p1 = getelementptr <3 x i32>, ptr addrspace(3) @weights, i64 12
  store <3 x i32> %wei31, ptr addrspace(3) %wei.p1, align 64
  %wei.p2 = getelementptr <3 x i32>, ptr addrspace(3) @weights, i64 24
  store <3 x i32> %wei32, ptr addrspace(3) %wei.p2, align 64

  call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) @sem1, i32 poison)
  ret void
}

define private amdgpu_kernel void @compute(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) #1 {
; CHECK-LABEL: define private amdgpu_kernel void @compute(
; CHECK-SAME: ptr addrspace(1) [[INBUF:%.*]], ptr addrspace(1) [[WBUF:%.*]], ptr addrspace(1) [[OUTBUF:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sem1)
; CHECK-NEXT:    [[VEC30:%.*]] = load <3 x i32>, ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, align 16
; CHECK-NEXT:    [[VEC31:%.*]] = load <3 x i32>, ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T:%.*]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 1), align 16
; CHECK-NEXT:    [[VEC32:%.*]] = load <3 x i32>, ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 2), align 16
; CHECK-NEXT:    [[WEI:%.*]] = load <9 x i32>, ptr addrspace(3) @llvm.amdgcn.module.lds, align 64
; CHECK-NEXT:    [[TMP0:%.*]] = tail call contract <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> zeroinitializer, <9 x i32> [[WEI]], <3 x i32> [[VEC30]], <3 x i32> [[VEC31]], <3 x i32> [[VEC32]], i32 42, i1 true)
; CHECK-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 3), align 16, !tbaa [[TBAA6:![0-9]+]]
; CHECK-NEXT:    call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) @sem2, i32 poison)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sem1)
  %vec30 = load <3 x i32>, ptr addrspace(3) @col_center, align 16
  %vec31 = load <3 x i32>, ptr addrspace(3) @col_left, align 16
  %vec32 = load <3 x i32>, ptr addrspace(3) @col_right, align 16
  %wei = load <9 x i32>, ptr addrspace(3) @weights, align 64
  %0 = tail call contract <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> zeroinitializer, <9 x i32> %wei, <3 x i32> %vec30, <3 x i32> %vec31, <3 x i32> %vec32, i32 42, i1 true)
  store <8 x half> %0, ptr addrspace(3) @out, align 16, !tbaa !4
  call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) @sem2, i32 poison)
  ret void
}

define private amdgpu_kernel void @output(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) #1 {
; CHECK-LABEL: define private amdgpu_kernel void @output(
; CHECK-SAME: ptr addrspace(1) [[INBUF:%.*]], ptr addrspace(1) [[WBUF:%.*]], ptr addrspace(1) [[OUTBUF:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sem2)
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x half>, ptr addrspace(3) getelementptr inbounds ([[LLVM_AMDGCN_KERNEL_MAIN_LDS_T:%.*]], ptr addrspace(3) @llvm.amdgcn.kernel.main.lds, i32 0, i32 3), align 16
; CHECK-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUTBUF]], align 16
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sem2)
  %0 = load <8 x half>, ptr addrspace(3) @out, align 16
  store <8 x half> %0, ptr addrspace(1) %outbuf, align 16
  ret void
}

; Function Attrs: convergent mustprogress nofree norecurse nosync nounwind memory(readwrite, argmem: none, inaccessiblemem: none)
define amdgpu_kernel void @main(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) !reqd_work_group_size !{i32 32, i32 12, i32 1} {
; CHECK-LABEL: define amdgpu_kernel void @main(
; CHECK-SAME: ptr addrspace(1) [[INBUF:%.*]], ptr addrspace(1) [[WBUF:%.*]], ptr addrspace(1) [[OUTBUF:%.*]]) #[[ATTR2:[0-9]+]] !reqd_work_group_size [[META9:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.donothing() [ "ExplicitUse"(ptr addrspace(3) @llvm.amdgcn.kernel.main.lds) ], !alias.scope [[META10:![0-9]+]], !noalias [[META13:![0-9]+]]
; CHECK-NEXT:    call void @llvm.donothing() [ "ExplicitUse"(ptr addrspace(3) @llvm.amdgcn.module.lds) ]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr @input)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 1, ptr @compute)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 2, ptr @output)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.amdgcn.wavegroup.rank(i32 0, ptr @input)
  call void @llvm.amdgcn.wavegroup.rank(i32 1, ptr @compute)
  call void @llvm.amdgcn.wavegroup.rank(i32 2, ptr @output)
  ret void
}


; Rank specialization example below tests the case where there is another kernel in the module that uses the same addrspace(3) GVs, in which case those
; GVs get lowered using the module-scope strategy in the amdgpu-lower-module-lds pass.
define private amdgpu_kernel void @input_kern2(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) #1 {
; CHECK-LABEL: define private amdgpu_kernel void @input_kern2(
; CHECK-SAME: ptr addrspace(1) [[INBUF:%.*]], ptr addrspace(1) [[WBUF:%.*]], ptr addrspace(1) [[OUTBUF:%.*]]) #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[IN:%.*]] = load <3 x i32>, ptr addrspace(1) [[INBUF]], align 16
; CHECK-NEXT:    [[W:%.*]] = load <3 x i32>, ptr addrspace(1) [[WBUF]], align 64
; CHECK-NEXT:    [[VEC:%.*]] = add <3 x i32> [[W]], [[IN]]
; CHECK-NEXT:    store <3 x i32> [[VEC]], ptr addrspace(3) @llvm.amdgcn.module.lds, align 64
; CHECK-NEXT:    call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) @sem1, i32 poison)
; CHECK-NEXT:    ret void
;
entry:
  %in = load <3 x i32>, ptr addrspace(1) %inbuf, align 16
  %w = load <3 x i32>, ptr addrspace(1) %wbuf, align 64
  %vec = add <3 x i32> %w, %in

  store <3 x i32> %vec, ptr addrspace(3) @weights, align 64

  call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) @sem1, i32 poison)
  ret void
}

define amdgpu_kernel void @kern2(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) !reqd_work_group_size !{i32 32, i32 12, i32 1} {
; CHECK-LABEL: define amdgpu_kernel void @kern2(
; CHECK-SAME: ptr addrspace(1) [[INBUF:%.*]], ptr addrspace(1) [[WBUF:%.*]], ptr addrspace(1) [[OUTBUF:%.*]]) #[[ATTR4:[0-9]+]] !reqd_work_group_size [[META9]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.donothing() [ "ExplicitUse"(ptr addrspace(3) @llvm.amdgcn.module.lds) ]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr @input_kern2)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr @input_kern2)
  ret void
}

attributes #1 = { "amdgpu-wavegroup-rank-function" }
attributes #2 = { convergent nounwind }

; Check that LDS propogates to rank specializations and that it matches the kernel entry functions.
; LDS Size 128 for main's rank specializations:
; ... and for main:
; LDS Size 128 for kern2's rank specializations:
; ... and for input_kern2:

!4 = !{!5, !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}
!38 = !{!39}
!39 = !{i64 1, i1 false}

;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { convergent nounwind "target-cpu"="gfx1300" }
; CHECK: attributes #[[ATTR1]] = { "amdgpu-lds-size"="128" "amdgpu-wavegroup-rank-function" "target-cpu"="gfx1300" }
; CHECK: attributes #[[ATTR2]] = { "amdgpu-lds-size"="128" "target-cpu"="gfx1300" }
; CHECK: attributes #[[ATTR3]] = { "amdgpu-lds-size"="64" "amdgpu-wavegroup-rank-function" "target-cpu"="gfx1300" }
; CHECK: attributes #[[ATTR4]] = { "amdgpu-lds-size"="64" "target-cpu"="gfx1300" }
; CHECK: attributes #[[ATTR5:[0-9]+]] = { convergent nocallback nofree nosync nounwind willreturn memory(none) "target-cpu"="gfx1300" }
; CHECK: attributes #[[ATTR6:[0-9]+]] = { convergent nocallback nofree nounwind willreturn "target-cpu"="gfx1300" }
; CHECK: attributes #[[ATTR7:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(none) }
;.
; CHECK: [[META0]] = !{i64 8392976, i64 8392977}
; CHECK: [[META1]] = !{i64 8393232, i64 8393233}
; CHECK: [[META2]] = !{i64 0, i64 1}
; CHECK: [[META3]] = !{i64 64, i64 65}
; CHECK: [[META4:![0-9]+]] = !{[[META5:![0-9]+]]}
; CHECK: [[META5]] = !{i64 1, i1 false}
; CHECK: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
; CHECK: [[META7]] = !{!"omnipotent char", [[META8:![0-9]+]], i64 0}
; CHECK: [[META8]] = !{!"Simple C++ TBAA"}
; CHECK: [[META9]] = !{i32 32, i32 12, i32 1}
; CHECK: [[META10]] = !{[[META11:![0-9]+]]}
; CHECK: [[META11]] = distinct !{[[META11]], [[META12:![0-9]+]]}
; CHECK: [[META12]] = distinct !{[[META12]]}
; CHECK: [[META13]] = !{[[META14:![0-9]+]], [[META15:![0-9]+]], [[META16:![0-9]+]]}
; CHECK: [[META14]] = distinct !{[[META14]], [[META12]]}
; CHECK: [[META15]] = distinct !{[[META15]], [[META12]]}
; CHECK: [[META16]] = distinct !{[[META16]], [[META12]]}
;.
