; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -stop-after=machine-scheduler --misched-prera-direction=topdown -verify-machineinstrs %s -o - | FileCheck %s

; This test should form two convolution bundles, they share some sources but not share dest.
; Therefore, they should be independent to each other. False memory dependence can prevent
; the 2nd convolution from scheduling into the gap between the global-load and the 1st
; convolution.


target datalayout = "A5"

@weights = external local_unnamed_addr addrspace(10) global <9 x i32>, align 64
@col_center = external local_unnamed_addr addrspace(10) global <3 x i32>, align 16
@col_right = external local_unnamed_addr addrspace(10) global <3 x i32>, align 16
@out = external local_unnamed_addr addrspace(10) global <8 x i16>, align 16
@col_right2 = external local_unnamed_addr addrspace(10) global <3 x i32>, align 16
@out2 = external local_unnamed_addr addrspace(10) global <8 x i16>, align 16

; Function Attrs: convergent mustprogress nofree norecurse nosync nounwind memory(readwrite, argmem: none, inaccessiblemem: none)
define amdgpu_kernel void @two_convolve_f16_fp8_3x3_4x4v(ptr addrspace(1) %col_left) "amdgpu-wavegroup-enable" !reqd_work_group_size !{i32 32, i32 12, i32 1} {

  ; CHECK-LABEL: name: two_convolve_f16_fp8_3x3_4x4v
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $sgpr4_sgpr5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:sgpr_64(p4) = COPY $sgpr4_sgpr5
  ; CHECK-NEXT:   $idx1 = S_SET_GPR_IDX_U32 0
  ; CHECK-NEXT:   [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[COPY]](p4), 0, 0 :: (dereferenceable invariant load (s64) from %ir.col_left.kernarg.offset1, align 16, addrspace 4)
  ; CHECK-NEXT:   BUNDLE implicit-def dead $stg_srcd, implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def dead $stg_dsta, implicit $idx1, implicit $exec :: (dereferenceable load (s96) from @col_right2, align 16, addrspace 10), (dereferenceable load (s96) from @col_center, align 32, addrspace 10), (dereferenceable load (s96) from @col_right, align 16, addrspace 10), (dereferenceable load (s288) from @weights, align 268435456, addrspace 10), (store (s128) into @out2, align 32, !tbaa !9, addrspace 10) {
  ; CHECK-NEXT:     $stg_srcd = V_LOAD_IDX_B96 $idx1, 22, implicit $exec :: (dereferenceable load (s96) from @col_right2, align 16, addrspace 10)
  ; CHECK-NEXT:     $stg_srcc = V_LOAD_IDX_B96 $idx1, 10, implicit $exec :: (dereferenceable load (s96) from @col_center, align 32, addrspace 10)
  ; CHECK-NEXT:     $stg_srcb = V_LOAD_IDX_B96 $idx1, 14, implicit $exec :: (dereferenceable load (s96) from @col_right, align 16, addrspace 10)
  ; CHECK-NEXT:     $stg_srca = V_LOAD_IDX_B288 $idx1, 0, implicit $exec :: (dereferenceable load (s288) from @weights, align 268435456, addrspace 10)
  ; CHECK-NEXT:     $stg_dsta = contract V_CONVOLVE_F16_FP8_FP8_3x3_4x4 0, internal $stg_srca, internal $stg_srcb, internal $stg_srcc, internal $stg_srcd, 42, -1, 0, 0, implicit $exec
  ; CHECK-NEXT:     V_STORE_IDX_B128 internal $stg_dsta, $idx1, 26, implicit $exec :: (store (s128) into @out2, align 32, !tbaa !9, addrspace 10)
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[S_LOAD_DWORDX3_IMM:%[0-9]+]]:sgpr_96 = S_LOAD_DWORDX3_IMM [[S_LOAD_DWORDX2_IMM]], 0, 0 :: ("amdgpu-noclobber" load (s96) from %ir.col_left.load, align 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:vreg_96 = COPY [[S_LOAD_DWORDX3_IMM]]
  ; CHECK-NEXT:   BUNDLE implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def dead $stg_dsta, implicit $idx1, implicit $exec, implicit [[COPY1]] :: (dereferenceable load (s96) from @col_right, align 16, addrspace 10), (dereferenceable load (s96) from @col_center, align 32, addrspace 10), (dereferenceable load (s288) from @weights, align 268435456, addrspace 10), (store (s128) into @out, align 64, !tbaa !9, addrspace 10) {
  ; CHECK-NEXT:     $stg_srcc = V_LOAD_IDX_B96 $idx1, 14, implicit $exec :: (dereferenceable load (s96) from @col_right, align 16, addrspace 10)
  ; CHECK-NEXT:     $stg_srcb = V_LOAD_IDX_B96 $idx1, 10, implicit $exec :: (dereferenceable load (s96) from @col_center, align 32, addrspace 10)
  ; CHECK-NEXT:     $stg_srca = V_LOAD_IDX_B288 $idx1, 0, implicit $exec :: (dereferenceable load (s288) from @weights, align 268435456, addrspace 10)
  ; CHECK-NEXT:     $stg_dsta = contract V_CONVOLVE_F16_FP8_FP8_3x3_4x4 0, internal $stg_srca, internal $stg_srcb, [[COPY1]], internal $stg_srcc, 42, -1, 0, 0, implicit $exec
  ; CHECK-NEXT:     V_STORE_IDX_B128 internal $stg_dsta, $idx1, 18, implicit $exec :: (store (s128) into @out, align 64, !tbaa !9, addrspace 10)
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   S_ENDPGM 0
entry:
  %vec30 = load <3 x i32>, ptr addrspace(10) @col_center, align 16
  %vec31 = load <3 x i32>, ptr addrspace(1) %col_left, align 16
  %vec32 = load <3 x i32>, ptr addrspace(10) @col_right, align 16
  %wei = load <9 x i32>, ptr addrspace(10) @weights, align 64
  %0 = tail call contract <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> zeroinitializer, <9 x i32> %wei, <3 x i32> %vec30, <3 x i32> %vec31, <3 x i32> %vec32, i32 42, i1 true)
  store <8 x half> %0, ptr addrspace(10) @out, align 16, !tbaa !4
  %vec33 = load <3 x i32>, ptr addrspace(10) @col_right2, align 16
  %1 = tail call contract <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> zeroinitializer, <9 x i32> %wei, <3 x i32> %vec32, <3 x i32> %vec30, <3 x i32> %vec33, i32 42, i1 true)
  store <8 x half> %1, ptr addrspace(10) @out2, align 16, !tbaa !4
  ret void
}

; Function Attrs: convergent mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half>, <9 x i32>, <3 x i32>, <3 x i32>, <3 x i32>, i32 immarg, i1 immarg) #1

!4 = !{!5, !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}
