; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=amdgpu9.00-amd-amdhsa -passes=slp-vectorizer < %s | llc -mtriple=amdgpu9.00-amd-amdhsa | FileCheck -check-prefix=GFX900 %s
; RUN: opt -mtriple=amdgpu9.0a-amd-amdhsa -passes=slp-vectorizer < %s | llc -mtriple=amdgpu9.0a-amd-amdhsa | FileCheck -check-prefix=GFX90A %s
; RUN: opt -mtriple=amdgpu11.00-amd-amdhsa -passes=slp-vectorizer < %s | llc -mtriple=amdgpu11.00-amd-amdhsa | FileCheck -check-prefix=GFX1100 %s
; RUN: opt -mtriple=amdgpu12.50-amd-amdhsa -passes=slp-vectorizer < %s | llc -mtriple=amdgpu12.50-amd-amdhsa | FileCheck -check-prefix=GFX1250 %s

define void @sitofp_i8_to_double(ptr addrspace(1) noalias %out, ptr addrspace(1) noalias %in) {
  %x0 = load i8, ptr addrspace(1) %in, align 1
  %c0 = sitofp i8 %x0 to double
  store double %c0, ptr addrspace(1) %out, align 8
  %in.1 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 1
  %x1 = load i8, ptr addrspace(1) %in.1, align 1
  %c1 = sitofp i8 %x1 to double
  %out.1 = getelementptr inbounds double, ptr addrspace(1) %out, i64 1
  store double %c1, ptr addrspace(1) %out.1, align 8
  %in.2 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 2
  %x2 = load i8, ptr addrspace(1) %in.2, align 1
  %c2 = sitofp i8 %x2 to double
  %out.2 = getelementptr inbounds double, ptr addrspace(1) %out, i64 2
  store double %c2, ptr addrspace(1) %out.2, align 8
  %in.3 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 3
  %x3 = load i8, ptr addrspace(1) %in.3, align 1
  %c3 = sitofp i8 %x3 to double
  %out.3 = getelementptr inbounds double, ptr addrspace(1) %out, i64 3
  store double %c3, ptr addrspace(1) %out.3, align 8
  %in.4 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 4
  %x4 = load i8, ptr addrspace(1) %in.4, align 1
  %c4 = sitofp i8 %x4 to double
  %out.4 = getelementptr inbounds double, ptr addrspace(1) %out, i64 4
  store double %c4, ptr addrspace(1) %out.4, align 8
  %in.5 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 5
  %x5 = load i8, ptr addrspace(1) %in.5, align 1
  %c5 = sitofp i8 %x5 to double
  %out.5 = getelementptr inbounds double, ptr addrspace(1) %out, i64 5
  store double %c5, ptr addrspace(1) %out.5, align 8
  %in.6 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 6
  %x6 = load i8, ptr addrspace(1) %in.6, align 1
  %c6 = sitofp i8 %x6 to double
  %out.6 = getelementptr inbounds double, ptr addrspace(1) %out, i64 6
  store double %c6, ptr addrspace(1) %out.6, align 8
  %in.7 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 7
  %x7 = load i8, ptr addrspace(1) %in.7, align 1
  %c7 = sitofp i8 %x7 to double
  %out.7 = getelementptr inbounds double, ptr addrspace(1) %out, i64 7
  store double %c7, ptr addrspace(1) %out.7, align 8
  ret void
}

define float @sitofp_i8_sum_to_float(ptr addrspace(1) noalias %in) {
  %x0 = load i8, ptr addrspace(1) %in, align 1
  %c0 = sitofp i8 %x0 to float
  %in.1 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 1
  %x1 = load i8, ptr addrspace(1) %in.1, align 1
  %c1 = sitofp i8 %x1 to float
  %s1 = fadd fast float %c0, %c1
  %in.2 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 2
  %x2 = load i8, ptr addrspace(1) %in.2, align 1
  %c2 = sitofp i8 %x2 to float
  %s2 = fadd fast float %s1, %c2
  %in.3 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 3
  %x3 = load i8, ptr addrspace(1) %in.3, align 1
  %c3 = sitofp i8 %x3 to float
  %s3 = fadd fast float %s2, %c3
  %in.4 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 4
  %x4 = load i8, ptr addrspace(1) %in.4, align 1
  %c4 = sitofp i8 %x4 to float
  %s4 = fadd fast float %s3, %c4
  %in.5 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 5
  %x5 = load i8, ptr addrspace(1) %in.5, align 1
  %c5 = sitofp i8 %x5 to float
  %s5 = fadd fast float %s4, %c5
  %in.6 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 6
  %x6 = load i8, ptr addrspace(1) %in.6, align 1
  %c6 = sitofp i8 %x6 to float
  %s6 = fadd fast float %s5, %c6
  %in.7 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 7
  %x7 = load i8, ptr addrspace(1) %in.7, align 1
  %c7 = sitofp i8 %x7 to float
  %s7 = fadd fast float %s6, %c7
  ret float %s7
}

define void @sitofp_i8_scaled_to_float(ptr addrspace(1) noalias %out, ptr addrspace(1) noalias %in, float %scale) {
  %x0 = load i8, ptr addrspace(1) %in, align 1
  %c0 = sitofp i8 %x0 to float
  %m0 = fmul float %c0, %scale
  store float %m0, ptr addrspace(1) %out, align 4
  %in.1 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 1
  %x1 = load i8, ptr addrspace(1) %in.1, align 1
  %c1 = sitofp i8 %x1 to float
  %m1 = fmul float %c1, %scale
  %out.1 = getelementptr inbounds float, ptr addrspace(1) %out, i64 1
  store float %m1, ptr addrspace(1) %out.1, align 4
  %in.2 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 2
  %x2 = load i8, ptr addrspace(1) %in.2, align 1
  %c2 = sitofp i8 %x2 to float
  %m2 = fmul float %c2, %scale
  %out.2 = getelementptr inbounds float, ptr addrspace(1) %out, i64 2
  store float %m2, ptr addrspace(1) %out.2, align 4
  %in.3 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 3
  %x3 = load i8, ptr addrspace(1) %in.3, align 1
  %c3 = sitofp i8 %x3 to float
  %m3 = fmul float %c3, %scale
  %out.3 = getelementptr inbounds float, ptr addrspace(1) %out, i64 3
  store float %m3, ptr addrspace(1) %out.3, align 4
  %in.4 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 4
  %x4 = load i8, ptr addrspace(1) %in.4, align 1
  %c4 = sitofp i8 %x4 to float
  %m4 = fmul float %c4, %scale
  %out.4 = getelementptr inbounds float, ptr addrspace(1) %out, i64 4
  store float %m4, ptr addrspace(1) %out.4, align 4
  %in.5 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 5
  %x5 = load i8, ptr addrspace(1) %in.5, align 1
  %c5 = sitofp i8 %x5 to float
  %m5 = fmul float %c5, %scale
  %out.5 = getelementptr inbounds float, ptr addrspace(1) %out, i64 5
  store float %m5, ptr addrspace(1) %out.5, align 4
  %in.6 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 6
  %x6 = load i8, ptr addrspace(1) %in.6, align 1
  %c6 = sitofp i8 %x6 to float
  %m6 = fmul float %c6, %scale
  %out.6 = getelementptr inbounds float, ptr addrspace(1) %out, i64 6
  store float %m6, ptr addrspace(1) %out.6, align 4
  %in.7 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 7
  %x7 = load i8, ptr addrspace(1) %in.7, align 1
  %c7 = sitofp i8 %x7 to float
  %m7 = fmul float %c7, %scale
  %out.7 = getelementptr inbounds float, ptr addrspace(1) %out, i64 7
  store float %m7, ptr addrspace(1) %out.7, align 4
  ret void
}

define void @sitofp_i12_to_half(ptr addrspace(1) noalias %out, ptr addrspace(1) noalias %in) {
  %x0 = load i16, ptr addrspace(1) %in, align 2
  %t0 = trunc i16 %x0 to i12
  %c0 = sitofp i12 %t0 to half
  store half %c0, ptr addrspace(1) %out, align 2
  %in.1 = getelementptr inbounds i16, ptr addrspace(1) %in, i64 1
  %x1 = load i16, ptr addrspace(1) %in.1, align 2
  %t1 = trunc i16 %x1 to i12
  %c1 = sitofp i12 %t1 to half
  %out.1 = getelementptr inbounds half, ptr addrspace(1) %out, i64 1
  store half %c1, ptr addrspace(1) %out.1, align 2
  %in.2 = getelementptr inbounds i16, ptr addrspace(1) %in, i64 2
  %x2 = load i16, ptr addrspace(1) %in.2, align 2
  %t2 = trunc i16 %x2 to i12
  %c2 = sitofp i12 %t2 to half
  %out.2 = getelementptr inbounds half, ptr addrspace(1) %out, i64 2
  store half %c2, ptr addrspace(1) %out.2, align 2
  %in.3 = getelementptr inbounds i16, ptr addrspace(1) %in, i64 3
  %x3 = load i16, ptr addrspace(1) %in.3, align 2
  %t3 = trunc i16 %x3 to i12
  %c3 = sitofp i12 %t3 to half
  %out.3 = getelementptr inbounds half, ptr addrspace(1) %out, i64 3
  store half %c3, ptr addrspace(1) %out.3, align 2
  ret void
}

define void @sitofp_i12_to_bfloat(ptr addrspace(1) noalias %out, ptr addrspace(1) noalias %in) {
  %x0 = load i16, ptr addrspace(1) %in, align 2
  %t0 = trunc i16 %x0 to i12
  %c0 = sitofp i12 %t0 to bfloat
  store bfloat %c0, ptr addrspace(1) %out, align 2
  %in.1 = getelementptr inbounds i16, ptr addrspace(1) %in, i64 1
  %x1 = load i16, ptr addrspace(1) %in.1, align 2
  %t1 = trunc i16 %x1 to i12
  %c1 = sitofp i12 %t1 to bfloat
  %out.1 = getelementptr inbounds bfloat, ptr addrspace(1) %out, i64 1
  store bfloat %c1, ptr addrspace(1) %out.1, align 2
  %in.2 = getelementptr inbounds i16, ptr addrspace(1) %in, i64 2
  %x2 = load i16, ptr addrspace(1) %in.2, align 2
  %t2 = trunc i16 %x2 to i12
  %c2 = sitofp i12 %t2 to bfloat
  %out.2 = getelementptr inbounds bfloat, ptr addrspace(1) %out, i64 2
  store bfloat %c2, ptr addrspace(1) %out.2, align 2
  %in.3 = getelementptr inbounds i16, ptr addrspace(1) %in, i64 3
  %x3 = load i16, ptr addrspace(1) %in.3, align 2
  %t3 = trunc i16 %x3 to i12
  %c3 = sitofp i12 %t3 to bfloat
  %out.3 = getelementptr inbounds bfloat, ptr addrspace(1) %out, i64 3
  store bfloat %c3, ptr addrspace(1) %out.3, align 2
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; GFX1100: {{.*}}
; GFX1250: {{.*}}
; GFX900: {{.*}}
; GFX90A: {{.*}}
