# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs -run-pass si-insert-waitcnts %s -o - | FileCheck -check-prefix=GCN %s

---
# Check that a VGPR write dependency on STOREcnt generated by RTS_RAY_SAVE is
# handled correctly (should be a wait for STOREcnt<=1 before first V_ADD_U32)
# and that instructions using STOREcnt that can complete out of order with
# respect to each other are also handled correctly (there should be a wait
# for STOREcnt==0 before the second and third V_ADD_U32s, not 1).


name:            test_rts_ray_save
machineFunctionInfo:
  isEntryFunction: true
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2

    ; GCN-LABEL: name: test_rts_ray_save
    ; GCN: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: $vgpr3 = RTS_RAY_SAVE 0, implicit $exec :: (load store (s32), align 1)
    ; GCN-NEXT: $vgpr4 = RTS_RAY_SAVE 0, implicit $exec :: (load store (s32), align 1)
    ; GCN-NEXT: S_WAIT_STORECNT 1
    ; GCN-NEXT: $vgpr3 = V_ADD_U32_e32 $vgpr3, $vgpr3, implicit $exec
    ; GCN-NEXT: IMAGE_STORE_V2_V1_gfx13 $vgpr0_vgpr1, $vgpr2, $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 12, 0, 1, 0, 0, -1, 0, implicit $exec :: (dereferenceable store (<2 x s32>), addrspace 7)
    ; GCN-NEXT: S_WAIT_STORECNT 0
    ; GCN-NEXT: $vgpr4 = V_ADD_U32_e32 $vgpr4, $vgpr4, implicit $exec
    ; GCN-NEXT: $vgpr5 = RTS_RAY_SAVE 0, implicit $exec :: (load store (s32), align 1)
    ; GCN-NEXT: GLOBAL_STORE_DWORD $vgpr0_vgpr1, $vgpr2, 0, 0, implicit $exec
    ; GCN-NEXT: S_WAIT_STORECNT 0
    ; GCN-NEXT: $vgpr5 = V_ADD_U32_e32 $vgpr5, $vgpr5, implicit $exec
    ; GCN-NEXT: EXP_DONE 20, $vgpr3, $vgpr4, $vgpr5, $vgpr3, 0, 0, 1, implicit $exec
    ; GCN-NEXT: S_ENDPGM 0
    $vgpr3 = RTS_RAY_SAVE 0, implicit $exec :: (load store (s32), align 1)
    $vgpr4 = RTS_RAY_SAVE 0, implicit $exec :: (load store (s32), align 1)
    $vgpr3 = V_ADD_U32_e32 $vgpr3, $vgpr3, implicit $exec
    IMAGE_STORE_V2_V1_gfx13 $vgpr0_vgpr1, $vgpr2, $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 12, 0, 1, 0, 0, -1, 0, implicit $exec :: (dereferenceable store (<2 x s32>), addrspace 7)
    $vgpr4 = V_ADD_U32_e32 $vgpr4, $vgpr4, implicit $exec
    $vgpr5 = RTS_RAY_SAVE 0, implicit $exec :: (load store (s32), align 1)
    GLOBAL_STORE_DWORD $vgpr0_vgpr1, $vgpr2, 0, 0, implicit $exec
    $vgpr5 = V_ADD_U32_e32 $vgpr5, $vgpr5, implicit $exec
    EXP_DONE 20, $vgpr3, $vgpr4, $vgpr5, $vgpr3, 0, 0, 1, implicit $exec
    S_ENDPGM 0
...
