# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -passes=machine-scheduler -verify-misched -filetype=null %s  2>&1  | FileCheck %s

--- |
 @LS = external local_unnamed_addr addrspace(10) global <512 x i32>, align 64

 define void @bundles() { unreachable }
...

---
name: bundles
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: bundles
    ; CHECK: $idx1 = S_SET_GPR_IDX_U32 0
    ; CHECK-NEXT: BUNDLE implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def %0, implicit $idx1, implicit $exec :: (dereferenceable load (s32) from @LS + 2272, align 32, addrspace 10), (dereferenceable load (s128) from @LS + 64, align 64, addrspace 10) {
    ; CHECK-NEXT:   $stg_srcb = V_LOAD_IDX_B32 $idx1, 568, implicit $exec :: (dereferenceable load (s32) from @LS + 2272, align 32, addrspace 10)
    ; CHECK-NEXT:   $stg_srca = V_LOAD_IDX_B128 $idx1, 16, implicit $exec :: (dereferenceable load (s128) from @LS + 64, align 64, addrspace 10)
    ; CHECK-NEXT:   [[V_SCALE_BIAS_ACTIVATE_F32_:%[0-9]+]]:vreg_128 = contract V_SCALE_BIAS_ACTIVATE_F32 internal $stg_srca, 1065353216, internal $stg_srcb, 131, -1, 0, 0, implicit $exec
    ; CHECK-NEXT: }
    ; CHECK-NEXT: [[V_CVT_TO_TENSOR_F16_F32_4x2x16_:%[0-9]+]]:vgpr_32, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_1:%[0-9]+]]:vgpr_32 = V_CVT_TO_TENSOR_F16_F32_4x2x16 [[V_SCALE_BIAS_ACTIVATE_F32_]], 0, 3, -1, 0, 0, implicit $exec
    ; CHECK-NEXT: BUNDLE implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def %7, implicit $idx1, implicit $exec :: (dereferenceable load (s32) from @LS + 2272, align 32, addrspace 10), (dereferenceable load (s128) from @LS + 80, addrspace 10) {
    ; CHECK-NEXT:   $stg_srcb = V_LOAD_IDX_B32 $idx1, 568, implicit $exec :: (dereferenceable load (s32) from @LS + 2272, align 32, addrspace 10)
    ; CHECK-NEXT:   $stg_srca = V_LOAD_IDX_B128 $idx1, 20, implicit $exec :: (dereferenceable load (s128) from @LS + 80, addrspace 10)
    ; CHECK-NEXT:   [[V_SCALE_BIAS_ACTIVATE_F32_1:%[0-9]+]]:vreg_128 = contract V_SCALE_BIAS_ACTIVATE_F32 internal $stg_srca, 1065353216, internal $stg_srcb, 2179, -1, 0, 0, implicit $exec
    ; CHECK-NEXT: }
    ; CHECK-NEXT: [[V_CVT_TO_TENSOR_F16_F32_4x2x16_2:%[0-9]+]]:vgpr_32, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_3:%[0-9]+]]:vgpr_32 = V_CVT_TO_TENSOR_F16_F32_4x2x16 [[V_SCALE_BIAS_ACTIVATE_F32_1]], 0, 3, -1, 0, 0, implicit $exec
    ; CHECK-NEXT: [[V_PK_MUL_F16_:%[0-9]+]]:vgpr_32 = contract nofpexcept V_PK_MUL_F16 0, 12902, 8, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: [[V_PK_MAX_F16_:%[0-9]+]]:vgpr_32 = contract nofpexcept V_PK_MAX_F16 8, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_]], 8, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: [[V_PK_MUL_F16_1:%[0-9]+]]:vgpr_32 = contract nofpexcept V_PK_MUL_F16 0, 12902, 8, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_1]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: [[V_PK_MAX_F16_1:%[0-9]+]]:vgpr_32 = contract nofpexcept V_PK_MAX_F16 8, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_1]], 8, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_1]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: [[V_PK_MUL_F16_2:%[0-9]+]]:vgpr_32 = contract nofpexcept V_PK_MUL_F16 0, 12902, 8, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_2]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: [[V_PK_MAX_F16_2:%[0-9]+]]:vgpr_32 = contract nofpexcept V_PK_MAX_F16 8, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_2]], 8, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_2]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: [[V_PK_MUL_F16_3:%[0-9]+]]:vgpr_32 = contract nofpexcept V_PK_MUL_F16 0, 12902, 8, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_3]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: [[V_PK_MAX_F16_3:%[0-9]+]]:vgpr_32 = contract nofpexcept V_PK_MAX_F16 8, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_3]], 8, [[V_CVT_TO_TENSOR_F16_F32_4x2x16_3]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: BUNDLE implicit-def dead $stg_dsta, implicit [[V_PK_MAX_F16_]], implicit [[V_PK_MUL_F16_]], implicit $mode, implicit $exec, implicit $idx1 :: (store (s32) into @LS + 1284, addrspace 10) {
    ; CHECK-NEXT:   $stg_dsta = contract nofpexcept V_PK_MAX_F16 8, [[V_PK_MAX_F16_]], 8, [[V_PK_MUL_F16_]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT:   V_STORE_IDX_B32 internal $stg_dsta, $idx1, 321, implicit $exec :: (store (s32) into @LS + 1284, addrspace 10)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE implicit-def dead $stg_dsta, implicit [[V_PK_MAX_F16_1]], implicit [[V_PK_MUL_F16_1]], implicit $mode, implicit $exec, implicit $idx1 :: (store (s32) into @LS + 1348, addrspace 10) {
    ; CHECK-NEXT:   $stg_dsta = contract nofpexcept V_PK_MAX_F16 8, [[V_PK_MAX_F16_1]], 8, [[V_PK_MUL_F16_1]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT:   V_STORE_IDX_B32 internal $stg_dsta, $idx1, 337, implicit $exec :: (store (s32) into @LS + 1348, addrspace 10)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE implicit-def dead $stg_dsta, implicit [[V_PK_MAX_F16_2]], implicit [[V_PK_MUL_F16_2]], implicit $mode, implicit $exec, implicit $idx1 :: (store (s32) into @LS + 1412, addrspace 10) {
    ; CHECK-NEXT:   $stg_dsta = contract nofpexcept V_PK_MAX_F16 8, [[V_PK_MAX_F16_2]], 8, [[V_PK_MUL_F16_2]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT:   V_STORE_IDX_B32 internal $stg_dsta, $idx1, 353, implicit $exec :: (store (s32) into @LS + 1412, addrspace 10)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: BUNDLE implicit-def dead $stg_dsta, implicit [[V_PK_MAX_F16_3]], implicit [[V_PK_MUL_F16_3]], implicit $mode, implicit $exec, implicit $idx1 :: (store (s32) into @LS + 1476, addrspace 10) {
    ; CHECK-NEXT:   $stg_dsta = contract nofpexcept V_PK_MAX_F16 8, [[V_PK_MAX_F16_3]], 8, [[V_PK_MUL_F16_3]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT:   V_STORE_IDX_B32 internal $stg_dsta, $idx1, 369, implicit $exec :: (store (s32) into @LS + 1476, addrspace 10)
    ; CHECK-NEXT: }
    $idx1 = S_SET_GPR_IDX_U32 0
    BUNDLE implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def %49, implicit $idx1, implicit $exec :: (dereferenceable load (s32) from @LS + 2272, align 32, addrspace 10), (dereferenceable load (s128) from @LS + 64, align 64, addrspace 10) {
      $stg_srcb = V_LOAD_IDX_B32 $idx1, 568, implicit $exec :: (dereferenceable load (s32) from @LS + 2272, align 32, addrspace 10)
      $stg_srca = V_LOAD_IDX_B128 $idx1, 16, implicit $exec :: (dereferenceable load (s128) from @LS + 64, align 64, addrspace 10)
      %49:vreg_128 = contract V_SCALE_BIAS_ACTIVATE_F32 internal $stg_srca, 1065353216, internal $stg_srcb, 131, -1, 0, 0, implicit $exec
    }
    %51:vgpr_32, %52:vgpr_32 = V_CVT_TO_TENSOR_F16_F32_4x2x16 %49, 0, 3, -1, 0, 0, implicit $exec
    %54:vgpr_32 = contract nofpexcept V_PK_MUL_F16 0, 12902, 8, %51, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %55:vgpr_32 = contract nofpexcept V_PK_MAX_F16 8, %51, 8, %51, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %58:vgpr_32 = contract nofpexcept V_PK_MUL_F16 0, 12902, 8, %52, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %59:vgpr_32 = contract nofpexcept V_PK_MAX_F16 8, %52, 8, %52, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    BUNDLE implicit-def dead $stg_dsta, implicit %55, implicit %54, implicit $mode, implicit $exec, implicit $idx1 :: (store (s32) into @LS + 1284, addrspace 10) {
      $stg_dsta = contract nofpexcept V_PK_MAX_F16 8, %55, 8, %54, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
      V_STORE_IDX_B32 internal $stg_dsta, $idx1, 321, implicit $exec :: (store (s32) into @LS + 1284, addrspace 10)
    }
    BUNDLE implicit-def dead $stg_dsta, implicit %59, implicit %58, implicit $mode, implicit $exec, implicit $idx1 :: (store (s32) into @LS + 1348, addrspace 10) {
      $stg_dsta = contract nofpexcept V_PK_MAX_F16 8, %59, 8, %58, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
      V_STORE_IDX_B32 internal $stg_dsta, $idx1, 337, implicit $exec :: (store (s32) into @LS + 1348, addrspace 10)
    }
    BUNDLE implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def %64, implicit $idx1, implicit $exec :: (dereferenceable load (s32) from @LS + 2272, align 32, addrspace 10), (dereferenceable load (s128) from @LS + 80, addrspace 10) {
      $stg_srcb = V_LOAD_IDX_B32 $idx1, 568, implicit $exec :: (dereferenceable load (s32) from @LS + 2272, align 32, addrspace 10)
      $stg_srca = V_LOAD_IDX_B128 $idx1, 20, implicit $exec :: (dereferenceable load (s128) from @LS + 80, addrspace 10)
      %64:vreg_128 = contract V_SCALE_BIAS_ACTIVATE_F32 internal $stg_srca, 1065353216, internal $stg_srcb, 2179, -1, 0, 0, implicit $exec
    }
    %65:vgpr_32, %66:vgpr_32 = V_CVT_TO_TENSOR_F16_F32_4x2x16 %64, 0, 3, -1, 0, 0, implicit $exec
    %67:vgpr_32 = contract nofpexcept V_PK_MUL_F16 0, 12902, 8, %65, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %68:vgpr_32 = contract nofpexcept V_PK_MAX_F16 8, %65, 8, %65, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %71:vgpr_32 = contract nofpexcept V_PK_MUL_F16 0, 12902, 8, %66, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %72:vgpr_32 = contract nofpexcept V_PK_MAX_F16 8, %66, 8, %66, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    BUNDLE implicit-def dead $stg_dsta, implicit %68, implicit %67, implicit $mode, implicit $exec, implicit $idx1 :: (store (s32) into @LS + 1412, addrspace 10) {
      $stg_dsta = contract nofpexcept V_PK_MAX_F16 8, %68, 8, %67, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
      V_STORE_IDX_B32 internal $stg_dsta, $idx1, 353, implicit $exec :: (store (s32) into @LS + 1412, addrspace 10)
    }
    BUNDLE implicit-def dead $stg_dsta, implicit %72, implicit %71, implicit $mode, implicit $exec, implicit $idx1 :: (store (s32) into @LS + 1476, addrspace 10) {
      $stg_dsta = contract nofpexcept V_PK_MAX_F16 8, %72, 8, %71, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
      V_STORE_IDX_B32 internal $stg_dsta, $idx1, 369, implicit $exec :: (store (s32) into @LS + 1476, addrspace 10)
    }
...
