; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn -mcpu=gfx1370 -mattr=+wavefrontsize32 -verify-machineinstrs < %s | FileCheck %s

declare <4 x half> @llvm.amdgcn.fma.from.tensor.f16.i16.v4f16(<4 x half>, <2 x i16>, <2 x i16>, <4 x half>, i32, i1) #0

define amdgpu_ps void @test_fma_from_tensor_f16_i16_dequant_disable_4x2(ptr addrspace(1) %out, <4 x half> %acc_in, <2 x i16> %resid_0, <2 x i16> %resid_1, <4 x half> %scale) {
; CHECK-LABEL: test_fma_from_tensor_f16_i16_dequant_disable_4x2:
; CHECK:       ; %bb.0: ; %bb
; CHECK-NEXT:    v_fma_from_tensor_f16_i16 v[2:3], [v4, v5], v[6:7], v[2:3] layout:LAYOUT_CONVOLVE_4X2 clamp
; CHECK-NEXT:    global_store_b64 v[0:1], v[2:3], off
; CHECK-NEXT:    s_endpgm
bb:
  %dst = call <4 x half> @llvm.amdgcn.fma.from.tensor.f16.i16.v4f16(<4 x half> %acc_in, <2 x i16> %resid_0, <2 x i16> %resid_1, <4 x half> %scale,
              ;   AUX_DATA: PIXEL_SHAPE_CONV_4X2 == (2 << 0)
              i32 2,
              ;   CLAMP
              i1 1)
  store <4 x half> %dst, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @test_fma_from_tensor_f16_i16_dequant_disable_4x4(ptr addrspace(1) %out, <4 x half> %acc_in, <2 x i16> %resid_0, <2 x i16> %resid_1, <4 x half> %scale) {
; CHECK-LABEL: test_fma_from_tensor_f16_i16_dequant_disable_4x4:
; CHECK:       ; %bb.0: ; %bb
; CHECK-NEXT:    v_fma_from_tensor_f16_i16 v[2:3], [v4, v5], v[6:7], v[2:3] layout:LAYOUT_CONVOLVE_4X4 clamp
; CHECK-NEXT:    global_store_b64 v[0:1], v[2:3], off
; CHECK-NEXT:    s_endpgm
bb:
  %dst = call <4 x half> @llvm.amdgcn.fma.from.tensor.f16.i16.v4f16(<4 x half> %acc_in, <2 x i16> %resid_0, <2 x i16> %resid_1, <4 x half> %scale,
              ;   AUX_DATA: PIXEL_SHAPE_CONV_4X4 == (1 << 0)
              i32 1,
              ;   CLAMP
              i1 1)
  store <4 x half> %dst, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @test_fma_from_tensor_f16_i16_dequant_disable_8x4(ptr addrspace(1) %out, <4 x half> %acc_in, <2 x i16> %resid_0, <2 x i16> %resid_1, <4 x half> %scale) {
; CHECK-LABEL: test_fma_from_tensor_f16_i16_dequant_disable_8x4:
; CHECK:       ; %bb.0: ; %bb
; CHECK-NEXT:    v_fma_from_tensor_f16_i16 v[2:3], [v4, v5], v[6:7], v[2:3] layout:LAYOUT_CONVOLVE_8X4 clamp
; CHECK-NEXT:    global_store_b64 v[0:1], v[2:3], off
; CHECK-NEXT:    s_endpgm
bb:
  %dst = call <4 x half> @llvm.amdgcn.fma.from.tensor.f16.i16.v4f16(<4 x half> %acc_in, <2 x i16> %resid_0, <2 x i16> %resid_1, <4 x half> %scale,
              ;   AUX_DATA: PIXEL_SHAPE_CONV_8X4 == (0 << 0)
              i32 0,
              ;   CLAMP
              i1 1)
  store <4 x half> %dst, ptr addrspace(1) %out
  ret void
}

declare <4 x half> @llvm.amdgcn.fma.from.tensor.f16.u16.v4f16(<4 x half>, <2 x i16>, <2 x i16>, <4 x half>, i32, i1) #0

define amdgpu_ps void @test_fma_from_tensor_f16_u16_dequant_disable_4x2(ptr addrspace(1) %out, <4 x half> %acc_in, <2 x i16> %resid_0, <2 x i16> %resid_1, <4 x half> %scale) {
; CHECK-LABEL: test_fma_from_tensor_f16_u16_dequant_disable_4x2:
; CHECK:       ; %bb.0: ; %bb
; CHECK-NEXT:    v_fma_from_tensor_f16_u16 v[2:3], [v4, v5], v[6:7], v[2:3] layout:LAYOUT_CONVOLVE_4X2 clamp
; CHECK-NEXT:    global_store_b64 v[0:1], v[2:3], off
; CHECK-NEXT:    s_endpgm
bb:
  %dst = call <4 x half> @llvm.amdgcn.fma.from.tensor.f16.u16.v4f16(<4 x half> %acc_in, <2 x i16> %resid_0, <2 x i16> %resid_1, <4 x half> %scale,
              ;   AUX_DATA: PIXEL_SHAPE_CONV_4X2 == (2 << 0)
              i32 2,
              ;   CLAMP
              i1 1)
  store <4 x half> %dst, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @test_fma_from_tensor_f16_u16_dequant_disable_4x4(ptr addrspace(1) %out, <4 x half> %acc_in, <2 x i16> %resid_0, <2 x i16> %resid_1, <4 x half> %scale) {
; CHECK-LABEL: test_fma_from_tensor_f16_u16_dequant_disable_4x4:
; CHECK:       ; %bb.0: ; %bb
; CHECK-NEXT:    v_fma_from_tensor_f16_u16 v[2:3], [v4, v5], v[6:7], v[2:3] layout:LAYOUT_CONVOLVE_4X4 clamp
; CHECK-NEXT:    global_store_b64 v[0:1], v[2:3], off
; CHECK-NEXT:    s_endpgm
bb:
  %dst = call <4 x half> @llvm.amdgcn.fma.from.tensor.f16.u16.v4f16(<4 x half> %acc_in, <2 x i16> %resid_0, <2 x i16> %resid_1, <4 x half> %scale,
              ;   AUX_DATA: PIXEL_SHAPE_CONV_4X4 == (1 << 0)
              i32 1,
              ;   CLAMP
              i1 1)
  store <4 x half> %dst, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @test_fma_from_tensor_f16_u16_dequant_disable_8x4(ptr addrspace(1) %out, <4 x half> %acc_in, <2 x i16> %resid_0, <2 x i16> %resid_1, <4 x half> %scale) {
; CHECK-LABEL: test_fma_from_tensor_f16_u16_dequant_disable_8x4:
; CHECK:       ; %bb.0: ; %bb
; CHECK-NEXT:    v_fma_from_tensor_f16_u16 v[2:3], [v4, v5], v[6:7], v[2:3] layout:LAYOUT_CONVOLVE_8X4 clamp
; CHECK-NEXT:    global_store_b64 v[0:1], v[2:3], off
; CHECK-NEXT:    s_endpgm
bb:
  %dst = call <4 x half> @llvm.amdgcn.fma.from.tensor.f16.u16.v4f16(<4 x half> %acc_in, <2 x i16> %resid_0, <2 x i16> %resid_1, <4 x half> %scale,
              ;   AUX_DATA: PIXEL_SHAPE_CONV_8X4 == (0 << 0)
              i32 0,
              ;   CLAMP
              i1 1)
  store <4 x half> %dst, ptr addrspace(1) %out
  ret void
}

attributes #0 = { nounwind convergent }
