; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -stop-after=bundle-indexed-load-store -verify-machineinstrs -o - %s | FileCheck %s

target datalayout = "A5"

@weights = external local_unnamed_addr addrspace(10) global [9 x i32], align 4
@color = external local_unnamed_addr addrspace(10) global [9 x i32], align 4
@out = external local_unnamed_addr addrspace(10) global [8 x half], align 4

define amdgpu_kernel void @vectorize() "amdgpu-wavegroup-enable" !reqd_work_group_size !4 {
  ; CHECK-LABEL: name: vectorize
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 0
  ; CHECK-NEXT:   [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; CHECK-NEXT:   [[V_MOV_B32_e32_1:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; CHECK-NEXT:   [[V_MOV_B32_e32_2:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; CHECK-NEXT:   [[V_MOV_B32_e32_3:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; CHECK-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[V_MOV_B32_e32_]], %subreg.sub0, [[V_MOV_B32_e32_1]], %subreg.sub1, [[V_MOV_B32_e32_2]], %subreg.sub2, [[V_MOV_B32_e32_3]], %subreg.sub3
  ; CHECK-NEXT:   BUNDLE implicit-def dead $stg_srcd, implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit killed [[S_MOV_B32_]], implicit $exec :: (dereferenceable load (s96) from @color + 24, align 4, addrspace 10), (dereferenceable load (s96) from @color + 12, align 4, addrspace 10), (dereferenceable load (s96) from @color, align 4, addrspace 10), (dereferenceable load (s288) from @weights, align 268435456, addrspace 10), (store (s128) into @out, align 8, !tbaa !8, addrspace 10) {
  ; CHECK-NEXT:     $stg_srcd = V_LOAD_IDX_B96 [[S_MOV_B32_]], 15, implicit $exec :: (dereferenceable load (s96) from @color + 24, align 4, addrspace 10)
  ; CHECK-NEXT:     $stg_srcc = V_LOAD_IDX_B96 [[S_MOV_B32_]], 12, implicit $exec :: (dereferenceable load (s96) from @color + 12, align 4, addrspace 10)
  ; CHECK-NEXT:     $stg_srcb = V_LOAD_IDX_B96 [[S_MOV_B32_]], 9, implicit $exec :: (dereferenceable load (s96) from @color, align 4, addrspace 10)
  ; CHECK-NEXT:     $stg_srca = V_LOAD_IDX_B288 [[S_MOV_B32_]], 0, implicit $exec :: (dereferenceable load (s288) from @weights, align 268435456, addrspace 10)
  ; CHECK-NEXT:     $stg_dsta = contract V_CONVOLVE_F16_FP8_FP8_3x3_4x4 0, internal killed $stg_srca, internal killed $stg_srcb, internal killed $stg_srcc, internal killed $stg_srcd, 10, -1, 0, 0, implicit $exec
  ; CHECK-NEXT:     V_STORE_IDX_B128 internal $stg_dsta, killed [[S_MOV_B32_]], 18, implicit $exec :: (store (s128) into @out, align 8, !tbaa !8, addrspace 10)
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   S_ENDPGM 0
entry:
  %6 = load i32, ptr addrspace(10) @weights, align 4
  %vecins = insertelement <9 x i32> undef, i32 %6, i64 0
  %7 = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 4), align 4, !tbaa !5
  %vecins.1 = insertelement <9 x i32> %vecins, i32 %7, i64 1
  %8 = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 8), align 4, !tbaa !5
  %vecins.2 = insertelement <9 x i32> %vecins.1, i32 %8, i64 2
  %9 = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 12), align 4, !tbaa !5
  %vecins.3 = insertelement <9 x i32> %vecins.2, i32 %9, i64 3
  %10 = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 16), align 4, !tbaa !5
  %vecins.4 = insertelement <9 x i32> %vecins.3, i32 %10, i64 4
  %11 = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 20), align 4, !tbaa !5
  %vecins.5 = insertelement <9 x i32> %vecins.4, i32 %11, i64 5
  %12 = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 24), align 4, !tbaa !5
  %vecins.6 = insertelement <9 x i32> %vecins.5, i32 %12, i64 6
  %13 = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 28), align 4, !tbaa !5
  %vecins.7 = insertelement <9 x i32> %vecins.6, i32 %13, i64 7
  %14 = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 32), align 4, !tbaa !5
  %vecins.8 = insertelement <9 x i32> %vecins.7, i32 %14, i64 8
  %15 = load <3 x i32>, ptr addrspace(10) @color, align 4, !tbaa !12
  %16 = load <3 x i32>, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @color, i32 12), align 4, !tbaa !12
  %17 = load <3 x i32>, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @color, i32 24), align 4, !tbaa !12
  %18 = tail call contract <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> zeroinitializer, <9 x i32> %vecins.8, <3 x i32> %15, <3 x i32> %16, <3 x i32> %17, i32 10, i1 true)
  %vecext = extractelement <8 x half> %18, i64 0
  store half %vecext, ptr addrspace(10) @out, align 4, !tbaa !13
  %vecext.1 = extractelement <8 x half> %18, i64 1
  store half %vecext.1, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @out, i32 2), align 2, !tbaa !13
  %vecext.2 = extractelement <8 x half> %18, i64 2
  store half %vecext.2, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @out, i32 4), align 4, !tbaa !13
  %vecext.3 = extractelement <8 x half> %18, i64 3
  store half %vecext.3, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @out, i32 6), align 2, !tbaa !13
  %vecext.4 = extractelement <8 x half> %18, i64 4
  store half %vecext.4, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @out, i32 8), align 4, !tbaa !13
  %vecext.5 = extractelement <8 x half> %18, i64 5
  store half %vecext.5, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @out, i32 10), align 2, !tbaa !13
  %vecext.6 = extractelement <8 x half> %18, i64 6
  store half %vecext.6, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @out, i32 12), align 4, !tbaa !13
  %vecext.7 = extractelement <8 x half> %18, i64 7
  store half %vecext.7, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @out, i32 14), align 2, !tbaa !13
  ret void
}

; Function Attrs: convergent mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half>, <9 x i32>, <3 x i32>, <3 x i32>, <3 x i32>, i32 immarg, i1 immarg) #2

attributes #2 = { convergent mustprogress nocallback nofree nosync nounwind willreturn memory(none) }

!4 = !{i32 128, i32 1, i32 1}
!5 = !{!6, !6, i64 0}
!6 = !{!"int", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C++ TBAA"}
!9 = distinct !{!9, !10, !11}
!10 = !{!"llvm.loop.mustprogress"}
!11 = !{!"llvm.loop.unroll.disable"}
!12 = !{!7, !7, i64 0}
!13 = !{!14, !14, i64 0}
!14 = !{!"__fp16", !7, i64 0}
