; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -verify-machineinstrs -o - %s | FileCheck -check-prefixes=CHECK,VGPR %s

; test MinNumVGPRs and MaxNumVGPRs setting, make sure it does not trip assertion

target datalayout = "A5"

@global_laneshared = external local_unnamed_addr addrspace(10) global [2048 x i8], align 2
@global_smem = external addrspace(3) global [0 x i8], align 16

; Function Attrs: nounwind
define amdgpu_kernel void @laneshared_example_kernel(ptr addrspace(1) %0, ptr addrspace(1) writeonly captures(none) %1, ptr addrspace(1) readnone captures(none) %2, ptr addrspace(1) readnone captures(none) %3) local_unnamed_addr #0 !reqd_work_group_size !2 {
; CHECK-LABEL: laneshared_example_kernel:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; CHECK-NEXT:    s_mul_i32 s1, s0, 1
; CHECK-NEXT:    s_add_co_u32 s1, s1, 0x200
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    s_set_gpr_idx_u32 idx0, s1
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, 0
; CHECK-NEXT:    s_mul_i32 s33, s0, s2
; CHECK-NEXT:    s_set_vgpr_frames 4 ; vsrc0_idx=0 vsrc1_idx=1 vsrc2_idx=0 vdst_idx=0 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    ds_store_b32 v0, g1[0]
; CHECK-NEXT:    s_barrier_signal -1
; CHECK-NEXT:    s_barrier_wait -1
; CHECK-NEXT:    s_endpgm
  %id = call i32 @llvm.amdgcn.workitem.id.x()
  %b = load <2 x bfloat>, ptr addrspace(10) @global_laneshared, align 16
  %a= getelementptr inbounds i8, ptr addrspace(3) @global_smem, i32 %id
  store <2 x bfloat> %b, ptr addrspace(3) %a, align 2
  ret void
}

; VGPR: ; NumVgprs: 513
; VGPR: ; NumVGPRsForWavesPerEU: 513

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.x() #1


attributes #0 = { "amdgpu-flat-work-group-size"="1,128" "amdgpu-no-cluster-id-x" "amdgpu-no-cluster-id-y" "amdgpu-no-cluster-id-z" "amdgpu-no-completion-action" "amdgpu-no-default-queue" "amdgpu-no-dispatch-id" "amdgpu-no-dispatch-ptr" "amdgpu-no-flat-scratch-init" "amdgpu-no-heap-ptr" "amdgpu-no-hostcall-ptr" "amdgpu-no-implicitarg-ptr" "amdgpu-no-lds-kernel-id" "amdgpu-no-multigrid-sync-arg" "amdgpu-no-queue-ptr" "amdgpu-no-workgroup-id-x" "amdgpu-no-workgroup-id-y" "amdgpu-no-workgroup-id-z" "amdgpu-no-workitem-id-x" "amdgpu-no-workitem-id-y" "amdgpu-no-workitem-id-z" "amdgpu-wavegroup-enable" "amdgpu-waves-per-eu"="1, 1" "denormal-fp-math-f32"="ieee" "uniform-work-group-size"="false" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none) }

!llvm.module.flags = !{!0, !1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !{i32 1, !"amdhsa_code_object_version", i32 500}
!2 = !{i32 1, i32 1, i32 1}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; VGPR: {{.*}}
