; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -stop-after=bundle-indexed-load-store -verify-machineinstrs -o - %s | FileCheck %s

target datalayout = "A5"

@weights = external local_unnamed_addr addrspace(10) global [36 x half], align 4
@color = external local_unnamed_addr addrspace(10) global [18 x half], align 4
@out = external local_unnamed_addr addrspace(10) global [4 x float], align 4

define amdgpu_kernel void @vectorize() "amdgpu-wavegroup-enable" !reqd_work_group_size !4 {
  ; CHECK-LABEL: name: vectorize
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 0
  ; CHECK-NEXT:   [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; CHECK-NEXT:   [[V_MOV_B32_e32_1:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; CHECK-NEXT:   [[V_MOV_B32_e32_2:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; CHECK-NEXT:   [[V_MOV_B32_e32_3:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; CHECK-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[V_MOV_B32_e32_]], %subreg.sub0, [[V_MOV_B32_e32_1]], %subreg.sub1, [[V_MOV_B32_e32_2]], %subreg.sub2, [[V_MOV_B32_e32_3]], %subreg.sub3
  ; CHECK-NEXT:   BUNDLE implicit-def dead $stg_srcd, implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit killed [[S_MOV_B32_]], implicit $exec :: (dereferenceable load (s96) from @color + 24, align 8, addrspace 10), (dereferenceable load (s96) from @color + 12, align 4, basealign 8, addrspace 10), (dereferenceable load (s96) from @color, align 8, addrspace 10), (dereferenceable load (s576) from @weights, align 268435456, !tbaa !5, addrspace 10), (store (s128) into @out, align 4, !tbaa !10, addrspace 10) {
  ; CHECK-NEXT:     $stg_srcd = V_LOAD_IDX_B96 [[S_MOV_B32_]], 24, implicit $exec :: (dereferenceable load (s96) from @color + 24, align 8, addrspace 10)
  ; CHECK-NEXT:     $stg_srcc = V_LOAD_IDX_B96 [[S_MOV_B32_]], 21, implicit $exec :: (dereferenceable load (s96) from @color + 12, align 4, basealign 8, addrspace 10)
  ; CHECK-NEXT:     $stg_srcb = V_LOAD_IDX_B96 [[S_MOV_B32_]], 18, implicit $exec :: (dereferenceable load (s96) from @color, align 8, addrspace 10)
  ; CHECK-NEXT:     $stg_srca = V_LOAD_IDX_B576 [[S_MOV_B32_]], 0, implicit $exec :: (dereferenceable load (s576) from @weights, align 268435456, !tbaa !5, addrspace 10)
  ; CHECK-NEXT:     $stg_dsta = contract V_CONVOLVE_F32_F16_3x3_4x2 0, internal killed $stg_srca, internal killed $stg_srcb, internal killed $stg_srcc, internal killed $stg_srcd, 11, -1, 0, 0, implicit $exec
  ; CHECK-NEXT:     V_STORE_IDX_B128 internal $stg_dsta, killed [[S_MOV_B32_]], 27, implicit $exec :: (store (s128) into @out, align 4, !tbaa !10, addrspace 10)
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   S_ENDPGM 0
entry:
  %4 = load half, ptr addrspace(10) @weights, align 4, !tbaa !12
  %vecins = insertelement <36 x half> <half poison, half poison, half poison, half poison, half poison, half poison, half poison, half poison, half poison, half poison, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef, half undef>, half %4, i64 0
  %5 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 2), align 2, !tbaa !12
  %vecins.1 = insertelement <36 x half> %vecins, half %5, i64 1
  %6 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 4), align 4, !tbaa !12
  %vecins.2 = insertelement <36 x half> %vecins.1, half %6, i64 2
  %7 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 6), align 2, !tbaa !12
  %vecins.3 = insertelement <36 x half> %vecins.2, half %7, i64 3
  %8 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 8), align 4, !tbaa !12
  %vecins.4 = insertelement <36 x half> %vecins.3, half %8, i64 4
  %9 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 10), align 2, !tbaa !12
  %vecins.5 = insertelement <36 x half> %vecins.4, half %9, i64 5
  %10 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 12), align 4, !tbaa !12
  %vecins.6 = insertelement <36 x half> %vecins.5, half %10, i64 6
  %11 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 14), align 2, !tbaa !12
  %vecins.7 = insertelement <36 x half> %vecins.6, half %11, i64 7
  %12 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 16), align 4, !tbaa !12
  %vecins.8 = insertelement <36 x half> %vecins.7, half %12, i64 8
  %13 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 18), align 2, !tbaa !12
  %vecins.9 = insertelement <36 x half> %vecins.8, half %13, i64 9
  %14 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 20), align 4, !tbaa !12
  %vecins.10 = insertelement <36 x half> %vecins.9, half %14, i64 10
  %15 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 22), align 2, !tbaa !12
  %vecins.11 = insertelement <36 x half> %vecins.10, half %15, i64 11
  %16 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 24), align 4, !tbaa !12
  %vecins.12 = insertelement <36 x half> %vecins.11, half %16, i64 12
  %17 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 26), align 2, !tbaa !12
  %vecins.13 = insertelement <36 x half> %vecins.12, half %17, i64 13
  %18 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 28), align 4, !tbaa !12
  %vecins.14 = insertelement <36 x half> %vecins.13, half %18, i64 14
  %19 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 30), align 2, !tbaa !12
  %vecins.15 = insertelement <36 x half> %vecins.14, half %19, i64 15
  %20 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 32), align 4, !tbaa !12
  %vecins.16 = insertelement <36 x half> %vecins.15, half %20, i64 16
  %21 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 34), align 2, !tbaa !12
  %vecins.17 = insertelement <36 x half> %vecins.16, half %21, i64 17
  %22 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 36), align 4, !tbaa !12
  %vecins.18 = insertelement <36 x half> %vecins.17, half %22, i64 18
  %23 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 38), align 2, !tbaa !12
  %vecins.19 = insertelement <36 x half> %vecins.18, half %23, i64 19
  %24 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 40), align 4, !tbaa !12
  %vecins.20 = insertelement <36 x half> %vecins.19, half %24, i64 20
  %25 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 42), align 2, !tbaa !12
  %vecins.21 = insertelement <36 x half> %vecins.20, half %25, i64 21
  %26 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 44), align 4, !tbaa !12
  %vecins.22 = insertelement <36 x half> %vecins.21, half %26, i64 22
  %27 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 46), align 2, !tbaa !12
  %vecins.23 = insertelement <36 x half> %vecins.22, half %27, i64 23
  %28 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 48), align 4, !tbaa !12
  %vecins.24 = insertelement <36 x half> %vecins.23, half %28, i64 24
  %29 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 50), align 2, !tbaa !12
  %vecins.25 = insertelement <36 x half> %vecins.24, half %29, i64 25
  %30 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 52), align 4, !tbaa !12
  %vecins.26 = insertelement <36 x half> %vecins.25, half %30, i64 26
  %31 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 54), align 2, !tbaa !12
  %vecins.27 = insertelement <36 x half> %vecins.26, half %31, i64 27
  %32 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 56), align 4, !tbaa !12
  %vecins.28 = insertelement <36 x half> %vecins.27, half %32, i64 28
  %33 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 58), align 2, !tbaa !12
  %vecins.29 = insertelement <36 x half> %vecins.28, half %33, i64 29
  %34 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 60), align 4, !tbaa !12
  %vecins.30 = insertelement <36 x half> %vecins.29, half %34, i64 30
  %35 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 62), align 2, !tbaa !12
  %vecins.31 = insertelement <36 x half> %vecins.30, half %35, i64 31
  %36 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 64), align 4, !tbaa !12
  %vecins.32 = insertelement <36 x half> %vecins.31, half %36, i64 32
  %37 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 66), align 2, !tbaa !12
  %vecins.33 = insertelement <36 x half> %vecins.32, half %37, i64 33
  %38 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 68), align 4, !tbaa !12
  %vecins.34 = insertelement <36 x half> %vecins.33, half %38, i64 34
  %39 = load half, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @weights, i32 70), align 2, !tbaa !12
  %vecins.35 = insertelement <36 x half> %vecins.34, half %39, i64 35
  %40 = load <6 x half>, ptr addrspace(10) @color, align 4, !tbaa !14
  %41 = load <6 x half>, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @color, i32 12), align 4, !tbaa !14
  %42 = load <6 x half>, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @color, i32 24), align 4, !tbaa !14
  %43 = tail call contract <4 x float> @llvm.amdgcn.convolve.f32.f16.3x3.v4f32.v4f32.v36f16.v6f16(<4 x float> zeroinitializer, <36 x half> %vecins.35, <6 x half> %40, <6 x half> %41, <6 x half> %42, i32 11, i1 true)
  %vecext = extractelement <4 x float> %43, i64 0
  store float %vecext, ptr addrspace(10) @out, align 4, !tbaa !15
  %vecext.1 = extractelement <4 x float> %43, i64 1
  store float %vecext.1, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @out, i32 4), align 4, !tbaa !15
  %vecext.2 = extractelement <4 x float> %43, i64 2
  store float %vecext.2, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @out, i32 8), align 4, !tbaa !15
  %vecext.3 = extractelement <4 x float> %43, i64 3
  store float %vecext.3, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @out, i32 12), align 4, !tbaa !15
  ret void
}

; Function Attrs: convergent mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <4 x float> @llvm.amdgcn.convolve.f32.f16.3x3.v4f32.v4f32.v36f16.v6f16(<4 x float>, <36 x half>, <6 x half>, <6 x half>, <6 x half>, i32 immarg, i1 immarg) #2

attributes #2 = { convergent mustprogress nocallback nofree nosync nounwind willreturn memory(none) }

!4 = !{i32 128, i32 1, i32 1}
!5 = !{!6, !6, i64 0}
!6 = !{!"int", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C++ TBAA"}
!9 = distinct !{!9, !10, !11}
!10 = !{!"llvm.loop.mustprogress"}
!11 = !{!"llvm.loop.unroll.disable"}
!12 = !{!13, !13, i64 0}
!13 = !{!"__fp16", !7, i64 0}
!14 = !{!7, !7, i64 0}
!15 = !{!16, !16, i64 0}
!16 = !{!"float", !7, i64 0}
