; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes='sroa<modify-cfg>' -sroa-max-struct-to-vector-bytes=16 < %s | FileCheck %s
; RUN: opt -S -passes='sroa<modify-cfg>' -sroa-max-struct-to-vector-bytes=0  < %s | FileCheck %s --check-prefix=DISABLED

%v4i32 = type { i32, i32, i32, i32 }

@zeros = internal constant %v4i32 zeroinitializer, align 16

; This models: ptr select of homogeneous struct feeding a memcpy.
; The change in SROA adds a canonicalization that treats such structs
; as fixed vectors, enabling SROA to rewrite the memcpy as a vector select.

declare void @llvm.memcpy.p0.p0.i64(ptr nocapture writeonly, ptr nocapture readonly, i64, i1 immarg)
declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)

; Model the original bad.ll shape:
;   br i1 %c, label %cond.true, label %cond.false
;   %cond190 = phi ptr [ %row, %cond.true ], [ @zeros, %cond.false ]
;   call @llvm.memcpy(..., %cond190, 16, false)
;
; SROA with struct-to-vector enabled should eliminate the memcpy and form a
; vector select feeding the final store.
define void @test_memcpy_from_phi_ptr_to_struct(ptr %out, i1 %c, ptr %src) {
; CHECK-LABEL: @test_memcpy_from_phi_ptr_to_struct(
; CHECK-NOT: call void @llvm.memcpy
; CHECK-NOT: alloca
; CHECK: [[VROW:%.*]] = load <4 x i32>, ptr %src, align 16
; CHECK: [[SEL:%.*]] = select i1 [[C:%.*]], <4 x i32> [[VROW]], <4 x i32> zeroinitializer
; CHECK: store <4 x i32> [[SEL]], ptr [[OUT:%.*]], align 16
; DISABLED-LABEL: @test_memcpy_from_phi_ptr_to_struct(
; DISABLED: call void @llvm.memcpy
entry:
  %row = alloca %v4i32, align 16
  call void @llvm.lifetime.start.p0(i64 16, ptr %row)
  call void @llvm.memcpy.p0.p0.i64(ptr align 16 %row, ptr align 16 %src, i64 16, i1 false)

  br i1 %c, label %cond.true, label %cond.false

cond.true:                                         ; preds = %entry
  br label %cond.end

cond.false:                                        ; preds = %entry
  br label %cond.end

cond.end:                                          ; preds = %cond.false, %cond.true
  %cond190 = phi ptr [ %row, %cond.true ], [ @zeros, %cond.false ]

  %dst = alloca %v4i32, align 16
  call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %cond190, i64 16, i1 false)
  %v = load <4 x i32>, ptr %dst, align 16
  store <4 x i32> %v, ptr %out, align 16
  call void @llvm.lifetime.end.p0(i64 16, ptr %row)
  ret void
}

; Array element version mirroring bad.ll: select between an array element
; pointer (%row_data_v[inner_i]) and a zero struct, then memcpy.
; Expect SROA to eliminate memcpy and form a vector select when enabled.
define <4 x i32> @test_array_elem_phi_memcpy(i1 %c, i32 %idx, ptr %src) {
; CHECK-LABEL: @test_array_elem_phi_memcpy(
; CHECK-NOT: alloca
; CHECK: [[IDXZ:%.*]] = zext i32 [[IDX:%.*]] to i64
; CHECK: [[ARRAYIDX:%.*]] = getelementptr inbounds [4 x { i32, i32, i32, i32 }], ptr [[ROW_DATA_V:%.*]], i64 0, i64 [[IDXZ]]
; CHECK: [[VLOAD:%.*]] = load <4 x i32>, ptr [[ARRAYIDX]], align 16
; CHECK: [[VPHI:%.*]] = phi <4 x i32> [ [[VLOAD]], [[COND_TRUE:%.*]] ], [ zeroinitializer, [[COND_FALSE:%.*]] ]
; CHECK: ret <4 x i32> [[VPHI]]
; DISABLED-LABEL: @test_array_elem_phi_memcpy(
; DISABLED: call void @llvm.memcpy
entry:
  %row_data_v = alloca [4 x %v4i32], align 16
  call void @llvm.lifetime.start.p0(i64 64, ptr %row_data_v)
  %idxz = zext i32 %idx to i64
  %arrayidx = getelementptr inbounds [4 x %v4i32], ptr %row_data_v, i64 0, i64 %idxz
  call void @llvm.memcpy.p0.p0.i64(ptr align 16 %arrayidx, ptr align 16 %src, i64 16, i1 false)

  br i1 %c, label %cond.true, label %cond.false

cond.true:
  %vload = load <4 x i32>, ptr %arrayidx, align 16
  br label %cond.end

cond.false:
  br label %cond.end

cond.end:
  %vphi = phi <4 x i32> [ %vload, %cond.true ], [ zeroinitializer, %cond.false ]
  call void @llvm.lifetime.end.p0(i64 64, ptr %row_data_v)
  ret <4 x i32> %vphi
}
