// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu gfx1260 -target-feature +wavefrontsize32 -emit-llvm -o - %s | FileCheck %s --check-prefix=CHECK-GFX1260
// REQUIRES: amdgpu-registered-target

typedef float  v16f  __attribute__((ext_vector_type(16)));
typedef float  v8f   __attribute__((ext_vector_type(8)));
typedef half   v8h   __attribute__((ext_vector_type(8)));
typedef half   v16h  __attribute__((ext_vector_type(16)));
typedef half   v32h  __attribute__((ext_vector_type(32)));
typedef __bf16 v32bf16 __attribute__((ext_vector_type(32)));
typedef __bf16 v16bf16 __attribute__((ext_vector_type(16)));
typedef __bf16 v8bf16 __attribute__((ext_vector_type(8)));
typedef int    v16i   __attribute__((ext_vector_type(16)));
typedef int    v8i   __attribute__((ext_vector_type(8)));

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f32_16x16x32_bf16_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 32)) [[OUT:%.*]], <16 x bfloat> noundef [[A:%.*]], <16 x bfloat> noundef [[B:%.*]], <8 x float> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x32.bf16.pred.xdl.v8f32.v16bf16(<16 x bfloat> [[A]], i16 0, <16 x bfloat> [[B]], i16 0, <8 x float> [[C]], i1 true, i1 false, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT]], align 32, !tbaa [[CHAR_TBAA8:![0-9]+]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x32_bf16_pred_xdl(global v8f* out, v16bf16 a, v16bf16 b, v8f c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f32_16x16x32_bf16_pred_xdl(a, 0, b, 0, c, true, false, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f32_16x16x32_f16_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 32)) [[OUT:%.*]], <16 x half> noundef [[A:%.*]], <16 x half> noundef [[B:%.*]], <8 x float> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x32.f16.pred.xdl.v8f32.v16f16(<16 x half> [[A]], i16 0, <16 x half> [[B]], i16 0, <8 x float> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT]], align 32, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x32_f16_pred_xdl(global v8f* out, v16h a, v16h b, v8f c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f32_16x16x32_f16_pred_xdl(a, 0, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f16_16x16x32_f16_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[OUT:%.*]], <16 x half> noundef [[A:%.*]], <16 x half> noundef [[B:%.*]], <8 x half> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x32.f16.pred.xdl.v8f16.v16f16(<16 x half> [[A]], i16 0, <16 x half> [[B]], i16 0, <8 x half> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT]], align 16, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x32_f16_pred_xdl(global v8h* out, v16h a, v16h b, v8h c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f16_16x16x32_f16_pred_xdl(a, 0, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_bf16_16x16x32_bf16_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[OUT:%.*]], <16 x bfloat> noundef [[A:%.*]], <16 x bfloat> noundef [[B:%.*]], <8 x bfloat> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.wmma.bf16.16x16x32.bf16.pred.xdl.v8bf16.v16bf16(<16 x bfloat> [[A]], i16 0, <16 x bfloat> [[B]], i16 0, <8 x bfloat> [[C]], i1 false, i1 false, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT]], align 16, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_bf16_16x16x32_bf16_pred_xdl(global v8bf16* out, v16bf16 a, v16bf16 b, v8bf16 c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_bf16_16x16x32_bf16_pred_xdl(a, 0, b, 0, c, false, false, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_bf16f32_16x16x32_bf16_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[OUT:%.*]], <16 x bfloat> noundef [[A:%.*]], <16 x bfloat> noundef [[B:%.*]], <8 x float> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.wmma.bf16f32.16x16x32.bf16.pred.xdl.v8bf16.v16bf16.v8f32(<16 x bfloat> [[A]], i16 0, <16 x bfloat> [[B]], i16 0, <8 x float> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT]], align 16, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_bf16f32_16x16x32_bf16_pred_xdl(global v8bf16* out, v16bf16 a, v16bf16 b, v8f c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_bf16f32_16x16x32_bf16_pred_xdl(a, 0, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f32_16x16x64_fp8_fp8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 32)) [[OUT:%.*]], <8 x i32> noundef [[A:%.*]], <8 x i32> noundef [[B:%.*]], <8 x float> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x64.fp8.fp8.pred.xdl.v8f32.v8i32(<8 x i32> [[A]], <8 x i32> [[B]], i16 0, <8 x float> [[C]], i1 true, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT]], align 32, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x64_fp8_fp8_pred_xdl(global v8f* out, v8i a, v8i b, v8f c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f32_16x16x64_fp8_fp8_pred_xdl(a, b, 0, c, true, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f32_16x16x64_fp8_bf8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 32)) [[OUT:%.*]], <8 x i32> noundef [[A:%.*]], <8 x i32> noundef [[B:%.*]], <8 x float> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x64.fp8.bf8.pred.xdl.v8f32.v8i32(<8 x i32> [[A]], <8 x i32> [[B]], i16 0, <8 x float> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT]], align 32, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x64_fp8_bf8_pred_xdl(global v8f* out, v8i a, v8i b, v8f c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f32_16x16x64_fp8_bf8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f32_16x16x64_bf8_fp8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 32)) [[OUT:%.*]], <8 x i32> noundef [[A:%.*]], <8 x i32> noundef [[B:%.*]], <8 x float> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x64.bf8.fp8.pred.xdl.v8f32.v8i32(<8 x i32> [[A]], <8 x i32> [[B]], i16 0, <8 x float> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT]], align 32, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x64_bf8_fp8_pred_xdl(global v8f* out, v8i a, v8i b, v8f c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f32_16x16x64_bf8_fp8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f32_16x16x64_bf8_bf8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 32)) [[OUT:%.*]], <8 x i32> noundef [[A:%.*]], <8 x i32> noundef [[B:%.*]], <8 x float> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x64.bf8.bf8.pred.xdl.v8f32.v8i32(<8 x i32> [[A]], <8 x i32> [[B]], i16 0, <8 x float> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT]], align 32, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x64_bf8_bf8_pred_xdl(global v8f* out, v8i a, v8i b, v8f c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f32_16x16x64_bf8_bf8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f16_16x16x64_fp8_fp8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[OUT:%.*]], <8 x i32> noundef [[A:%.*]], <8 x i32> noundef [[B:%.*]], <8 x half> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x64.fp8.fp8.pred.xdl.v8f16.v8i32(<8 x i32> [[A]], <8 x i32> [[B]], i16 0, <8 x half> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT]], align 16, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x64_fp8_fp8_pred_xdl(global v8h* out, v8i a, v8i b, v8h c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f16_16x16x64_fp8_fp8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f16_16x16x64_fp8_bf8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[OUT:%.*]], <8 x i32> noundef [[A:%.*]], <8 x i32> noundef [[B:%.*]], <8 x half> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x64.fp8.bf8.pred.xdl.v8f16.v8i32(<8 x i32> [[A]], <8 x i32> [[B]], i16 0, <8 x half> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT]], align 16, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x64_fp8_bf8_pred_xdl(global v8h* out, v8i a, v8i b, v8h c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f16_16x16x64_fp8_bf8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f16_16x16x64_bf8_fp8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[OUT:%.*]], <8 x i32> noundef [[A:%.*]], <8 x i32> noundef [[B:%.*]], <8 x half> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x64.bf8.fp8.pred.xdl.v8f16.v8i32(<8 x i32> [[A]], <8 x i32> [[B]], i16 0, <8 x half> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT]], align 16, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x64_bf8_fp8_pred_xdl(global v8h* out, v8i a, v8i b, v8h c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f16_16x16x64_bf8_fp8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f16_16x16x64_bf8_bf8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[OUT:%.*]], <8 x i32> noundef [[A:%.*]], <8 x i32> noundef [[B:%.*]], <8 x half> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x64.bf8.bf8.pred.xdl.v8f16.v8i32(<8 x i32> [[A]], <8 x i32> [[B]], i16 0, <8 x half> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT]], align 16, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x64_bf8_bf8_pred_xdl(global v8h* out, v8i a, v8i b, v8h c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f16_16x16x64_bf8_bf8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f16_16x16x128_fp8_fp8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[OUT:%.*]], <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], <8 x half> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x128.fp8.fp8.pred.xdl.v8f16.v16i32(<16 x i32> [[A]], <16 x i32> [[B]], i16 0, <8 x half> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT]], align 16, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x128_fp8_fp8_pred_xdl(global v8h* out, v16i a, v16i b, v8h c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f16_16x16x128_fp8_fp8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f16_16x16x128_fp8_bf8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[OUT:%.*]], <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], <8 x half> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x128.fp8.bf8.pred.xdl.v8f16.v16i32(<16 x i32> [[A]], <16 x i32> [[B]], i16 0, <8 x half> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT]], align 16, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x128_fp8_bf8_pred_xdl(global v8h* out, v16i a, v16i b, v8h c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f16_16x16x128_fp8_bf8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f16_16x16x128_bf8_fp8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[OUT:%.*]], <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], <8 x half> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x128.bf8.fp8.pred.xdl.v8f16.v16i32(<16 x i32> [[A]], <16 x i32> [[B]], i16 0, <8 x half> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT]], align 16, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x128_bf8_fp8_pred_xdl(global v8h* out, v16i a, v16i b, v8h c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f16_16x16x128_bf8_fp8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f16_16x16x128_bf8_bf8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[OUT:%.*]], <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], <8 x half> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x128.bf8.bf8.pred.xdl.v8f16.v16i32(<16 x i32> [[A]], <16 x i32> [[B]], i16 0, <8 x half> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT]], align 16, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x128_bf8_bf8_pred_xdl(global v8h* out, v16i a, v16i b, v8h c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f16_16x16x128_bf8_bf8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f32_16x16x128_fp8_fp8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 32)) [[OUT:%.*]], <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], <8 x float> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x128.fp8.fp8.pred.xdl.v8f32.v16i32(<16 x i32> [[A]], <16 x i32> [[B]], i16 0, <8 x float> [[C]], i1 true, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT]], align 32, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x128_fp8_fp8_pred_xdl(global v8f* out, v16i a, v16i b, v8f c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f32_16x16x128_fp8_fp8_pred_xdl(a, b, 0, c, true, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f32_16x16x128_fp8_bf8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 32)) [[OUT:%.*]], <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], <8 x float> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x128.fp8.bf8.pred.xdl.v8f32.v16i32(<16 x i32> [[A]], <16 x i32> [[B]], i16 0, <8 x float> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT]], align 32, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x128_fp8_bf8_pred_xdl(global v8f* out, v16i a, v16i b, v8f c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f32_16x16x128_fp8_bf8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f32_16x16x128_bf8_fp8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 32)) [[OUT:%.*]], <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], <8 x float> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x128.bf8.fp8.pred.xdl.v8f32.v16i32(<16 x i32> [[A]], <16 x i32> [[B]], i16 0, <8 x float> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT]], align 32, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x128_bf8_fp8_pred_xdl(global v8f* out, v16i a, v16i b, v8f c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f32_16x16x128_bf8_fp8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_f32_16x16x128_bf8_bf8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 32)) [[OUT:%.*]], <16 x i32> noundef [[A:%.*]], <16 x i32> noundef [[B:%.*]], <8 x float> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x128.bf8.bf8.pred.xdl.v8f32.v16i32(<16 x i32> [[A]], <16 x i32> [[B]], i16 0, <8 x float> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]])
// CHECK-GFX1260-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT]], align 32, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x128_bf8_bf8_pred_xdl(global v8f* out, v16i a, v16i b, v8f c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_f32_16x16x128_bf8_bf8_pred_xdl(a, b, 0, c, false, true, custom_shape);
}

// CHECK-GFX1260-LABEL: define dso_local void @test_amdgcn_wmma_i32_16x16x64_iu8_pred_xdl(
// CHECK-GFX1260-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 32)) [[OUT:%.*]], <8 x i32> noundef [[A:%.*]], <8 x i32> noundef [[B:%.*]], <8 x i32> noundef [[C:%.*]], i32 noundef [[CUSTOM_SHAPE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-GFX1260-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1260-NEXT:    [[TMP0:%.*]] = tail call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x64.iu8.pred.xdl.v8i32.v8i32(i16 0, <8 x i32> [[A]], i16 0, <8 x i32> [[B]], <8 x i32> [[C]], i1 false, i1 true, i32 [[CUSTOM_SHAPE]], i1 false)
// CHECK-GFX1260-NEXT:    store <8 x i32> [[TMP0]], ptr addrspace(1) [[OUT]], align 32, !tbaa [[CHAR_TBAA8]]
// CHECK-GFX1260-NEXT:    ret void
//
void test_amdgcn_wmma_i32_16x16x64_iu8_pred_xdl(global v8i* out, v8i a, v8i b, v8i c, int custom_shape)
{
  *out = __builtin_amdgcn_wmma_i32_16x16x64_iu8_pred_xdl(0, a, 0, b, c, false, true, custom_shape, false);
}
//.
// CHECK-GFX1260: [[META6:![0-9]+]] = !{!"omnipotent char", [[META7:![0-9]+]], i64 0}
// CHECK-GFX1260: [[META7]] = !{!"Simple C/C++ TBAA"}
// CHECK-GFX1260: [[CHAR_TBAA8]] = !{[[META6]], [[META6]], i64 0}
//.
