// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu gfx1370 -target-feature +wavefrontsize32 -emit-llvm -o - %s | FileCheck %s --check-prefix=CHECK-GFX1370

typedef int    v4i   __attribute__((ext_vector_type(4)));

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_global_tiled_load_2x2_b128(
// CHECK-GFX1370-SAME: ptr addrspace(1) noundef align 16 captures(none) [[PTR:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] !kernel_arg_addr_space [[META8:![0-9]+]] !kernel_arg_access_qual [[META9:![0-9]+]] !kernel_arg_type [[META10:![0-9]+]] !kernel_arg_base_type [[META11:![0-9]+]] !kernel_arg_type_qual [[META12:![0-9]+]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.global.tiled.load.2x2.b128(ptr addrspace(1) align 16 [[PTR]])
// CHECK-GFX1370-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[PTR]], align 16, !tbaa [[TBAA13:![0-9]+]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_global_tiled_load_2x2_b128(global v4i* ptr)
{
   *ptr = __builtin_amdgcn_global_tiled_load_2x2_b128(ptr);
}
//.
// CHECK-GFX1370: [[META6:![0-9]+]] = !{!"omnipotent char", [[META7:![0-9]+]], i64 0}
// CHECK-GFX1370: [[META7]] = !{!"Simple C/C++ TBAA"}
// CHECK-GFX1370: [[META8]] = !{i32 1}
// CHECK-GFX1370: [[META9]] = !{!"none"}
// CHECK-GFX1370: [[META10]] = !{!"v4i*"}
// CHECK-GFX1370: [[META11]] = !{!"int __attribute__((ext_vector_type(4)))*"}
// CHECK-GFX1370: [[META12]] = !{!""}
// CHECK-GFX1370: [[TBAA13]] = !{[[META6]], [[META6]], i64 0}
//.
