// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -cl-std=CL2.0 -triple amdgcn-unknown-unknown -target-cpu gfx1260 -emit-llvm -o - %s | FileCheck %s --check-prefix=GFX1260

typedef int v2i __attribute__((ext_vector_type(2)));

// GFX1260-LABEL: @test_amdgcn_ds_block_load_mcast_b128(
// GFX1260-NEXT:  entry:
// GFX1260-NEXT:    tail call void @llvm.amdgcn.ds.block.load.mcast.b128(ptr addrspace(10) [[OUTPTR:%.*]], <2 x i32> [[VSRC:%.*]], i16 257)
// GFX1260-NEXT:    ret void
//
void test_amdgcn_ds_block_load_mcast_b128(__attribute__((address_space(10))) int* outptr, v2i vsrc)
{
  __builtin_amdgcn_ds_block_load_mcast_b128(outptr, vsrc, 257);
}

// GFX1260-LABEL: @test_amdgcn_ds_block_load_mcast_b256(
// GFX1260-NEXT:  entry:
// GFX1260-NEXT:    tail call void @llvm.amdgcn.ds.block.load.mcast.b256(ptr addrspace(10) [[OUTPTR:%.*]], <2 x i32> [[VSRC:%.*]], i16 257)
// GFX1260-NEXT:    ret void
//
void test_amdgcn_ds_block_load_mcast_b256(__attribute__((address_space(10))) int* outptr, v2i vsrc)
{
  __builtin_amdgcn_ds_block_load_mcast_b256(outptr, vsrc, 257);
}

// GFX1260-LABEL: @test_amdgcn_ds_block_load_mcast_b512(
// GFX1260-NEXT:  entry:
// GFX1260-NEXT:    tail call void @llvm.amdgcn.ds.block.load.mcast.b512(ptr addrspace(10) [[OUTPTR:%.*]], <2 x i32> [[VSRC:%.*]], i16 257)
// GFX1260-NEXT:    ret void
//
void test_amdgcn_ds_block_load_mcast_b512(__attribute__((address_space(10))) int* outptr, v2i vsrc)
{
  __builtin_amdgcn_ds_block_load_mcast_b512(outptr, vsrc, 257);
}

// GFX1260-LABEL: @test_amdgcn_ds_block_load_mcast_b1024(
// GFX1260-NEXT:  entry:
// GFX1260-NEXT:    tail call void @llvm.amdgcn.ds.block.load.mcast.b1024(ptr addrspace(10) [[OUTPTR:%.*]], <2 x i32> [[VSRC:%.*]], i16 257)
// GFX1260-NEXT:    ret void
//
void test_amdgcn_ds_block_load_mcast_b1024(__attribute__((address_space(10))) int* outptr, v2i vsrc)
{
  __builtin_amdgcn_ds_block_load_mcast_b1024(outptr, vsrc, 257);
}
