// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu gfx1370 -target-feature +wavefrontsize32 -target-feature +lds-tiled-loads -emit-llvm -o - %s | FileCheck %s --check-prefix=CHECK-GFX1370

typedef int v2i __attribute__((ext_vector_type(2)));
typedef int v3i __attribute__((ext_vector_type(3)));
typedef int v4i __attribute__((ext_vector_type(4)));
typedef signed char    v8c   __attribute__((ext_vector_type(8)));
typedef unsigned char  v8uc  __attribute__((ext_vector_type(8)));
typedef signed char    v16c  __attribute__((ext_vector_type(16)));
typedef unsigned char  v16uc __attribute__((ext_vector_type(16)));

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_ds_tiled_load_half_b64(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly align 4 captures(none) [[SRC:%.*]], ptr addrspace(1) noundef writeonly align 4 captures(none) initializes((0, 4)) [[DST:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] !kernel_arg_addr_space [[META8:![0-9]+]] !kernel_arg_access_qual [[META9:![0-9]+]] !kernel_arg_type [[META10:![0-9]+]] !kernel_arg_base_type [[META10]] !kernel_arg_type_qual [[META11:![0-9]+]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.amdgcn.ds.tiled.load.half.b64(ptr addrspace(3) readonly align 4 [[SRC]])
// CHECK-GFX1370-NEXT:    store i32 [[TMP0]], ptr addrspace(1) [[DST]], align 4, !tbaa [[TBAA4:![0-9]+]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_ds_tiled_load_half_b64(local int *src, global int *dst) {
  *dst = __builtin_amdgcn_ds_tiled_load_half_b64(src);
}

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_ds_tiled_load_b64(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly align 8 captures(none) [[SRC:%.*]], ptr addrspace(1) noundef writeonly align 8 captures(none) initializes((0, 8)) [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] !kernel_arg_addr_space [[META8]] !kernel_arg_access_qual [[META9]] !kernel_arg_type [[META12:![0-9]+]] !kernel_arg_base_type [[META13:![0-9]+]] !kernel_arg_type_qual [[META11]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.amdgcn.ds.tiled.load.b64(ptr addrspace(3) readonly align 8 [[SRC]])
// CHECK-GFX1370-NEXT:    store <2 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 8, !tbaa [[TBAA14:![0-9]+]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_ds_tiled_load_b64(local v2i *src, global v2i *dst) {
  *dst = __builtin_amdgcn_ds_tiled_load_b64(src);
}

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_ds_tiled_load_2x2_b128(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly align 16 captures(none) [[SRC:%.*]], ptr addrspace(1) noundef writeonly align 16 captures(none) initializes((0, 16)) [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] !kernel_arg_addr_space [[META8]] !kernel_arg_access_qual [[META9]] !kernel_arg_type [[META15:![0-9]+]] !kernel_arg_base_type [[META16:![0-9]+]] !kernel_arg_type_qual [[META11]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.ds.tiled.load.2x2.b128(ptr addrspace(3) readonly align 16 [[SRC]])
// CHECK-GFX1370-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 16, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_ds_tiled_load_2x2_b128(local v4i *src, global v4i *dst) {
  *dst = __builtin_amdgcn_ds_tiled_load_2x2_b128(src);
}

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_ds_tiled_load_b128(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly align 16 captures(none) [[SRC:%.*]], ptr addrspace(1) noundef writeonly align 16 captures(none) initializes((0, 16)) [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] !kernel_arg_addr_space [[META8]] !kernel_arg_access_qual [[META9]] !kernel_arg_type [[META15]] !kernel_arg_base_type [[META16]] !kernel_arg_type_qual [[META11]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.ds.tiled.load.b128(ptr addrspace(3) readonly align 16 [[SRC]])
// CHECK-GFX1370-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 16, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_ds_tiled_load_b128(local v4i *src, global v4i *dst) {
  *dst = __builtin_amdgcn_ds_tiled_load_b128(src);
}

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_ds_tiled_load_mcast_half_b64(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly align 4 captures(none) [[SRC:%.*]], ptr addrspace(1) noundef writeonly align 4 captures(none) initializes((0, 4)) [[DST:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] !kernel_arg_addr_space [[META17:![0-9]+]] !kernel_arg_access_qual [[META18:![0-9]+]] !kernel_arg_type [[META19:![0-9]+]] !kernel_arg_base_type [[META19]] !kernel_arg_type_qual [[META20:![0-9]+]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.amdgcn.ds.tiled.load.mcast.half.b64(ptr addrspace(3) readonly align 4 [[SRC]], i32 [[MASK]])
// CHECK-GFX1370-NEXT:    store i32 [[TMP0]], ptr addrspace(1) [[DST]], align 4, !tbaa [[TBAA4]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_ds_tiled_load_mcast_half_b64(local int *src, global int *dst, int mask) {
  *dst = __builtin_amdgcn_ds_tiled_load_mcast_half_b64(src, mask);
}

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_ds_tiled_load_mcast_b64(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly align 8 captures(none) [[SRC:%.*]], ptr addrspace(1) noundef writeonly align 8 captures(none) initializes((0, 8)) [[DST:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR2]] !kernel_arg_addr_space [[META17]] !kernel_arg_access_qual [[META18]] !kernel_arg_type [[META21:![0-9]+]] !kernel_arg_base_type [[META22:![0-9]+]] !kernel_arg_type_qual [[META20]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.amdgcn.ds.tiled.load.mcast.b64(ptr addrspace(3) readonly align 8 [[SRC]], i32 [[MASK]])
// CHECK-GFX1370-NEXT:    store <2 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 8, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_ds_tiled_load_mcast_b64(local v2i *src, global v2i *dst, int mask) {
  *dst = __builtin_amdgcn_ds_tiled_load_mcast_b64(src, mask);
}

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_ds_tiled_load_mcast_b128(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly align 16 captures(none) [[SRC:%.*]], ptr addrspace(1) noundef writeonly align 16 captures(none) initializes((0, 16)) [[DST:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR2]] !kernel_arg_addr_space [[META17]] !kernel_arg_access_qual [[META18]] !kernel_arg_type [[META23:![0-9]+]] !kernel_arg_base_type [[META24:![0-9]+]] !kernel_arg_type_qual [[META20]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.ds.tiled.load.mcast.b128(ptr addrspace(3) readonly align 16 [[SRC]], i32 [[MASK]])
// CHECK-GFX1370-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 16, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_ds_tiled_load_mcast_b128(local v4i *src, global v4i *dst, int mask) {
  *dst = __builtin_amdgcn_ds_tiled_load_mcast_b128(src, mask);
}

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_ds_tiled_load_mcast_2x2_b128(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly align 16 captures(none) [[SRC:%.*]], ptr addrspace(1) noundef writeonly align 16 captures(none) initializes((0, 16)) [[DST:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR2]] !kernel_arg_addr_space [[META17]] !kernel_arg_access_qual [[META18]] !kernel_arg_type [[META23]] !kernel_arg_base_type [[META24]] !kernel_arg_type_qual [[META20]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.ds.tiled.load.mcast.2x2.b128(ptr addrspace(3) readonly align 16 [[SRC]], i32 [[MASK]])
// CHECK-GFX1370-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 16, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_ds_tiled_load_mcast_2x2_b128(local v4i *src, global v4i *dst, int mask) {
  *dst = __builtin_amdgcn_ds_tiled_load_mcast_2x2_b128(src, mask);
}

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_ds_load_mcast_tr4_b64(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly align 8 captures(none) [[SRC:%.*]], ptr addrspace(1) noundef writeonly align 8 captures(none) initializes((0, 8)) [[DST:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR2]] !kernel_arg_addr_space [[META17]] !kernel_arg_access_qual [[META18]] !kernel_arg_type [[META21]] !kernel_arg_base_type [[META22]] !kernel_arg_type_qual [[META20]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.amdgcn.ds.load.mcast.tr4.b64(ptr addrspace(3) readonly align 8 [[SRC]], i32 [[MASK]])
// CHECK-GFX1370-NEXT:    store <2 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 8, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_ds_load_mcast_tr4_b64(local v2i *src, global v2i *dst, int mask) {
  *dst = __builtin_amdgcn_ds_load_mcast_tr4_b64(src, mask);
}

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_ds_load_mcast_tr6_b96(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly align 16 captures(none) [[SRC:%.*]], ptr addrspace(1) noundef writeonly align 16 captures(none) initializes((0, 12)) [[DST:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR2]] !kernel_arg_addr_space [[META17]] !kernel_arg_access_qual [[META18]] !kernel_arg_type [[META25:![0-9]+]] !kernel_arg_base_type [[META26:![0-9]+]] !kernel_arg_type_qual [[META20]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <3 x i32> @llvm.amdgcn.ds.load.mcast.tr6.b96(ptr addrspace(3) readonly align 16 [[SRC]], i32 [[MASK]])
// CHECK-GFX1370-NEXT:    store <3 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 16, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_ds_load_mcast_tr6_b96(local v3i *src, global v3i *dst, int mask) {
  *dst = __builtin_amdgcn_ds_load_mcast_tr6_b96(src, mask);
}

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_ds_load_mcast_tr8_b64(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly align 8 captures(none) [[SRC:%.*]], ptr addrspace(1) noundef writeonly align 8 captures(none) initializes((0, 8)) [[DST:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR2]] !kernel_arg_addr_space [[META17]] !kernel_arg_access_qual [[META18]] !kernel_arg_type [[META21]] !kernel_arg_base_type [[META22]] !kernel_arg_type_qual [[META20]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.amdgcn.ds.load.mcast.tr8.b64(ptr addrspace(3) readonly align 8 [[SRC]], i32 [[MASK]])
// CHECK-GFX1370-NEXT:    store <2 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 8, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_ds_load_mcast_tr8_b64(local v2i *src, global v2i *dst, int mask) {
  *dst = __builtin_amdgcn_ds_load_mcast_tr8_b64(src, mask);
}

// CHECK-GFX1370-LABEL: define dso_local amdgpu_kernel void @test_ds_load_mcast_tr16_b128(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly align 16 captures(none) [[SRC:%.*]], ptr addrspace(1) noundef writeonly align 16 captures(none) initializes((0, 16)) [[DST:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR2]] !kernel_arg_addr_space [[META17]] !kernel_arg_access_qual [[META18]] !kernel_arg_type [[META23]] !kernel_arg_base_type [[META24]] !kernel_arg_type_qual [[META20]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.ds.load.mcast.tr16.b128(ptr addrspace(3) readonly align 16 [[SRC]], i32 [[MASK]])
// CHECK-GFX1370-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 16, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void kernel test_ds_load_mcast_tr16_b128(local v4i *src, global v4i *dst, int mask) {
  *dst = __builtin_amdgcn_ds_load_mcast_tr16_b128(src, mask);
}


// Test with bitsize argument (1, 2, or 4) which gets translated to format

// CHECK-GFX1370-LABEL: define dso_local void @test_amdgcn_tiled_load_mcast_extend_b64_sign_bitsize1(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly captures(none) [[INPTR:%.*]], ptr addrspace(1) noundef writeonly captures(none) initializes((0, 8)) [[DST:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.amdgcn.ds.tiled.load.mcast.extend.b64(ptr addrspace(3) [[INPTR]], i32 1, i32 [[MASK]])
// CHECK-GFX1370-NEXT:    store <2 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 8, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void test_amdgcn_tiled_load_mcast_extend_b64_sign_bitsize1(local v2i* inptr, global v8c* dst, int mask)
{
  *dst = __builtin_amdgcn_ds_tiled_load_mcast_extend_b64_sign(inptr, 1, mask);
}

// CHECK-GFX1370-LABEL: define dso_local void @test_amdgcn_tiled_load_mcast_extend_b64_zero_bitsize2(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly captures(none) [[INPTR:%.*]], ptr addrspace(1) noundef writeonly captures(none) initializes((0, 8)) [[DST:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.amdgcn.ds.tiled.load.mcast.extend.b64(ptr addrspace(3) [[INPTR]], i32 2, i32 [[MASK]])
// CHECK-GFX1370-NEXT:    store <2 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 8, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void test_amdgcn_tiled_load_mcast_extend_b64_zero_bitsize2(local v2i* inptr, global v8uc* dst, int mask)
{
  *dst = __builtin_amdgcn_ds_tiled_load_mcast_extend_b64_zero(inptr, 2, mask);
}

// CHECK-GFX1370-LABEL: define dso_local void @test_amdgcn_tiled_load_mcast_2x2_extend_b128_sign_bitsize4(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly captures(none) [[INPTR:%.*]], ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[DST:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.ds.tiled.load.mcast.2x2.extend.b128(ptr addrspace(3) [[INPTR]], i32 5, i32 [[MASK]])
// CHECK-GFX1370-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 16, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void test_amdgcn_tiled_load_mcast_2x2_extend_b128_sign_bitsize4(local v4i* inptr, global v16c* dst, int mask)
{
  *dst = __builtin_amdgcn_ds_tiled_load_mcast_2x2_extend_b128_sign(inptr, 4, mask);
}

// CHECK-GFX1370-LABEL: define dso_local void @test_amdgcn_tiled_load_mcast_2x2_extend_b128_zero_bitsize1(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly captures(none) [[INPTR:%.*]], ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[DST:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.ds.tiled.load.mcast.2x2.extend.b128(ptr addrspace(3) [[INPTR]], i32 0, i32 [[MASK]])
// CHECK-GFX1370-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 16, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void test_amdgcn_tiled_load_mcast_2x2_extend_b128_zero_bitsize1(local v4i* inptr, global v16uc* dst, int mask)
{
  *dst = __builtin_amdgcn_ds_tiled_load_mcast_2x2_extend_b128_zero(inptr, 1, mask);
}

// Test with constant mask
// CHECK-GFX1370-LABEL: define dso_local void @test_amdgcn_tiled_load_mcast_extend_b64_sign_imm(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly captures(none) [[INPTR:%.*]], ptr addrspace(1) noundef writeonly captures(none) initializes((0, 8)) [[DST:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.amdgcn.ds.tiled.load.mcast.extend.b64(ptr addrspace(3) [[INPTR]], i32 1, i32 7)
// CHECK-GFX1370-NEXT:    store <2 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 8, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void test_amdgcn_tiled_load_mcast_extend_b64_sign_imm(local v2i* inptr, global v8c* dst)
{
  *dst = __builtin_amdgcn_ds_tiled_load_mcast_extend_b64_sign(inptr, 1, 7);
}

// CHECK-GFX1370-LABEL: define dso_local void @test_amdgcn_tiled_load_mcast_2x2_extend_b128_zero_imm(
// CHECK-GFX1370-SAME: ptr addrspace(3) noundef readonly captures(none) [[INPTR:%.*]], ptr addrspace(1) noundef writeonly captures(none) initializes((0, 16)) [[DST:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-GFX1370-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.ds.tiled.load.mcast.2x2.extend.b128(ptr addrspace(3) [[INPTR]], i32 2, i32 15)
// CHECK-GFX1370-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[DST]], align 16, !tbaa [[TBAA14]]
// CHECK-GFX1370-NEXT:    ret void
//
void test_amdgcn_tiled_load_mcast_2x2_extend_b128_zero_imm(local v4i* inptr, global v16uc* dst)
{
  *dst = __builtin_amdgcn_ds_tiled_load_mcast_2x2_extend_b128_zero(inptr, 2, 15);
}

//.
// CHECK-GFX1370: [[TBAA4]] = !{[[META5:![0-9]+]], [[META5]], i64 0}
// CHECK-GFX1370: [[META5]] = !{!"int", [[META6:![0-9]+]], i64 0}
// CHECK-GFX1370: [[META6]] = !{!"omnipotent char", [[META7:![0-9]+]], i64 0}
// CHECK-GFX1370: [[META7]] = !{!"Simple C/C++ TBAA"}
// CHECK-GFX1370: [[META8]] = !{i32 3, i32 1}
// CHECK-GFX1370: [[META9]] = !{!"none", !"none"}
// CHECK-GFX1370: [[META10]] = !{!"int*", !"int*"}
// CHECK-GFX1370: [[META11]] = !{!"", !""}
// CHECK-GFX1370: [[META12]] = !{!"v2i*", !"v2i*"}
// CHECK-GFX1370: [[META13]] = !{!"int __attribute__((ext_vector_type(2)))*", !"int __attribute__((ext_vector_type(2)))*"}
// CHECK-GFX1370: [[TBAA14]] = !{[[META6]], [[META6]], i64 0}
// CHECK-GFX1370: [[META15]] = !{!"v4i*", !"v4i*"}
// CHECK-GFX1370: [[META16]] = !{!"int __attribute__((ext_vector_type(4)))*", !"int __attribute__((ext_vector_type(4)))*"}
// CHECK-GFX1370: [[META17]] = !{i32 3, i32 1, i32 0}
// CHECK-GFX1370: [[META18]] = !{!"none", !"none", !"none"}
// CHECK-GFX1370: [[META19]] = !{!"int*", !"int*", !"int"}
// CHECK-GFX1370: [[META20]] = !{!"", !"", !""}
// CHECK-GFX1370: [[META21]] = !{!"v2i*", !"v2i*", !"int"}
// CHECK-GFX1370: [[META22]] = !{!"int __attribute__((ext_vector_type(2)))*", !"int __attribute__((ext_vector_type(2)))*", !"int"}
// CHECK-GFX1370: [[META23]] = !{!"v4i*", !"v4i*", !"int"}
// CHECK-GFX1370: [[META24]] = !{!"int __attribute__((ext_vector_type(4)))*", !"int __attribute__((ext_vector_type(4)))*", !"int"}
// CHECK-GFX1370: [[META25]] = !{!"v3i*", !"v3i*", !"int"}
// CHECK-GFX1370: [[META26]] = !{!"int __attribute__((ext_vector_type(3)))*", !"int __attribute__((ext_vector_type(3)))*", !"int"}
//.
