// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu gfx1370 -target-feature +wavefrontsize32 -emit-llvm -o - %s | FileCheck %s --check-prefix=CHECK-GFX1370

typedef float v8f __attribute__((ext_vector_type(8)));
typedef int   v8i __attribute__((ext_vector_type(8)));
typedef int   v16i __attribute__((ext_vector_type(16)));

// CHECK-GFX1370-LABEL: @test_amdgcn_wmma_f32_16x16x128_iu8_gfx13(
// CHECK-GFX1370-NEXT:  entry:
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x128.iu8.clamp(i1 true, <16 x i32> [[A:%.*]], i1 true, <16 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1370-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA8:![0-9]+]]
// CHECK-GFX1370-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x128_iu8_gfx13(global v8f* out, v16i a, v16i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x128_iu8_clamp(1, a, 1, b, c, 1);
}

// CHECK-GFX1370-LABEL: @test_amdgcn_wmma_f32i32_16x16x128_iu8_gfx13(
// CHECK-GFX1370-NEXT:  entry:
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32i32.16x16x128.iu8.clamp(i1 true, <16 x i32> [[A:%.*]], i1 true, <16 x i32> [[B:%.*]], <8 x i32> [[C:%.*]], i1 true)
// CHECK-GFX1370-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA8]]
// CHECK-GFX1370-NEXT:    ret void
//
void test_amdgcn_wmma_f32i32_16x16x128_iu8_gfx13(global v8f* out, v16i a, v16i b, v8i c)
{
   *out = __builtin_amdgcn_wmma_f32i32_16x16x128_iu8_clamp(1, a, 1, b, c, 1);
}

// CHECK-GFX1370-LABEL: @test_amdgcn_wmma_i32_16x16x128_iu8_gfx13(
// CHECK-GFX1370-NEXT:  entry:
// CHECK-GFX1370-NEXT:    [[TMP0:%.*]] = tail call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x128.iu8.clamp(i1 true, <16 x i32> [[A:%.*]], i1 true, <16 x i32> [[B:%.*]], <8 x i32> [[C:%.*]], i1 true)
// CHECK-GFX1370-NEXT:    store <8 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA8]]
// CHECK-GFX1370-NEXT:    ret void
//
void test_amdgcn_wmma_i32_16x16x128_iu8_gfx13(global v8i* out, v16i a, v16i b, v8i c)
{
   *out = __builtin_amdgcn_wmma_i32_16x16x128_iu8_clamp(1, a, 1, b, c, 1);
}
