// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu gfx1370 -target-feature +wavefrontsize32 -emit-llvm -o - %s | FileCheck %s

typedef half v4h __attribute__((ext_vector_type(4)));
typedef short v2s __attribute__((ext_vector_type(2)));
typedef unsigned short v2us __attribute__((ext_vector_type(2)));

// CHECK-LABEL: @test_amdgcn_fma_from_tensor_f16_i16_4x2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.fma.from.tensor.f16.i16.v4f16(<4 x half> [[ACC:%.*]], <2 x i16> [[RESID_0:%.*]], <2 x i16> [[RESID_1:%.*]], <4 x half> [[SCALE:%.*]], i32 2, i1 true)
// CHECK-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8
// CHECK-NEXT:    ret void
//
void test_amdgcn_fma_from_tensor_f16_i16_4x2(global v4h *out, v4h acc, v2s resid_0, v2s resid_1, v4h scale) {
  *out = __builtin_amdgcn_fma_from_tensor_f16_i16_4x2(acc, resid_0, resid_1, scale, 2, true);
}

// CHECK-LABEL: @test_amdgcn_fma_from_tensor_f16_i16_4x4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.fma.from.tensor.f16.i16.v4f16(<4 x half> [[ACC:%.*]], <2 x i16> [[RESID_0:%.*]], <2 x i16> [[RESID_1:%.*]], <4 x half> [[SCALE:%.*]], i32 1, i1 true)
// CHECK-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8
// CHECK-NEXT:    ret void
//
void test_amdgcn_fma_from_tensor_f16_i16_4x4(global v4h *out, v4h acc, v2s resid_0, v2s resid_1, v4h scale) {
  *out = __builtin_amdgcn_fma_from_tensor_f16_i16_4x4(acc, resid_0, resid_1, scale, 1, true);
}

// CHECK-LABEL: @test_amdgcn_fma_from_tensor_f16_i16_8x4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.fma.from.tensor.f16.i16.v4f16(<4 x half> [[ACC:%.*]], <2 x i16> [[RESID_0:%.*]], <2 x i16> [[RESID_1:%.*]], <4 x half> [[SCALE:%.*]], i32 0, i1 true)
// CHECK-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8
// CHECK-NEXT:    ret void
//
void test_amdgcn_fma_from_tensor_f16_i16_8x4(global v4h *out, v4h acc, v2s resid_0, v2s resid_1, v4h scale) {
  *out = __builtin_amdgcn_fma_from_tensor_f16_i16_8x4(acc, resid_0, resid_1, scale, 0, true);
}

// CHECK-LABEL: @test_amdgcn_fma_from_tensor_f16_u16_4x2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.fma.from.tensor.f16.u16.v4f16(<4 x half> [[ACC:%.*]], <2 x i16> [[RESID_0:%.*]], <2 x i16> [[RESID_1:%.*]], <4 x half> [[SCALE:%.*]], i32 2, i1 true)
// CHECK-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8
// CHECK-NEXT:    ret void
//
void test_amdgcn_fma_from_tensor_f16_u16_4x2(global v4h *out, v4h acc, v2us resid_0, v2us resid_1, v4h scale) {
  *out = __builtin_amdgcn_fma_from_tensor_f16_u16_4x2(acc, resid_0, resid_1, scale, 2, true);
}

// CHECK-LABEL: @test_amdgcn_fma_from_tensor_f16_u16_4x4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.fma.from.tensor.f16.u16.v4f16(<4 x half> [[ACC:%.*]], <2 x i16> [[RESID_0:%.*]], <2 x i16> [[RESID_1:%.*]], <4 x half> [[SCALE:%.*]], i32 1, i1 true)
// CHECK-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8
// CHECK-NEXT:    ret void
//
void test_amdgcn_fma_from_tensor_f16_u16_4x4(global v4h *out, v4h acc, v2us resid_0, v2us resid_1, v4h scale) {
  *out = __builtin_amdgcn_fma_from_tensor_f16_u16_4x4(acc, resid_0, resid_1, scale, 1, true);
}

// CHECK-LABEL: @test_amdgcn_fma_from_tensor_f16_u16_8x4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.fma.from.tensor.f16.u16.v4f16(<4 x half> [[ACC:%.*]], <2 x i16> [[RESID_0:%.*]], <2 x i16> [[RESID_1:%.*]], <4 x half> [[SCALE:%.*]], i32 0, i1 true)
// CHECK-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8
// CHECK-NEXT:    ret void
//
void test_amdgcn_fma_from_tensor_f16_u16_8x4(global v4h *out, v4h acc, v2us resid_0, v2us resid_1, v4h scale) {
  *out = __builtin_amdgcn_fma_from_tensor_f16_u16_8x4(acc, resid_0, resid_1, scale, 0, true);
}
