// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-amd-amdhsa -target-cpu gfx1300 -x hip -emit-llvm -O2 -fcuda-is-device \
// RUN:   -o - %s | FileCheck %s

// Check that addrspaces are inferred on builtin ptr operands

#define __global__ __attribute__((global))
#define __shared__ __attribute__((shared))
#define __device__ __attribute__((device))
#define __exp_amd_laneshared__ __attribute__((exp_amd_laneshared))
#define __exp_amd_wavegroup_kernel(num_wavegroups, wave_size, block_x, block_y, block_z) \
    __attribute__((amdgpu_wavegroup_kernel(num_wavegroups, wave_size, block_x, block_y, block_z)))
#define __exp_amd_spatial_cluster__ \
    __attribute__((amdgpu_spatial_cluster_kernel))
#define __cluster_dims__(...) __attribute__((cluster_dims(__VA_ARGS__)))
#define HIP_INLINE __attribute__((always_inline))

__shared__ __amdgpu_semaphore0_t sema_next;
__shared__ __amdgpu_semaphore0_t sema_prev;

__exp_amd_laneshared__ int ls_next[2];
__exp_amd_laneshared__ int ls_prev[2];

__global__
__exp_amd_spatial_cluster__
__cluster_dims__(8, 1, 1)
__exp_amd_wavegroup_kernel(
        /* num_wavegroups */ 4,
        /* wave size */ 32,
        /* block_size */ 128, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z33spatial_kernel_infers_zero_offsetPiPKii(
// CHECK-SAME: ptr addrspace(1) noundef readnone captures(none) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readonly captures(none) [[IN_COERCE:%.*]], i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] !reqd_work_group_size [[META8:![0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.amdgcn.load.mcast.b32.p1(ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), ptr addrspace(1) [[IN_COERCE]], i32 0, i32 786432)
// CHECK-NEXT:    tail call void @llvm.amdgcn.load.mcast.b32.p1(ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), ptr addrspace(1) [[IN_COERCE]], i32 0, i32 786432)
// CHECK-NEXT:    tail call void @llvm.amdgcn.spatial.cluster.send.next(i32 0, ptr addrspace(10) @ls_next, ptr addrspace(3) @sema_next, ptr addrspace(10) @ls_prev, ptr addrspace(3) @sema_prev, i32 0)
// CHECK-NEXT:    tail call void @llvm.amdgcn.spatial.cluster.send.prev(i32 0, ptr addrspace(10) @ls_prev, ptr addrspace(3) @sema_prev, ptr addrspace(10) @ls_next, ptr addrspace(3) @sema_next, i32 0)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sema_next)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sema_prev)
// CHECK-NEXT:    fence syncscope("workgroup") acquire, !mmra [[META9:![0-9]+]]
// CHECK-NEXT:    ret void
//
void spatial_kernel_infers_zero_offset(int* out, const int* in, int size) {
  // There's no addrspacecast on the vnbr since it's zero offset from ls_next/prev.
  // MCast addrspace are inferred by directly looking at its operands.
  using pLSi32 = __attribute__((address_space(10))) int *;
  using pGi32 = __attribute__((address_space(1))) int *;
  int index = 0;
  auto src_laneshared_next = (pLSi32)&ls_next[index + 1];
  auto src_laneshared_prev = (pLSi32)&ls_prev[index + 1];
  auto dst_laneshared_next = (pLSi32)&ls_next[index];
  auto dst_laneshared_prev = (pLSi32)&ls_prev[index];
  auto src_global = (pGi32) &in[0];

  constexpr unsigned int nbytes = 4;
  constexpr unsigned int num_16B = nbytes / 16;

  __builtin_amdgcn_load_mcast_b32(
      (pLSi32)(src_laneshared_next),
      (pGi32)(src_global),
      0, 3 << 18);
  __builtin_amdgcn_load_mcast_b32(
      (pLSi32)(src_laneshared_prev),
      (pGi32)(src_global),
      0, 3 << 18);

  __builtin_amdgcn_spatial_cluster_send_next(
    0, // If this was *src_laneshared_next, i.e. a load, then the mcast addrspace would be inferred.
    dst_laneshared_next, &sema_next,
    dst_laneshared_prev, &sema_prev,
    0);
  __builtin_amdgcn_spatial_cluster_send_prev(
    0,
    dst_laneshared_prev, &sema_prev,
    dst_laneshared_next, &sema_next,
    0);

  __builtin_amdgcn_s_sema_wait(&sema_next);
  __builtin_amdgcn_s_sema_wait(&sema_prev);
  __builtin_amdgcn_fence(__ATOMIC_ACQUIRE, "workgroup", "laneshared");
}

__global__
__exp_amd_spatial_cluster__
__cluster_dims__(8, 1, 1)
__exp_amd_wavegroup_kernel(
        /* num_wavegroups */ 4,
        /* wave size */ 32,
        /* block_size */ 128, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z52spatial_kernel_correct_infer_addrspace_pre_referencePiPKii(
// CHECK-SAME: ptr addrspace(1) noundef readnone captures(none) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readnone captures(none) [[IN_COERCE:%.*]], i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR4:[0-9]+]] !reqd_work_group_size [[META8]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), align 4, !tbaa [[TBAA4:![0-9]+]]
// CHECK-NEXT:    tail call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[TMP0]], ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), ptr addrspace(3) @sema_next, ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), ptr addrspace(3) @sema_prev, i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    tail call void @llvm.amdgcn.spatial.cluster.send.prev(i32 [[TMP1]], ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), ptr addrspace(3) @sema_prev, ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), ptr addrspace(3) @sema_next, i32 0)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sema_next)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sema_prev)
// CHECK-NEXT:    fence syncscope("workgroup") acquire, !mmra [[META9]]
// CHECK-NEXT:    ret void
//
void spatial_kernel_correct_infer_addrspace_pre_reference(int* out, const int* in, int size) {
  // By referencing the ptr in a load before using, it allows address spaces to be inferred
  // everywhere.
  using pLSi32 = __attribute__((address_space(10))) int *;
  int index = 0;
  pLSi32 laneshared_next = (pLSi32)&ls_next[index + 1];
  pLSi32 laneshared_prev = (pLSi32)&ls_prev[index + 1];

  __builtin_amdgcn_spatial_cluster_send_next(
    *laneshared_next,
    laneshared_next, &sema_next,
    laneshared_prev, &sema_prev,
    0);
  __builtin_amdgcn_spatial_cluster_send_prev(
    *laneshared_prev,
    laneshared_prev, &sema_prev,
    laneshared_next, &sema_next,
    0);
  __builtin_amdgcn_s_sema_wait(&sema_next);
  __builtin_amdgcn_s_sema_wait(&sema_prev);
  __builtin_amdgcn_fence(__ATOMIC_ACQUIRE, "workgroup", "laneshared");
}

__global__
__exp_amd_spatial_cluster__
__cluster_dims__(8, 1, 1)
__exp_amd_wavegroup_kernel(
        /* num_wavegroups */ 4,
        /* wave size */ 32,
        /* block_size */ 128, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z53spatial_kernel_correct_infer_addrspace_post_referencePiPKii(
// CHECK-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 8)) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readnone captures(none) [[IN_COERCE:%.*]], i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR4]] !reqd_work_group_size [[META8]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(10) @ls_next, align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    tail call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[TMP0]], ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), ptr addrspace(3) @sema_next, ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), ptr addrspace(3) @sema_prev, i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(10) @ls_prev, align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    tail call void @llvm.amdgcn.spatial.cluster.send.prev(i32 [[TMP1]], ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), ptr addrspace(3) @sema_prev, ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), ptr addrspace(3) @sema_next, i32 0)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sema_next)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sema_prev)
// CHECK-NEXT:    fence syncscope("workgroup") acquire, !mmra [[META9]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    store i32 [[TMP2]], ptr addrspace(1) [[OUT_COERCE]], align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    [[ARRAYIDX11:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[OUT_COERCE]], i64 4
// CHECK-NEXT:    store i32 [[TMP3]], ptr addrspace(1) [[ARRAYIDX11]], align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    ret void
//
void spatial_kernel_correct_infer_addrspace_post_reference(int* out, const int* in, int size) {
  // By referencing the ptr after using, it allows address spaces to be inferred
  // everywhere.
  using pLSi32 = __attribute__((address_space(10))) int *;
  int index = 0;
  int* myNumNext = &ls_next[index];
  int* myNumPrev = &ls_prev[index];
  pLSi32 dst_laneshared_next = (pLSi32)&ls_next[index + 1];
  pLSi32 dst_laneshared_prev = (pLSi32)&ls_prev[index + 1];

  __builtin_amdgcn_spatial_cluster_send_next(
    *myNumNext,
    (pLSi32)dst_laneshared_next, &sema_next,
    (pLSi32)dst_laneshared_prev, &sema_prev,
    0);
  __builtin_amdgcn_spatial_cluster_send_prev(
    *myNumPrev,
    (pLSi32)dst_laneshared_prev, &sema_prev,
    (pLSi32)dst_laneshared_next, &sema_next,
    0);
  __builtin_amdgcn_s_sema_wait(&sema_next);
  __builtin_amdgcn_s_sema_wait(&sema_prev);
  __builtin_amdgcn_fence(__ATOMIC_ACQUIRE, "workgroup", "laneshared");
  // Here is the important use
  out[0] = *dst_laneshared_next;
  out[1] = *dst_laneshared_prev;
}

__global__
__exp_amd_spatial_cluster__
__cluster_dims__(8, 1, 1)
__exp_amd_wavegroup_kernel(
        /* num_wavegroups */ 4,
        /* wave size */ 32,
        /* block_size */ 128, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z38spatial_kernel_infer_addrspace_no_castPiPKii(
// CHECK-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 8)) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readnone captures(none) [[IN_COERCE:%.*]], i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR4]] !reqd_work_group_size [[META8]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    tail call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[TMP0]], ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), ptr addrspace(3) @sema_next, ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), ptr addrspace(3) @sema_prev, i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    tail call void @llvm.amdgcn.spatial.cluster.send.prev(i32 [[TMP1]], ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), ptr addrspace(3) @sema_prev, ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), ptr addrspace(3) @sema_next, i32 0)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sema_next)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sema_prev)
// CHECK-NEXT:    fence syncscope("workgroup") acquire, !mmra [[META9]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    store i32 [[TMP2]], ptr addrspace(1) [[OUT_COERCE]], align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr addrspace(10) getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[OUT_COERCE]], i64 4
// CHECK-NEXT:    store i32 [[TMP3]], ptr addrspace(1) [[ARRAYIDX13]], align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    ret void
//
void spatial_kernel_infer_addrspace_no_cast(int* out, const int* in, int size) {
  // Operands can be partially inferred via myNumNext, but for full knowledge
  // the operands of the send instructions must be checked.
  using pLSi32 = __attribute__((address_space(10))) int *;
  int index = 0;
  int* myNumNext = &ls_next[index + 1];
  int* myNumPrev = &ls_prev[index + 1];
  pLSi32 dst_laneshared_next = (pLSi32)&ls_next[index + 1];
  pLSi32 dst_laneshared_prev = (pLSi32)&ls_prev[index + 1];

  __builtin_amdgcn_spatial_cluster_send_next(
    *myNumNext,
    (pLSi32)dst_laneshared_next, &sema_next,
    (pLSi32)dst_laneshared_prev, &sema_prev,
    0);
  __builtin_amdgcn_spatial_cluster_send_prev(
    *myNumPrev,
    (pLSi32)dst_laneshared_prev, &sema_prev,
    (pLSi32)dst_laneshared_next, &sema_next,
    0);
  __builtin_amdgcn_s_sema_wait(&sema_next);
  __builtin_amdgcn_s_sema_wait(&sema_prev);
  __builtin_amdgcn_fence(__ATOMIC_ACQUIRE, "workgroup", "laneshared");
  out[0] = *myNumNext;
  out[1] = *myNumPrev;
}

__global__
__exp_amd_spatial_cluster__
__cluster_dims__(8, 1, 1)
__exp_amd_wavegroup_kernel(
        /* num_wavegroups */ 4,
        /* wave size */ 32,
        /* block_size */ 128, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z46spatial_kernel_common_case_infer_addrspacecastPiPKii(
// CHECK-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 8)) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readnone captures(none) [[IN_COERCE:%.*]], i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR4]] !reqd_work_group_size [[META8]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(10) @ls_next, align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    tail call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[TMP0]], ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), ptr addrspace(3) @sema_next, ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), ptr addrspace(3) @sema_prev, i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(10) @ls_prev, align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    tail call void @llvm.amdgcn.spatial.cluster.send.prev(i32 [[TMP1]], ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), ptr addrspace(3) @sema_prev, ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), ptr addrspace(3) @sema_next, i32 0)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sema_next)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sema_prev)
// CHECK-NEXT:    fence syncscope("workgroup") acquire, !mmra [[META9]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr addrspace(10) @ls_next, align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    store i32 [[TMP2]], ptr addrspace(1) [[OUT_COERCE]], align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr addrspace(10) @ls_prev, align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    [[ARRAYIDX11:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[OUT_COERCE]], i64 4
// CHECK-NEXT:    store i32 [[TMP3]], ptr addrspace(1) [[ARRAYIDX11]], align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    ret void
//
void spatial_kernel_common_case_infer_addrspacecast(int* out, const int* in, int size) {
  // Infers addrspace by looking at send operands.
  using pLSi32 = __attribute__((address_space(10))) int *;
  int index = 0;
  auto myNumNext = (pLSi32)&ls_next[index];
  auto myNumPrev = (pLSi32)&ls_prev[index];
  auto dst_laneshared_next = (pLSi32)&ls_next[index + 1];
  auto dst_laneshared_prev = (pLSi32)&ls_prev[index + 1];

  __builtin_amdgcn_spatial_cluster_send_next(
    *myNumNext,
    (pLSi32)dst_laneshared_next, &sema_next,
    (pLSi32)dst_laneshared_prev, &sema_prev,
    0);
  __builtin_amdgcn_spatial_cluster_send_prev(
    *myNumPrev,
    (pLSi32)dst_laneshared_prev, &sema_prev,
    (pLSi32)dst_laneshared_next, &sema_next,
    0);
  __builtin_amdgcn_s_sema_wait(&sema_next);
  __builtin_amdgcn_s_sema_wait(&sema_prev);
  __builtin_amdgcn_fence(__ATOMIC_ACQUIRE, "workgroup", "laneshared");
  out[0] = *myNumNext;
  out[1] = *myNumPrev;
}

__global__
__exp_amd_spatial_cluster__
__cluster_dims__(8, 1, 1)
__exp_amd_wavegroup_kernel(
        /* num_wavegroups */ 4,
        /* wave size */ 32,
        /* block_size */ 128, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z43spatial_kernel_infer_addrspace_no_referencePiPKii(
// CHECK-SAME: ptr addrspace(1) noundef readnone captures(none) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readnone captures(none) [[IN_COERCE:%.*]], i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR4]] !reqd_work_group_size [[META8]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(10) @ls_next, align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    tail call void @llvm.amdgcn.spatial.cluster.send.next(i32 [[TMP0]], ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), ptr addrspace(3) @sema_next, ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), ptr addrspace(3) @sema_prev, i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(10) @ls_prev, align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    tail call void @llvm.amdgcn.spatial.cluster.send.prev(i32 [[TMP1]], ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_prev, i32 4), ptr addrspace(3) @sema_prev, ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), ptr addrspace(3) @sema_next, i32 0)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sema_next)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sema_prev)
// CHECK-NEXT:    fence syncscope("workgroup") acquire, !mmra [[META9]]
// CHECK-NEXT:    ret void
//
void spatial_kernel_infer_addrspace_no_reference(int* out, const int* in, int size) {
  // Infers addrspace by looking at send operands.
  using pLSi32 = __attribute__((address_space(10))) int *;
  int index = 0;
  int* myNumNext = &ls_next[index];
  int* myNumPrev = &ls_prev[index];
  pLSi32 dst_laneshared_next = (pLSi32)&ls_next[index + 1];
  pLSi32 dst_laneshared_prev = (pLSi32)&ls_prev[index + 1];

  __builtin_amdgcn_spatial_cluster_send_next(
    *myNumNext,
    (pLSi32)dst_laneshared_next, &sema_next,
    (pLSi32)dst_laneshared_prev, &sema_prev,
    0);
  __builtin_amdgcn_spatial_cluster_send_prev(
    *myNumPrev,
    (pLSi32)dst_laneshared_prev, &sema_prev,
    (pLSi32)dst_laneshared_next, &sema_next,
    0);
  __builtin_amdgcn_s_sema_wait(&sema_next);
  __builtin_amdgcn_s_sema_wait(&sema_prev);
  __builtin_amdgcn_fence(__ATOMIC_ACQUIRE, "workgroup", "laneshared");
}

__shared__ int dds[32];
__shared__ int lds_buffer[64];

__global__ __cluster_dims__(2, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z22map_shared_rank_kernelPiPKi(
// CHECK-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 4)) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readnone captures(none) [[IN_COERCE:%.*]]) local_unnamed_addr #[[ATTR5:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(11) @llvm.amdgcn.map.shared.rank(ptr addrspace(3) nonnull getelementptr inbounds nuw (i8, ptr addrspace(3) @dds, i32 8), i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(11) [[TMP0]], align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    store i32 [[TMP1]], ptr addrspace(1) [[OUT_COERCE]], align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    ret void
//
void map_shared_rank_kernel(int* out, const int* in)
{
    using pDDSv = __attribute__((address_space(11))) void *;
    out[0] = ((int*)__builtin_amdgcn_map_shared_rank(&dds[2], 0))[0];
}

// Test query_shared_rank - verifies DDS pointer address space inference
__global__ __cluster_dims__(2, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z34query_shared_rank_infers_addrspacePiPKiPv(
// CHECK-SAME: ptr addrspace(1) noundef writeonly captures(none) initializes((0, 4)) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readnone captures(none) [[IN_COERCE:%.*]], ptr addrspace(1) noundef [[DDS_PTR_COERCE:%.*]]) local_unnamed_addr #[[ATTR7:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = addrspacecast ptr addrspace(1) [[DDS_PTR_COERCE]] to ptr addrspace(11)
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(11) [[TMP0]], i32 40
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.amdgcn.query.shared.rank(ptr addrspace(11) nonnull [[ARRAYIDX]])
// CHECK-NEXT:    store i32 [[TMP1]], ptr addrspace(1) [[OUT_COERCE]], align 4, !tbaa [[TBAA4]]
// CHECK-NEXT:    ret void
//
void query_shared_rank_infers_addrspace(int* out, const int* in, void* dds_ptr)
{
    out[0] = __builtin_amdgcn_query_shared_rank(&((__attribute__((address_space(11))) int *)dds_ptr)[10]);
}

// Test load_mcast with laneshared
__global__
__exp_amd_spatial_cluster__
__cluster_dims__(8, 1, 1)
__exp_amd_wavegroup_kernel(4, 32, 128, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z38load_mcast_infers_laneshared_addrspacePiPKi(
// CHECK-SAME: ptr addrspace(1) noundef readnone captures(none) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readonly captures(none) [[IN_COERCE:%.*]]) local_unnamed_addr #[[ATTR8:[0-9]+]] !reqd_work_group_size [[META8]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[IN_COERCE]], i64 16
// CHECK-NEXT:    tail call void @llvm.amdgcn.load.mcast.b32.p1(ptr addrspace(10) nonnull getelementptr inbounds nuw (i8, ptr addrspace(10) @ls_next, i32 4), ptr addrspace(1) nonnull [[ARRAYIDX]], i32 0, i32 3)
// CHECK-NEXT:    ret void
//
void load_mcast_infers_laneshared_addrspace(int* out, const int* in)
{
    using pLSi32 = __attribute__((address_space(10))) int *;
    using pGlobal = __attribute__((address_space(1))) int *;

    pLSi32 ls_dest = (pLSi32)&ls_next[1];
    pGlobal global_src = (pGlobal)&in[4];

    __builtin_amdgcn_load_mcast_b32(
        ls_dest,
        global_src,
        0,        // cachepolicy
        0x3);     // workgroup and SIMD broadcast mask
}

// Test global store async from LDS
__global__ __cluster_dims__(2, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z44global_store_async_from_lds_infers_addrspacePiPKi(
// CHECK-SAME: ptr addrspace(1) noundef writeonly captures(none) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readnone captures(none) [[IN_COERCE:%.*]]) local_unnamed_addr #[[ATTR9:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[OUT_COERCE]], i64 32
// CHECK-NEXT:    tail call void @llvm.amdgcn.global.store.async.from.lds.b32(ptr addrspace(1) nonnull [[ARRAYIDX]], ptr addrspace(3) nonnull getelementptr inbounds nuw (i8, ptr addrspace(3) @lds_buffer, i32 96), i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void global_store_async_from_lds_infers_addrspace(int* out, const int* in)
{
    using pGlobal = __attribute__((address_space(1))) int *;
    using pLDS = __attribute__((address_space(3))) int *;

    pGlobal global_dest = (pGlobal)&out[8];
    pLDS lds_src = (pLDS)&lds_buffer[24];

    __builtin_amdgcn_global_store_async_from_lds_b32(
        global_dest,
        lds_src,
        0,    // offset
        0);   // cachepolicy
}

// Test cluster async load to LDS
__global__ __cluster_dims__(2, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z42cluster_load_async_to_lds_infers_addrspacePiPKi(
// CHECK-SAME: ptr addrspace(1) noundef readnone captures(none) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readonly captures(none) [[IN_COERCE:%.*]]) local_unnamed_addr #[[ATTR9]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[IN_COERCE]], i64 24
// CHECK-NEXT:    tail call void @llvm.amdgcn.cluster.load.async.to.lds.b32(ptr addrspace(1) nonnull [[ARRAYIDX]], ptr addrspace(3) nonnull getelementptr inbounds nuw (i8, ptr addrspace(3) @lds_buffer, i32 80), i32 0, i32 0, i32 1)
// CHECK-NEXT:    ret void
//
void cluster_load_async_to_lds_infers_addrspace(int* out, const int* in)
{
    using pGlobal = __attribute__((address_space(1))) int *;
    using pLDS = __attribute__((address_space(3))) int *;

    pGlobal global_src = (pGlobal)&in[6];
    pLDS lds_dest = (pLDS)&lds_buffer[20];

    __builtin_amdgcn_cluster_load_async_to_lds_b32(
        global_src,
        lds_dest,
        0,    // offset
        0,    // cachepolicy
        0x1); // workgroup broadcast mask
}

// Test global async load to LDS
__global__ __cluster_dims__(2, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z41global_load_async_to_lds_infers_addrspacePiPKi(
// CHECK-SAME: ptr addrspace(1) noundef readnone captures(none) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readonly captures(none) [[IN_COERCE:%.*]]) local_unnamed_addr #[[ATTR9]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[IN_COERCE]], i64 16
// CHECK-NEXT:    tail call void @llvm.amdgcn.global.load.async.to.lds.b32(ptr addrspace(1) nonnull [[ARRAYIDX]], ptr addrspace(3) nonnull getelementptr inbounds nuw (i8, ptr addrspace(3) @lds_buffer, i32 48), i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void global_load_async_to_lds_infers_addrspace(int* out, const int* in)
{
    using pGlobal = __attribute__((address_space(1))) int *;
    using pLDS = __attribute__((address_space(3))) int *;

    pGlobal global_src = (pGlobal)&in[4];
    pLDS lds_dest = (pLDS)&lds_buffer[12];

    __builtin_amdgcn_global_load_async_to_lds_b32(
        global_src,
        lds_dest,
        0,    // offset
        0);   // cachepolicy
}

// Test DDS async mcast load
__global__ __cluster_dims__(2, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z44dds_load_async_mcast_to_lds_infers_addrspacePiPKi(
// CHECK-SAME: ptr addrspace(1) noundef readnone captures(none) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readnone captures(none) [[IN_COERCE:%.*]]) local_unnamed_addr #[[ATTR9]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(11) @llvm.amdgcn.map.shared.rank(ptr addrspace(3) nonnull getelementptr inbounds nuw (i8, ptr addrspace(3) @dds, i32 32), i32 0)
// CHECK-NEXT:    tail call void @llvm.amdgcn.dds.load.async.mcast.to.lds.b32(ptr addrspace(11) [[TMP0]], ptr addrspace(3) nonnull getelementptr inbounds nuw (i8, ptr addrspace(3) @lds_buffer, i32 64), i32 0, i32 0, i32 3)
// CHECK-NEXT:    ret void
//
void dds_load_async_mcast_to_lds_infers_addrspace(int* out, const int* in)
{
    using pDDS = __attribute__((address_space(11))) int *;
    using pLDS = __attribute__((address_space(3))) int *;

    // Get DDS pointer with offset
    pDDS dds_src = (pDDS)__builtin_amdgcn_map_shared_rank(&dds[8], 0);
    pLDS lds_dest = (pLDS)&lds_buffer[16];

    __builtin_amdgcn_dds_load_async_mcast_to_lds_b32(
        dds_src,
        lds_dest,
        0,        // offset
        0,        // cachepolicy
        0x3);     // workgroup broadcast mask
}

// Test DDS async load
__global__ __cluster_dims__(2, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z38dds_load_async_to_lds_infers_addrspacePiPKi(
// CHECK-SAME: ptr addrspace(1) noundef readnone captures(none) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readnone captures(none) [[IN_COERCE:%.*]]) local_unnamed_addr #[[ATTR9]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(11) @llvm.amdgcn.map.shared.rank(ptr addrspace(3) nonnull getelementptr inbounds nuw (i8, ptr addrspace(3) @dds, i32 16), i32 0)
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(11) [[TMP0]], i32 16
// CHECK-NEXT:    tail call void @llvm.amdgcn.dds.load.async.to.lds.b32(ptr addrspace(11) nonnull [[ARRAYIDX]], ptr addrspace(3) nonnull getelementptr inbounds nuw (i8, ptr addrspace(3) @lds_buffer, i32 32), i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void dds_load_async_to_lds_infers_addrspace(int* out, const int* in)
{
    using pDDS = __attribute__((address_space(11))) int *;
    using pLDS = __attribute__((address_space(3))) int *;

    // Get DDS pointer with offset via map_shared_rank
    pDDS dds_src = (pDDS)__builtin_amdgcn_map_shared_rank(&dds[4], 0);
    pLDS lds_dest = (pLDS)&lds_buffer[8];

    __builtin_amdgcn_dds_load_async_to_lds_b32(
        &dds_src[4],
        lds_dest,
        0,    // offset
        0);   // cachepolicy
}

static __shared__ __amdgpu_semaphore0_t g_semaphores[3];

__global__
__exp_amd_spatial_cluster__
__cluster_dims__(8, 1, 1)
__exp_amd_wavegroup_kernel(4, 32, 128, 1, 1)
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z25sema_ops_infers_addrspacePiPKi(
// CHECK-SAME: ptr addrspace(1) noundef readnone captures(none) [[OUT_COERCE:%.*]], ptr addrspace(1) noundef readnone captures(none) [[IN_COERCE:%.*]]) local_unnamed_addr #[[ATTR11:[0-9]+]] !reqd_work_group_size [[META8]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.set.limit(ptr addrspace(3) nonnull getelementptr inbounds nuw (i8, ptr addrspace(3) @_ZL12g_semaphores, i32 16), i32 1)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.set.state(ptr addrspace(3) nonnull getelementptr inbounds nuw (i8, ptr addrspace(3) @_ZL12g_semaphores, i32 16), i32 65536)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) nonnull getelementptr inbounds nuw (i8, ptr addrspace(3) @_ZL12g_semaphores, i32 16), i32 0)
// CHECK-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) nonnull getelementptr inbounds nuw (i8, ptr addrspace(3) @_ZL12g_semaphores, i32 16))
// CHECK-NEXT:    ret void
//
void sema_ops_infers_addrspace(int* out, const int* in)
{
    __builtin_amdgcn_s_sema_set_limit(&g_semaphores[1], 1);
    __builtin_amdgcn_s_sema_set_state(&g_semaphores[1], 65536);
    __builtin_amdgcn_s_sema_signal(&g_semaphores[1], 0);
    __builtin_amdgcn_s_sema_wait(&g_semaphores[1]);
}

//.
// CHECK: [[TBAA4]] = !{[[META5:![0-9]+]], [[META5]], i64 0}
// CHECK: [[META5]] = !{!"int", [[META6:![0-9]+]], i64 0}
// CHECK: [[META6]] = !{!"omnipotent char", [[META7:![0-9]+]], i64 0}
// CHECK: [[META7]] = !{!"Simple C++ TBAA"}
// CHECK: [[META8]] = !{i32 128, i32 1, i32 1}
// CHECK: [[META9]] = !{!"amdgpu-synchronize-as", !"laneshared"}
//.
