// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 5
// RUN: llvm-mc -triple=amdgcn -mcpu=gfx1260 -show-encoding %s | FileCheck --check-prefix=GFX1260 %s
// RUN: not llvm-mc -triple=amdgcn -mcpu=gfx1260 -mattr=-wavefrontsize32,+wavefrontsize64 -show-encoding %s 2>&1 | FileCheck --check-prefix=WAVESIZE-ERR --implicit-check-not=error: --strict-whitespace %s

v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255]
// GFX1260: v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] ; encoding: [0x00,0x00,0x8f,0xcc,0x20,0x61,0x02,0x1f]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] neg_lo:[1,0,0]
// GFX1260: v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] neg_lo:[1,0,0] ; encoding: [0x00,0x00,0x8f,0xcc,0x20,0x61,0x02,0x3f]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] neg_lo:[0,1,0]
// GFX1260: v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] neg_lo:[0,1,0] ; encoding: [0x00,0x00,0x8f,0xcc,0x20,0x61,0x02,0x5f]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] neg_lo:[0,0,1]
// GFX1260: v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] neg_lo:[0,0,1] ; encoding: [0x00,0x00,0x8f,0xcc,0x20,0x61,0x02,0x9f]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] matrix_a_reuse
// GFX1260: v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] matrix_a_reuse ; encoding: [0x00,0x20,0x8f,0xcc,0x20,0x61,0x02,0x1f]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] matrix_b_reuse
// GFX1260: v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] matrix_b_reuse ; encoding: [0x00,0x40,0x8f,0xcc,0x20,0x61,0x02,0x1f]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], 1.0
// GFX1260: v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], 1.0 ; encoding: [0x00,0x00,0x8f,0xcc,0x20,0x61,0xca,0x1b]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95]
// GFX1260: v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] ; encoding: [0x00,0x00,0x98,0xcc,0x20,0x81,0x03,0x1d]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] neg_lo:[1,0,0]
// GFX1260: v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] neg_lo:[1,0,0] ; encoding: [0x00,0x00,0x98,0xcc,0x20,0x81,0x03,0x3d]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] neg_lo:[0,1,0]
// GFX1260: v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] neg_lo:[0,1,0] ; encoding: [0x00,0x00,0x98,0xcc,0x20,0x81,0x03,0x5d]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] neg_lo:[0,0,1]
// GFX1260: v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] neg_lo:[0,0,1] ; encoding: [0x00,0x00,0x98,0xcc,0x20,0x81,0x03,0x9d]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] matrix_a_reuse
// GFX1260: v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] matrix_a_reuse ; encoding: [0x00,0x20,0x98,0xcc,0x20,0x81,0x03,0x1d]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] matrix_b_reuse
// GFX1260: v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] matrix_b_reuse ; encoding: [0x00,0x40,0x98,0xcc,0x20,0x81,0x03,0x1d]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], 1.0
// GFX1260: v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], 1.0 ; encoding: [0x00,0x00,0x98,0xcc,0x20,0x81,0xcb,0x1b]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_swmmac_bf16f32_32x64x32_bf16 v[192:255], v[0:7], v[8:39], v40
// GFX1260: v_swmmac_bf16f32_32x64x32_bf16 v[192:255], v[0:7], v[8:39], v40 ; encoding: [0xc0,0x00,0xa1,0xcc,0x00,0x11,0xa2,0x1c]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_swmmac_bf16f32_32x64x32_bf16 v[192:255], v[0:7], v[8:39], v40 index_key:1
// GFX1260: v_swmmac_bf16f32_32x64x32_bf16 v[192:255], v[0:7], v[8:39], v40 index_key:1 ; encoding: [0xc0,0x08,0xa1,0xcc,0x00,0x11,0xa2,0x1c]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_swmmac_bf16f32_32x64x32_bf16 v[192:255], v[0:7], v[8:39], v40 neg_lo:[1,0,0]
// GFX1260: v_swmmac_bf16f32_32x64x32_bf16 v[192:255], v[0:7], v[8:39], v40 neg_lo:[1,0,0] ; encoding: [0xc0,0x00,0xa1,0xcc,0x00,0x11,0xa2,0x3c]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_swmmac_bf16f32_32x64x32_bf16 v[192:255], v[0:7], v[8:39], v40 neg_lo:[0,1,0]
// GFX1260: v_swmmac_bf16f32_32x64x32_bf16 v[192:255], v[0:7], v[8:39], v40 neg_lo:[0,1,0] ; encoding: [0xc0,0x00,0xa1,0xcc,0x00,0x11,0xa2,0x5c]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_swmmac_bf16f32_32x64x32_bf16 v[192:255], v[0:7], v[8:39], v40 matrix_a_reuse
// GFX1260: v_swmmac_bf16f32_32x64x32_bf16 v[192:255], v[0:7], v[8:39], v40 matrix_a_reuse ; encoding: [0xc0,0x20,0xa1,0xcc,0x00,0x11,0xa2,0x1c]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32

v_swmmac_bf16f32_32x64x32_bf16 v[192:255], v[0:7], v[8:39], v40 matrix_b_reuse
// GFX1260: v_swmmac_bf16f32_32x64x32_bf16 v[192:255], v[0:7], v[8:39], v40 matrix_b_reuse ; encoding: [0xc0,0x40,0xa1,0xcc,0x00,0x11,0xa2,0x1c]
// WAVESIZE-ERR: :[[@LINE-2]]:1: error: instruction requires wavesize=32
