// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
// RUN: not llvm-mc -triple=amdgcn -mcpu=gfx1260 %s 2>&1 | FileCheck --check-prefix=GFX1260-ERR --implicit-check-not=error: %s

v_swmmac_bf16f32_32x64x32_bf16 v[200:263], v[0:7], v[8:39], v40
// GFX1260-ERR: :[[@LINE-1]]:32: error: register index is out of range

v_swmmac_bf16f32_32x64x32_bf16 v[24:87], |v[0:7]|, v[8:39], v40
// GFX1260-ERR: :[[@LINE-1]]:42: error: not a valid operand.

v_swmmac_bf16f32_32x64x32_bf16 v[24:87], -v[0:7], v[8:39], v40
// GFX1260-ERR: :[[@LINE-1]]:42: error: not a valid operand.

v_swmmac_bf16f32_32x64x32_bf16 v[24:87], v[0:7], v[8:39], v40 clamp
// GFX1260-ERR: :[[@LINE-1]]:63: error: invalid operand for instruction

v_swmmac_bf16f32_32x64x32_bf16 v[24:87], v[0:7], v[8:39], v40 neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:63: error: not a valid operand.
