// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
// RUN: not llvm-mc -triple=amdgcn -mcpu=gfx1260 %s 2>&1 | FileCheck --check-prefix=GFX1260-ERR --implicit-check-not=error: %s

v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[200:263]
// GFX1260-ERR: :[[@LINE-1]]:59: error: register index is out of range

v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], |v[48:79]|, v[192:255]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], -v[48:79], v[192:255]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] clamp
// GFX1260-ERR: :[[@LINE-1]]:70: error: invalid operand for instruction

v_wmma_bf16f32_32x64x32_bf16 v[0:31], v[32:47], v[48:79], v[192:255] neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:70: error: not a valid operand.

v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[200:263], v[64:95]
// GFX1260-ERR: :[[@LINE-1]]:49: error: register index is out of range

v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], |v[192:255]|, v[64:95]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], -v[192:255], v[64:95]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] clamp
// GFX1260-ERR: :[[@LINE-1]]:70: error: invalid operand for instruction

v_wmma_f16_32x64x128_bf8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:70: error: not a valid operand.

v_wmma_f16_32x64x128_bf8_fp8 v[0:31], v[32:63], v[200:263], v[64:95]
// GFX1260-ERR: :[[@LINE-1]]:49: error: register index is out of range

v_wmma_f16_32x64x128_bf8_fp8 v[0:31], v[32:63], |v[192:255]|, v[64:95]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f16_32x64x128_bf8_fp8 v[0:31], v[32:63], -v[192:255], v[64:95]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f16_32x64x128_bf8_fp8 v[0:31], v[32:63], v[192:255], v[64:95] clamp
// GFX1260-ERR: :[[@LINE-1]]:70: error: invalid operand for instruction

v_wmma_f16_32x64x128_bf8_fp8 v[0:31], v[32:63], v[192:255], v[64:95] neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:70: error: not a valid operand.

v_wmma_f16_32x64x128_fp8_bf8 v[0:31], v[32:63], v[200:263], v[64:95]
// GFX1260-ERR: :[[@LINE-1]]:49: error: register index is out of range

v_wmma_f16_32x64x128_fp8_bf8 v[0:31], v[32:63], |v[192:255]|, v[64:95]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f16_32x64x128_fp8_bf8 v[0:31], v[32:63], -v[192:255], v[64:95]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f16_32x64x128_fp8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] clamp
// GFX1260-ERR: :[[@LINE-1]]:70: error: invalid operand for instruction

v_wmma_f16_32x64x128_fp8_bf8 v[0:31], v[32:63], v[192:255], v[64:95] neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:70: error: not a valid operand.

v_wmma_f16_32x64x128_fp8_fp8 v[0:31], v[32:63], v[200:263], v[64:95]
// GFX1260-ERR: :[[@LINE-1]]:49: error: register index is out of range

v_wmma_f16_32x64x128_fp8_fp8 v[0:31], v[32:63], |v[192:255]|, v[64:95]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f16_32x64x128_fp8_fp8 v[0:31], v[32:63], -v[192:255], v[64:95]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f16_32x64x128_fp8_fp8 v[0:31], v[32:63], v[192:255], v[64:95] clamp
// GFX1260-ERR: :[[@LINE-1]]:70: error: invalid operand for instruction

v_wmma_f16_32x64x128_fp8_fp8 v[0:31], v[32:63], v[192:255], v[64:95] neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:70: error: not a valid operand.

v_wmma_f32_32x64x32_bf16 v[200:263], v[0:15], v[16:47], v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:26: error: register index is out of range

v_wmma_f32_32x64x32_bf16 v[192:255], v[0:15], |v[16:47]|, v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:47: error: not a valid operand.

v_wmma_f32_32x64x32_bf16 v[192:255], v[0:15], -v[16:47], v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:47: error: not a valid operand.

v_wmma_f32_32x64x32_bf16 v[192:255], v[0:15], v[16:47], v[128:191] clamp
// GFX1260-ERR: :[[@LINE-1]]:68: error: invalid operand for instruction

v_wmma_f32_32x64x32_bf16 v[192:255], v[0:15], v[16:47], v[128:191] neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:68: error: not a valid operand.

v_wmma_f32_32x64x32_f16 v[200:263], v[0:15], v[16:47], v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:25: error: register index is out of range

v_wmma_f32_32x64x32_f16 v[192:255], v[0:15], |v[16:47]|, v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:46: error: not a valid operand.

v_wmma_f32_32x64x32_f16 v[192:255], v[0:15], -v[16:47], v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:46: error: not a valid operand.

v_wmma_f32_32x64x32_f16 v[192:255], v[0:15], v[16:47], v[128:191] clamp
// GFX1260-ERR: :[[@LINE-1]]:67: error: invalid operand for instruction

v_wmma_f32_32x64x32_f16 v[192:255], v[0:15], v[16:47], v[128:191] neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:67: error: not a valid operand.

v_wmma_f32_32x64x128_bf8_bf8 v[0:63], v[64:95], v[200:263], v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:49: error: register index is out of range

v_wmma_f32_32x64x128_bf8_bf8 v[0:63], v[64:95], |v[192:255]|, v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f32_32x64x128_bf8_bf8 v[0:63], v[64:95], -v[192:255], v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f32_32x64x128_bf8_bf8 v[0:63], v[64:95], v[192:255], v[128:191] clamp
// GFX1260-ERR: :[[@LINE-1]]:72: error: invalid operand for instruction

v_wmma_f32_32x64x128_bf8_bf8 v[0:63], v[64:95], v[192:255], v[128:191] neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:72: error: not a valid operand.

v_wmma_f32_32x64x128_fp8_fp8 v[0:63], v[64:95], v[200:263], v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:49: error: register index is out of range

v_wmma_f32_32x64x128_fp8_fp8 v[0:63], v[64:95], |v[192:255]|, v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f32_32x64x128_fp8_fp8 v[0:63], v[64:95], -v[192:255], v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f32_32x64x128_fp8_fp8 v[0:63], v[64:95], v[192:255], v[128:191] clamp
// GFX1260-ERR: :[[@LINE-1]]:72: error: invalid operand for instruction

v_wmma_f32_32x64x128_fp8_fp8 v[0:63], v[64:95], v[192:255], v[128:191] neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:72: error: not a valid operand.

v_wmma_f32_32x64x128_fp8_bf8 v[0:63], v[64:95], v[200:263], v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:49: error: register index is out of range

v_wmma_f32_32x64x128_fp8_bf8 v[0:63], v[64:95], |v[192:255]|, v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f32_32x64x128_fp8_bf8 v[0:63], v[64:95], -v[192:255], v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f32_32x64x128_fp8_bf8 v[0:63], v[64:95], v[192:255], v[128:191] clamp
// GFX1260-ERR: :[[@LINE-1]]:72: error: invalid operand for instruction

v_wmma_f32_32x64x128_fp8_bf8 v[0:63], v[64:95], v[192:255], v[128:191] neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:72: error: not a valid operand.

v_wmma_f32_32x64x128_bf8_fp8 v[0:63], v[64:95], v[200:263], v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:49: error: register index is out of range

v_wmma_f32_32x64x128_bf8_fp8 v[0:63], v[64:95], |v[192:255]|, v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f32_32x64x128_bf8_fp8 v[0:63], v[64:95], -v[192:255], v[128:191]
// GFX1260-ERR: :[[@LINE-1]]:49: error: not a valid operand.

v_wmma_f32_32x64x128_bf8_fp8 v[0:63], v[64:95], v[192:255], v[128:191] clamp
// GFX1260-ERR: :[[@LINE-1]]:72: error: invalid operand for instruction

v_wmma_f32_32x64x128_bf8_fp8 v[0:63], v[64:95], v[192:255], v[128:191] neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:72: error: not a valid operand.

v_swmmac_bf16f32_32x64x32_bf16 v[200:263], v[0:7], v[8:39], v40
// GFX1260-ERR: :[[@LINE-1]]:32: error: register index is out of range

v_swmmac_bf16f32_32x64x32_bf16 v[24:87], |v[0:7]|, v[8:39], v40
// GFX1260-ERR: :[[@LINE-1]]:42: error: not a valid operand.

v_swmmac_bf16f32_32x64x32_bf16 v[24:87], -v[0:7], v[8:39], v40
// GFX1260-ERR: :[[@LINE-1]]:42: error: not a valid operand.

v_swmmac_bf16f32_32x64x32_bf16 v[24:87], v[0:7], v[8:39], v40 clamp
// GFX1260-ERR: :[[@LINE-1]]:63: error: invalid operand for instruction

v_swmmac_bf16f32_32x64x32_bf16 v[24:87], v[0:7], v[8:39], v40 neg_hi:[1,0,0]
// GFX1260-ERR: :[[@LINE-1]]:63: error: not a valid operand.
